### ISSUE TITLE
Segmentation fault (probably NULL pointer dereference) when running conf check

### ISSUE THREAD

**Issue by cve-reporting** [haproxy/haproxy#1026]
## Detailed description of the problem

haproxy crashes with SIG_SEGV when opening crafted configuration file.

## Expected behavior

haproxy should verify configuration without crash and display appropriate message. 

## Steps to reproduce the behavior

1. Download and unzip provided configuration file
[crash_000_srv_set_addr_desc_MINIMIZED.zip](https://github.com/haproxy/haproxy/files/5762423/crash_000_srv_set_addr_desc_MINIMIZED.zip)

2. Run the haproxy using following command:

     haproxy -c -f crash_000_srv_set_addr_desc_MINIMIZED

## Do you have any idea what may have caused this?

Incorrect parsing of configuration file.

## Do you have an idea how to solve the issue?

Not investigated

## What is your configuration?

haproxy (master branch)

## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 2.4-dev4-23cc52-55 2020/12/31 - https://haproxy.org/
Status: development branch - not safe for use in production.
Known bugs: https://github.com/haproxy/haproxy/issues?q=is:issue+is:open
Running on: Linux 5.4.0-58-generic #64~18.04.1-Ubuntu SMP Wed Dec 9 17:11:11 UTC 2020 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = 
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO -OPENSSL -LUA +FUTEX +ACCEPT4 -CLOSEFROM -ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS -OT -QUIC

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=8).
Built with network namespace support.
Built without compression support (neither USE_ZLIB nor USE_SLZ are set).
Compression algorithms supported : identity("identity")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built without PCRE or PCRE2 support (using libc's regex instead)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 7.5.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : none

Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace

```

```
Linux ABC 5.4.0-58-generic #64~18.04.1-Ubuntu SMP Wed Dec 9 17:11:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

## If HAProxy crashed: Last outputs and backtraces

Output:
```
Segmentation fault (core dumped)
```

Output (with AddressSanitizer):
```
ASAN:DEADLYSIGNAL
=================================================================
==3607==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x557e1de35c37 bp 0x61f000000c38 sp 0x7ffe3bfebbc0 T0)
==3607==The signal is caused by a READ memory access.
==3607==Hint: address points to the zero page.
    #0 0x557e1de35c36 in string_equal_bits include/import/ebtree.h:868
    #1 0x557e1de35c36 in __ebis_insert include/import/ebistree.h:205
    #2 0x557e1de35c36 in ebis_insert src/ebistree.c:41
    #3 0x557e1db64ee6 in srv_set_addr_desc src/server.c:222
    #4 0x557e1db7a0a5 in parse_server src/server.c:2090
    #5 0x557e1dbe64ab in cfg_parse_listen src/cfgparse-listen.c:551
    #6 0x557e1dbba2cf in readcfgfile src/cfgparse.c:2073
    #7 0x557e1dc9e1a2 in init src/haproxy.c:1846
    #8 0x557e1d9d6af5 in main src/haproxy.c:3088
    #9 0x7fb2e8d4ab96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
    #10 0x557e1d9da559 in _start (haproxy-master-ASAN/haproxy+0xf7559)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV include/import/ebtree.h:868 in string_equal_bits
==3607==ABORTING
```

Output from gdb:
```
process 11637 is executing new program: haproxy-master/haproxy
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff7180700 (LWP 12136)]
[Thread 0x7ffff7180700 (LWP 12136) exited]

Thread 1 "haproxy" received signal SIGSEGV, Segmentation fault.
string_equal_bits (ignore=<optimized out>, b=0x0, a=0x0) at include/import/ebtree.h:867
867	include/import/ebtree.h: No such file or directory.
#0  string_equal_bits (ignore=<optimized out>, b=0x0, a=0x0) at include/import/ebtree.h:867
        d = <optimized out>
        beg = 0
        c = <optimized out>
        beg = <optimized out>
        c = <optimized out>
        d = <optimized out>
#1  __ebis_insert (new=new@entry=0x555555a4f190, root=0x555555a4d838, root@entry=0x17f8) at include/import/ebistree.h:205
        new_left = <optimized out>
        new_rght = <optimized out>
        new_leaf = <optimized out>
        old_leaf = <optimized out>
        old = <optimized out>
        bit = <optimized out>
        old_node_bit = <optimized out>
        side = <optimized out>
        troot = 0x555555a4e460
        root_right = 0x1
        diff = <optimized out>
        old = <optimized out>
        side = <optimized out>
        troot = <optimized out>
        root_right = <optimized out>
        diff = <optimized out>
        bit = <optimized out>
        old_node_bit = <optimized out>
        new_left = <optimized out>
        new_rght = <optimized out>
        new_leaf = <optimized out>
        old_leaf = <optimized out>
        ret = <optimized out>
        new_left = <optimized out>
        new_rght = <optimized out>
        new_leaf = <optimized out>
        old_node = <optimized out>
#2  ebis_insert (root=root@entry=0x555555a4d838, new=new@entry=0x555555a4f190) at src/ebistree.c:41
No locals.
#3  0x000055555560ff44 in srv_set_addr_desc (s=s@entry=0x555555a4e5f0) at src/server.c:222
        p = 0x555555a4c040
        key = 0x0
        __pl_r = <optimized out>
        __pl_l = <optimized out>
        ret = <optimized out>
        __pl_l = <optimized out>
        __pl_r = <optimized out>
        __pl_l = <optimized out>
        ret = <optimized out>
        __pl_l = <optimized out>
#4  0x0000555555616cbd in parse_server (file=file@entry=0x555555a49a30 "crash_000_srv_set_addr_desc_MINIMIZED", linenum=linenum@entry=3, args=args@entry=0x7fffffffd750, curproxy=curproxy@entry=0x555555a4c040, defproxy=<optimized out>, parse_addr=parse_addr@entry=1, in_peers_section=0, initial_resolve=0) at src/server.c:2090
        sk = 0x7ffff7fa9d30
        port1 = 0
        port2 = 0
        port = 0
        cur_arg = 2
        defsrv = <optimized out>
        srv = <optimized out>
        tmpl_range_low = <optimized out>
        srv_tmpl = <optimized out>
        tmpl_range_high = <optimized out>
        newsrv = 0x555555a4e5f0
        err = <optimized out>
        errmsg = 0x0
        err_code = 0
        val = 0
        fqdn = 0x555555a4a7b0 "0"
#5  0x000055555563f7f1 in cfg_parse_listen (file=0x555555a49a30 "crash_000_srv_set_addr_desc_MINIMIZED", linenum=3, args=0x7fffffffd750, kwm=0) at src/cfgparse-listen.c:551
        curproxy = 0x555555a4c040
        err = <optimized out>
        rc = 0
        val = 1436850784
        err_code = 0
        cond = 0x0
        tmplogsrv = <optimized out>
        errmsg = 0x0
        bind_conf = <optimized out>
#6  0x000055555562fda2 in readcfgfile (file=0x555555a49a30 "crash_000_srv_set_addr_desc_MINIMIZED") at src/cfgparse.c:2073
        status = <optimized out>
        kwm = <optimized out>
        end = <optimized out>
        line = <optimized out>
        arg = 3
        args = {0x555555a4a270 "server", 0x555555a4a277 "0", 0x555555a4a279 "0", 0x555555a4a27a "" <repeats 62 times>}
        thisline = <optimized out>
        linesize = 2048
        f = 0x555555a49700
        linenum = 3
        err_code = 0
        cs = 0x555555a3c730
        pcs = 0x0
        ics = <optimized out>
        readbytes = 0
        outline = 0x555555a4a270 "server"
        outlen = 11
        outlinesize = 1024
        fatal = 0
        missing_lf = 10
#7  0x000055555567963e in init (argc=<optimized out>, argv=<optimized out>) at src/haproxy.c:1846
        ret = <optimized out>
        trash = 0x7ffff7fab630
        arg_mode = <optimized out>
        tmp = <optimized out>
        cfg_pidfile = <optimized out>
        err_code = 0
        err_msg = 0x0
        wl = 0x555555a49a10
        progname = 0x7fffffffe206 "haproxy"
        change_dir = <optimized out>
        px = <optimized out>
        pcf = <optimized out>
        ideal_maxconn = <optimized out>
#8  0x0000555555589d07 in main (argc=4, argv=0x7fffffffde48) at src/haproxy.c:3088
        err = <optimized out>
        retry = <optimized out>
        limit = {rlim_cur = 1024, rlim_max = 4096}
        pidfd = -1

```

**Comment by TimWolla** [comment]
Thank you, this crash is very fresh and was introduced in 92149f9a82a9b55c598f1cc815bc330c555f3561 (unreleased as of now).

I sent a patch: https://www.mail-archive.com/haproxy@formilux.org/msg39315.html
