### ISSUE TITLE
SIGBUS on FreeBSD 12.2-RELEASE for 2.2.7

### ISSUE THREAD

**Issue by xorander00** [haproxy/haproxy#1045]
## Detailed description of the problem

2.2.7 randomly crashes with SIGBUS (signal 10) on FreeBSD 12.2-RELEASE.  Wish I could be more specific, but I have been unable to narrow down a potential set of conditions that causes the crash.

## Expected behavior

Operate as normal without crashing.

## Steps to reproduce the behavior

Unsure, as not able to pinpoint any specific set of conditions as of yet that causes the crash.

## Do you have any idea what may have caused this?  
  
Nope, but I did load the core dump into gdb.  (see below)

## Do you have an idea how to solve the issue?  
  
Nope.

## What is your configuration?

```
global
	set-dumpable
    daemon
    log                                     127.0.0.1:514 local0
    user                                    www
    group                                   www

    server-state-file                       /var/run/haproxy.state
    stats socket                            /var/run/haproxy.sock mode 660 level admin expose-fd listeners
    stats timeout                           30s

    maxconn                                 50000

    ssl-default-bind-ciphers                ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!3DES:!MD5:!PSK
    ssl-default-bind-options                ssl-min-ver TLSv1.3 no-tls-tickets
    tune.ssl.default-dh-param               2048
    tune.ssl.maxrecord                      1370

    userlist basic-auth-list
        group is-admin
        user <REDACTED>                     password <REDACTED> groups is-admin

resolvers myresolvers
	accepted_payload_size					8192
    hold valid                              0s
    hold obsolete                           2s
    hold timeout                            2s
    hold refused                            2s
    hold nx                                 2s
    hold other                              2s
    timeout resolve                         1s
    timeout retry                           1s
    resolve_retries                         3
	nameserver dns0                         127.0.0.1:53

defaults
    mode                                    http
    balance                                 roundrobin
    log                                     global
    option                                  httplog
    option                                  dontlognull
    option                                  forwardfor
    option                                  redispatch
    option                                  http-server-close
    retries                                 3
    timeout client                          30s
    timeout server                          30s
    timeout connect                         30s
    timeout queue                           30s
    timeout check                           30s
    timeout http-request                    30s
    timeout http-keep-alive                 30s
    timeout tunnel                          6h
    default-server                          resolvers myresolvers resolve-prefer ipv4 resolve-opts allow-dup-ip check inter 1s init-addr last,libc,none
```

## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 2.2.7-f10629d 2021/01/08 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.7.html
Running on: FreeBSD 12.2-RELEASE-p1 FreeBSD 12.2-RELEASE-p1 GENERIC amd64
Build options :
  TARGET  = freebsd
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-missing-field-initializers -Wno-string-plus-int -Wtype-limits -Wshift-negative-value -Wnull-dereference -DFREEBSD_PORTS
  OPTIONS = USE_PCRE=1 USE_PCRE_JIT=1 USE_STATIC_PCRE=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ACCEPT4=1 USE_ZLIB=1 USE_CPU_AFFINITY=1
  DEBUG   =

Feature list : -EPOLL +KQUEUE -NETFILTER +PCRE +PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -BACKTRACE +STATIC_PCRE -STATIC_PCRE2 +TPROXY -LINUX_TPROXY -LINUX_SPLICE +LIBCRYPT -CRYPT_H +GETADDRINFO +OPENSSL +LUA -FUTEX +ACCEPT4 +CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY -TFO -NS -DL -RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER -PRCTL -THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=8).
Built with OpenSSL version : OpenSSL 1.1.1i  8 Dec 2020
Running on OpenSSL version : OpenSSL 1.1.1i  8 Dec 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.6
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_BINDANY IPV6_BINDANY
Built with PCRE version : 8.44 2020-02-12
Running on PCRE version : 8.44 2020-02-12
PCRE library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with clang compiler version 10.0.1 (git@github.com:llvm/llvm-project.git llvmorg-10.0.1-0-gef32c611aa2)
Built with the Prometheus exporter as a service

Available polling systems :
     kqueue : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use kqueue.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services :
        prometheus-exporter

Available filters :
        [SPOE] spoe
        [COMP] compression
        [TRACE] trace
        [CACHE] cache
        [FCGI] fcgi-app
```

```
FreeBSD eddie 12.2-RELEASE-p1 FreeBSD 12.2-RELEASE-p1 GENERIC  amd64
```

## If HAProxy crashed: Last outputs and backtraces

```
2021-01-11T21:52:22.509632-05:00 nsa0 kernel: pid 90443 (haproxy), jid 0, uid 80: exited on signal 10 (core dumped)
```

```
GNU gdb (GDB) 10.1 [GDB v10.1 for FreeBSD]
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-portbld-freebsd12.2".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/local/sbin/haproxy...
(No debugging symbols found in /usr/local/sbin/haproxy)
[New LWP 101357]
[New LWP 100653]
Core was generated by `/usr/local/sbin/haproxy -q -f /usr/local/etc/haproxy/master.conf -p /var/run/hap'.
Program terminated with signal SIGBUS, Bus error.
#0  0x00000000003eb3b7 in ?? ()
[Current thread is 1 (LWP 101357)]
(gdb) t a a bt full

Thread 2 (LWP 100653):
#0  0x0000000800b0025a in _kevent () from /lib/libc.so.7
No symbol table info available.
#1  0x0000000800547fc3 in ?? () from /lib/libthr.so.3
No symbol table info available.
#2  0x00000000002c6d74 in ?? ()
No symbol table info available.
#3  0x00000000003ce4ec in run_poll_loop ()
No symbol table info available.
#4  0x00000000003d2ba1 in ?? ()
No symbol table info available.
#5  0x00000000003cfb79 in main ()
No symbol table info available.

Thread 1 (LWP 101357):
#0  0x00000000003eb3b7 in ?? ()
No symbol table info available.
#1  0x00000000003e9afd in ?? ()
No symbol table info available.
#2  0x0000000000433b8f in dgram_fd_handler ()
No symbol table info available.
#3  0x00000000002c71c0 in ?? ()
No symbol table info available.
#4  0x00000000003ce4ec in run_poll_loop ()
No symbol table info available.
#5  0x00000000003d2ba1 in ?? ()
No symbol table info available.
#6  0x0000000800544fac in ?? () from /lib/libthr.so.3
No symbol table info available.
#7  0x0000000000000000 in ?? ()
No symbol table info available.
Backtrace stopped: Cannot access memory at address 0x7fffdfdfd000
(gdb)
```

## Additional information (if helpful)

**(gdb) disass 0x3eb3a0,+100**
```
(gdb) disass 0x3eb3a0,+100
Dump of assembler code from 0x3eb3a0 to 0x3eb404:
   0x00000000003eb3a0:  shl    $0xb,%rcx
   0x00000000003eb3a4:  lea    (%rcx,%rsi,1),%rdi
   0x00000000003eb3a8:  add    $0x5d03a0,%rdi
   0x00000000003eb3af:  mov    0x5d03a0(%rcx,%rsi,1),%rax
=> 0x00000000003eb3b7:  mov    %rax,(%rbx)
   0x00000000003eb3ba:  mov    %rbx,0x5d03a0(%rcx,%rsi,1)
   0x00000000003eb3c2:  mov    (%rbx),%rax
   0x00000000003eb3c5:  mov    %rbx,0x8(%rax)
   0x00000000003eb3c9:  mov    %rdi,0x8(%rbx)
   0x00000000003eb3cd:  mov    $0xffffffffffffd558,%rax
   0x00000000003eb3d4:  mov    %fs:0x0,%rdi
   0x00000000003eb3dd:  mov    (%rdi,%rax,1),%rax
   0x00000000003eb3e1:  mov    0x30(%rax),%r8
   0x00000000003eb3e5:  lea    0x10(%rbx),%r10
   0x00000000003eb3e9:  mov    %r8,0x10(%rbx)
   0x00000000003eb3ed:  mov    %r10,0x30(%rax)
   0x00000000003eb3f1:  lea    0x30(%rax),%r8
   0x00000000003eb3f5:  mov    0x10(%rbx),%rax
   0x00000000003eb3f9:  mov    %r10,0x8(%rax)
   0x00000000003eb3fd:  mov    %r8,0x18(%rbx)
   0x00000000003eb401:  addl   $0x1,0x5d03b8(%rcx,%rsi,1)
End of assembler dump.
(gdb)
```  
  
**(gdb) info reg**
```
(gdb) info reg
rax            0x5d0d00            6098176
rbx            0x29cd051af1131b3e  3012069339052579646
rcx            0x800               2048
rdx            0xb                 11
rsi            0x160               352
rdi            0x5d0d00            6098176
rbp            0x7fffdfdfab70      0x7fffdfdfab70
rsp            0x7fffdfdfab60      0x7fffdfdfab60
r8             0x6c65686469757169  7810763909219316073
r9             0xfffffffffffffd00  -768
r10            0x67726f036c6c6568  7454142393746220392
r11            0x246               582
r12            0x801b2d3d0         34388235216
r13            0x800dcf780         34374219648
r14            0x5c9f40            6070080
r15            0x7fffdfdfacb6      140736949365942
rip            0x3eb3b7            0x3eb3b7
eflags         0x10206             [ PF IF RF ]
cs             0x43                67
ss             0x3b                59
ds             <unavailable>
es             <unavailable>
fs             <unavailable>
gs             <unavailable>
fs_base        <unavailable>
gs_base        <unavailable>
(gdb)
```

**Comment by xorander00** [comment]
Oh, and got help on IRC that gave further insight into it.  Snippet of conversation as follows...

```
<RhodiumToad> ok. so this is almost certainly a bug in haproxy
<RhodiumToad> rbx should contain some valid pointer value, but instead it has garbage.
<_xor> I'd figure as much if 2.2.6 is working but not 2.2.7.  What's the insight your seeing from my pastes?
<RhodiumToad> and garbage that points outside of canonical space, hence the SIGBUS rather than SIGSEGV
<_xor> Oh I see.
<RhodiumToad> amd64 arch doesn't (yet, and possibly ever) allow using all 64 address bits, so some number of bits at the top of a pointer must be either all 0 or all 1
<_xor> Yup, I do remember that "bit" of info *rimshot*
<RhodiumToad> hence, valid user-space pointers are always in the range 0 .. 0x7fffffffffff
<V_PauAmma_V> That's because it's a most significant bit, right?
<_xor> Hmm, I wonder if it's present in 2.2.6 but didn't come up in my case until 2.2.7 because of some change that triggered it.
<RhodiumToad> hard to say without more extensive debugging
```

**Comment by wtarreau** [comment]
Thanks. I'm seeing you're using resolvers, and a fix that was backported in 2.2.7 actually introduced a regression and was reverted from 2.4. I'm going to revert it there as well and issue a new set of stable releases in order to address this. In the mean time, please apply this patch which reverts it.
[a.diff.txt](https://github.com/haproxy/haproxy/files/5807177/a.diff.txt)

**Comment by xorander00** [comment]
Thank you for the prompt reply, appreciate it!  Will apply patch and re-compile.

**Comment by gtech99** [comment]
> Thank you for the prompt reply, appreciate it! Will apply patch and re-compile.

Can you confirm whether this patch fixed the issue ?

**Comment by xorander00** [comment]
I did, it appears to have fixed the issue.  Thank you! :)
