### ISSUE TITLE
segfault: haproxy 2.1.4 version 

### ISSUE THREAD

**Issue by zino7825** [haproxy/haproxy#1169]
## Detailed description of the problem

haproxy server was down after segfault.
Servers are down repeatedly.

## Steps to reproduce the behavior

We don't have any ideas.
Occurs suddenly during operation.

## What is your configuration?

```
######################################################################################################################################
######################################################## Global Configuration ########################################################
######################################################################################################################################
global
    log 127.0.0.1 local0 notice
    log "${logserver}:514" len 65535 local0
    log-send-hostname
    log-tag default
    daemon
    nbthread 18
    hard-stop-after 300s

    ### CPU Mapping ###
    cpu-map auto:1/13-18 1 3 5 7 9 11
    cpu-map auto:1/1-12 4 6 8 10 12 14 16 18 13 15 17 19

    # User
    user haproxy
    group haproxy

    # http statistics socket
    stats socket /var/run/haproxy.stat-1 uid 0 level admin expose-fd listeners process 1

    pidfile /var/run/haproxy.pid
    unix-bind prefix /var/run/ mode 660 user haproxy group haproxy
    spread-checks 5
    tune.bufsize 32768
    tune.maxrewrite 1024
    tune.ssl.cachesize 500000
    tune.ssl.lifetime 86000
    maxconn 3200000
    set-dumpable

    crt-base /etc/haproxy/ssl/certs
    ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
    ssl-default-bind-ciphers EECDH+AES128+AESGCM:EECDH+AES256+AESGCM:EECDH+CHACHA20:EECDH+AES128+SHA:EECDH+AES256+SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA:AES256-SHA:RSA+3DES:+aRSA
    ssl-default-bind-options ssl-min-ver TLSv1.0 ssl-max-ver TLSv1.3
    server-state-base /var/run
    #server-state-file .global_server_state

    lua-load lua/functions.lua

###################################################################
####################### SSL offloading #############################
####################################################################
    listen ssl-proxy
    mode tcp
    log-tag ssl
    log "${logserver}:514" len 8092 local0

    option dontlog-normal
    option dontlognull
    option log-health-checks
    option redispatch
    option tcp-smart-accept
    option tcp-smart-connect
    option abortonclose
    option splice-auto
    option tcplog

    ### server connection retries ####
    retries 2

    #### timeout parameter ####
    timeout connect 3100
    timeout client 65s
    timeout server 65s
    timeout check 3s
    timeout queue 10s
    timeout tarpit 30s

    backlog 70000
    maxconn 2000000

    bind :443 tfo ssl curves X25519:P-256 crt "${crt}" crt sni alpn h2,http/1.1 tls-ticket-keys /etc/haproxy/ssl/key/ticket.keys process 1/1-12

    #### whitelist/blacklist ####
    tcp-request connection accept if { src -f /etc/haproxy/etc/acl/ip_whitelist.acl }
    tcp-request connection reject if { src -f /etc/haproxy/etc/acl/ip_blacklist.acl }

    server https unix@/var/run/https send-proxy-v2 maxconn 500000

######################################################################################################################################
####################################################### Default HTTP Definition ######################################################
######################################################################################################################################
defaults HTTP
    #### logging ####
    log global
    log-tag default

    #### log format ####
    log-format @cee:{\"client_ip\":\"%ci\",\"client_port\":\"%cp\",\"time\":\"%t\",\"frontend\":\"%ft\",\"backend\":\"%b\",\"server\":\"%s\",\"time_event\":\"Ti:%Ti/TR:%TR/Tw:%Tw/Tc:%Tc/Tr:%Tr/Ta:%Ta/Tt:%Tt\",\"upload\":%U,\"bytes\":%B,\"tsc\":\"%tsc\",\"current_conn\":\"total:%ac/front:%fc/backend:%bc/srv:%sc/retry:%rc\",\"queue_length\":\"srv:%sq/backend:%bq\",\"fe_ip\":\"%fi\",\"be_ip\":\"%bi\",\"be_port\":\"%bp\",\"status_code\":\"%ST\",\"srv_ip\":\"%si\",\"srv_port\":\"%sp\",\"domain\":\"%[capture.req.hdr(0)]\",\"referer\":\"%[capture.req.hdr(1)]\",\"user-agent\":\"%[capture.req.hdr(2)]\",\"resp_header\":\"%hs\",\"request\":\"%r\"}


    #### error file list ####
    errorfile 200 /etc/haproxy/etc/errfile/200.http
    errorfile 400 /etc/haproxy/etc/errfile/400.http
    errorfile 403 /etc/haproxy/etc/errfile/403.http
    errorfile 408 /etc/haproxy/etc/errfile/408.http
    errorfile 500 /etc/haproxy/etc/errfile/500.http
    errorfile 502 /etc/haproxy/etc/errfile/502.http
    errorfile 503 /etc/haproxy/etc/errfile/503.http
    errorfile 504 /etc/haproxy/etc/errfile/504.http

    #### mode(http or tcp) ####
    mode http

    #### option ####
    option http-keep-alive
    option http-ignore-probes
    option dontlognull
    option log-health-checks
    #option dontlog-normal
    option contstats
    option redispatch
    option tcp-smart-accept
    option tcp-smart-connect
    option abortonclose
    option splice-auto

    #### not comply with RFC7230 ####
    option accept-invalid-http-request

    #### server connection retries ####
    retries 2

    #### timeout parameter ####
    timeout connect 3100
    timeout client 65s
    timeout server 65s
    timeout check 3s
    timeout queue 10s
    timeout tarpit 30s
    timeout http-request 10s
    timeout http-keep-alive 60s

    #### default proxy max connection ####
    maxconn 3100000

    #### default balance algorithm ####
    balance roundrobin

    #### default server options ####
    default-server maxconn 2000 inter 5s fastinter 2s downinter 10s rise 3 fall 2 slowstart 10s agent-inter 20s agent-port 9999
    #load-server-state-from-file global

####################################################################
################# Tarpit/Deny backend Definition ###################
####################################################################
backend bk_tarpit
    id 2
    http-request tarpit

backend bk_deny
    id 3
    http-request deny

backend bk_silentdrop
    id 4
    http-request silent-drop


####################################################################
#################### HTTP FrontEnd Definition ######################
####################################################################
frontend http-edge
    id 11
    bind :80 process 1/13-18
    log-tag http

    #### listen queue ####
    backlog 70000

    #### timeout configuration ####
    timeout http-keep-alive 5s

    #### Monitoring ACL ####
    acl maintenance src -f /etc/haproxy/etc/acl/monitor-net.acl

    #### whitelist/blacklist ####
    tcp-request connection accept if { src -f /etc/haproxy/etc/acl/ip_whitelist.acl }
    tcp-request connection silent-drop if { src -f /etc/haproxy/etc/acl/ip_blacklist.acl }

    #### Monitoring URL ####
    monitor-uri /monitor/check
    monitor fail if maintenance

    #### Bad headers ####
    acl FORBIDDEN_HDR req.hdr_cnt(Host) gt 1
    acl FORBIDDEN_HDR req.hdr_cnt(Content-Length) gt 1
    #acl FORBIDDEN_HDR req.hdr_val(Content-Length) lt 0
    acl FORBIDDEN_HDR req.hdr_cnt(Range) gt 10

    #### Hdr filtering ####
    acl ABUSER req.hdr(Cache-Control) -m sub -f /etc/haproxy/etc/acl/cc_blacklist.acl
    acl ABUSER req.hdr(User-Agent) -m sub -f /etc/haproxy/etc/acl/ua_blacklist.acl

    #### Bad urls ####
    acl FORBIDDEN_URI url_reg -i -f /etc/haproxy/etc/acl/urlreg_blacklist.acl
    acl FORBIDDEN_URI url_sub -i -f /etc/haproxy/etc/acl/urlsub_blacklist.acl

    ### Host Header Adjusting ###
    http-request replace-value Host (.*):.* \1
    http-request set-header Host %[hdr(Host),lower]

    #### MAP ACL
    http-request set-var(txn.dom_ip) src,lower,map_ip(/etc/haproxy/etc/acl/dom_ip_blacklist.map)
    http-request set-var(txn.dom_ua) hdr(User-Agent),lower,regsub(\s, ,g),map_sub(/etc/haproxy/etc/acl/dom_ua_blacklist.map)
    http-request set-var(txn.dom_cc) hdr(Cache-Control),lower,map_sub(/etc/haproxy/etc/acl/dom_cc_blacklist.map)
    http-request set-var(txn.host) hdr(Host)

    acl ABUSER lua.compare_values(txn.dom_ip,txn.host) -m bool
    acl ABUSER lua.compare_values(txn.dom_ua,txn.host) -m bool
    acl ABUSER lua.compare_values(txn.dom_cc,txn.host) -m bool

    #### Silent drop bad requests ####
    http-request silent-drop if ABUSER
    http-request deny if FORBIDDEN_HDR || FORBIDDEN_URI

    http-request set-header X-Forwarded-Proto http

    #### Add custom logging ####
    capture request header Host len 64
    capture request header Referer len 512
    capture request header User-Agent len 512
    capture request header Content-Length len 10
    capture response header Content-Length len 10
    capture response header Content-Type len 32

    #### backend selection ####
    use_backend %[base,map_beg(/etc/haproxy/etc/acl/base_to_backend.map,default)] if { base,map_beg(/etc/haproxy/etc/acl/base_to_backend.map) -m found }
    use_backend %[hdr(Host),lower,map(/etc/haproxy/etc/acl/host_to_backend.map,bk_silentdrop)]

####################################################################
################### HTTPS FrontEnd Definition ######################
####################################################################
frontend https-edge
    id 12
    bind unix@https tfo accept-proxy process 1/13-18
    log-tag https

    #### listen queue ####
    backlog 70000

    #### Monitoring ACL ####
    acl maintenance src -f /etc/haproxy/etc/acl/monitor-net.acl

    #### Monitoring URL ####
    monitor-uri /monitor/check
    monitor fail if maintenance

    #### Bad headers ####
    acl FORBIDDEN_HDR req.hdr_cnt(Host) gt 1
    acl FORBIDDEN_HDR req.hdr_cnt(Content-Length) gt 1
    acl FORBIDDEN_HDR req.hdr_cnt(Range) gt 10

    #### Hdr filtering ####
    acl ABUSER req.hdr(Cache-Control) -m sub -f /etc/haproxy/etc/acl/cc_blacklist.acl
    acl ABUSER req.hdr(User-Agent) -m sub -f /etc/haproxy/etc/acl/ua_blacklist.acl

    #### Bad urls ####
    acl FORBIDDEN_URI url_reg -i -f /etc/haproxy/etc/acl/urlreg_blacklist.acl
    acl FORBIDDEN_URI url_sub -i -f /etc/haproxy/etc/acl/urlsub_blacklist.acl

    ### Host Header Adjusting ###
    http-request replace-value Host (.*):.* \1
    http-request set-header Host %[hdr(Host),lower]

    #### MAP ACL
    http-request set-var(txn.dom_ip) src,lower,map_ip(/etc/haproxy/etc/acl/dom_ip_blacklist.map)
    http-request set-var(txn.dom_ua) hdr(User-Agent),lower,regsub(\s, ,g),map_sub(/etc/haproxy/etc/acl/dom_ua_blacklist.map)
    http-request set-var(txn.dom_cc) hdr(Cache-Control),lower,map_sub(/etc/haproxy/etc/acl/dom_cc_blacklist.map)
    http-request set-var(txn.host) hdr(Host)

    acl ABUSER lua.compare_values(txn.dom_ip,txn.host) -m bool
    acl ABUSER lua.compare_values(txn.dom_ua,txn.host) -m bool
    acl ABUSER lua.compare_values(txn.dom_cc,txn.host) -m bool

    #### Silent drop bad requests ####
    http-request silent-drop if ABUSER
    http-request deny if FORBIDDEN_HDR || FORBIDDEN_URI

    #### Set Request Header ####
    http-request set-header X-Forwarded-Proto https
    http-request set-header X-Proto h2 if { req.ver 2.0 }
    http-request set-header X-Proto h1 unless { req.hdr(X-Proto) -m found }

    ### Misdirected Request ###
    acl allowed_host hdr(Host) -i -M -f /etc/haproxy/etc/acl/host_to_backend.map
    http-request deny deny_status 421 if !allowed_host { hdr(X-Proto) h2 } { hdr_sub(User-Agent) Firefox/ }

    #### Referrer Policy ####
    acl no_referrer_policy res.hdr_cnt(Referrer-Policy) eq 0
    http-response add-header Referrer-Policy unsafe-url if no_referrer_policy


    #### Add custom logging ####
    capture request header Host len 64
    capture request header Referer len 512
    capture request header User-Agent len 512
    capture request header Content-Length len 10
    capture response header Content-Length len 10
    capture response header Content-Type len 32

    #### backend selection ####
    use_backend %[base,map_beg(/etc/haproxy/etc/acl/base_to_backend.map,default)] if { base,map_beg(/etc/haproxy/etc/acl/base_to_backend.map) -m found }
    use_backend %[hdr(Host),map(/etc/haproxy/etc/acl/host_to_backend.map,bk_silentdrop)]
```

## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 2.1.4  2020/04/02 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2021.
Known bugs: http://www.haproxy.org/bugs/bugs-2.1.4.html
Build options :
  TARGET  = linux-glibc
  CPU     = native
  CC      = gcc
  CFLAGS  = -O2 -march=native -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits -DTLS_TICKETS_NO=4
  OPTIONS = USE_PCRE=1 USE_PCRE_JIT=1 USE_REGPARM=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER +PCRE +PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=20).
Built with OpenSSL version : OpenSSL 1.1.1i  8 Dec 2020
Running on OpenSSL version : OpenSSL 1.1.1i  8 Dec 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.5
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.43 2019-02-23
Running on PCRE version : 8.43 2019-02-23
PCRE library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : none

Available filters :
        [SPOE] spoe
        [CACHE] cache
        [FCGI] fcgi-app
        [TRACE] trace
        [COMP] compression
```

## If HAProxy crashed: Last outputs and backtraces

* syslog message
```
syslog : [53711176.092123] haproxy[152912]: segfault at 0 ip 00000000004ac185 sp 00007f1173fd41a0 error 4 in haproxy[400000+235000]
```
* core dump
```
(gdb) info threads
  Id   Target Id         Frame
  18   Thread 0x7f1174ff9700 (LWP 152910) 0x00007f11b5aacd43 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  17   Thread 0x7f1175ffb700 (LWP 152908) 0x00007f11b5aacd43 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  16   Thread 0x7f11767fc700 (LWP 152907) 0x00007f11b5aacd43 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  15   Thread 0x7f11777fe700 (LWP 152905) 0x00007f11b5aacd43 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  14   Thread 0x7f1176ffd700 (LWP 152906) 0x00007f11b5aacd43 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  13   Thread 0x7f117ce75700 (LWP 152903) 0x00007f11b5aacd43 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  12   Thread 0x7f1177fff700 (LWP 152904) 0x00007f11b5aacd43 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  11   Thread 0x7f117fcfc700 (LWP 152901) 0x00007f11b5aacd43 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  10   Thread 0x7f117d676700 (LWP 152902) 0x00007f11b5aacd43 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  9    Thread 0x7f11b78f5140 (LWP 152894) 0x00007f11b5aacd43 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  8    Thread 0x7f11747f8700 (LWP 152911) 0x00007f11b5aacd43 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  7    Thread 0x7f11804fd700 (LWP 152900) 0x00007f11b5aacd43 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  6    Thread 0x7f1171ff3700 (LWP 152916) 0x00007f11b5aacd43 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  5    Thread 0x7f11727f4700 (LWP 152915) 0x0000000000590360 in ?? ()
  4    Thread 0x7f1172ff5700 (LWP 152914) 0x00007f11b5aacd43 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  3    Thread 0x7f11757fa700 (LWP 152909) 0x00007f11b5aacd43 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  2    Thread 0x7f11737f6700 (LWP 152913) 0x00007f11b5aacd43 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
* 1    Thread 0x7f1173ff7700 (LWP 152912) 0x00000000004ac185 in ?? ()
(gdb) thread apply all bt

Thread 18 (Thread 0x7f1174ff9700 (LWP 152910)):
#0  0x00007f11b5aacd43 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
#1  0x000000000042698c in _start ()

Thread 17 (Thread 0x7f1175ffb700 (LWP 152908)):
#0  0x00007f11b5aacd43 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
#1  0x000000000042698c in _start ()

Thread 16 (Thread 0x7f11767fc700 (LWP 152907)):
#0  0x00007f11b5aacd43 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
#1  0x000000000042698c in _start ()

Thread 15 (Thread 0x7f11777fe700 (LWP 152905)):
#0  0x00007f11b5aacd43 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
#1  0x000000000042698c in _start ()

Thread 14 (Thread 0x7f1176ffd700 (LWP 152906)):
#0  0x00007f11b5aacd43 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
#1  0x000000000042698c in _start ()

Thread 13 (Thread 0x7f117ce75700 (LWP 152903)):
#0  0x00007f11b5aacd43 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
#1  0x000000000042698c in _start ()

Thread 12 (Thread 0x7f1177fff700 (LWP 152904)):
#0  0x00007f11b5aacd43 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
#1  0x000000000042698c in _start ()

Thread 11 (Thread 0x7f117fcfc700 (LWP 152901)):
#0  0x00007f11b5aacd43 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
#1  0x000000000042698c in _start ()

Thread 10 (Thread 0x7f117d676700 (LWP 152902)):
#0  0x00007f11b5aacd43 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
#1  0x000000000042698c in _start ()

Thread 9 (Thread 0x7f11b78f5140 (LWP 152894)):
#0  0x00007f11b5aacd43 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
#1  0x000000000042698c in _start ()

Thread 8 (Thread 0x7f11747f8700 (LWP 152911)):
#0  0x00007f11b5aacd43 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
#1  0x000000000042698c in _start ()

Thread 7 (Thread 0x7f11804fd700 (LWP 152900)):
#0  0x00007f11b5aacd43 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
#1  0x000000000042698c in _start ()

Thread 6 (Thread 0x7f1171ff3700 (LWP 152916)):
#0  0x00007f11b5aacd43 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
#1  0x000000000042698c in _start ()

Thread 5 (Thread 0x7f11727f4700 (LWP 152915)):
#0  0x0000000000590360 in ?? ()
#1  0x000000000059afdd in ?? ()
#2  0x000000000058fafc in ?? ()
#3  0x000000000059074f in lua_resume ()
#4  0x00000000004468db in ?? ()
#5  0x000000000044b5ca in ?? ()
#6  0x0000000000518c49 in sample_process ()
#7  0x000000000055d27c in acl_exec_cond ()
#8  0x00000000004951e7 in ?? ()
#9  0x000000000049951b in http_process_req_common ()
#10 0x0000000000471404 in process_stream ()
#11 0x0000000000551a96 in process_runnable_tasks ()
#12 0x0000000000503bff in ?? ()
#13 0x00007f11b6e98dc5 in start_thread (arg=0x7f11727f4700) at pthread_create.c:308
#14 0x00007f11b5aac76d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

Thread 4 (Thread 0x7f1172ff5700 (LWP 152914)):
#0  0x00007f11b5aacd43 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
#1  0x000000000042698c in _start ()

Thread 3 (Thread 0x7f11757fa700 (LWP 152909)):
---Type <return> to continue, or q <return> to quit---
#0  0x00007f11b5aacd43 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
#1  0x000000000042698c in _start ()

Thread 2 (Thread 0x7f11737f6700 (LWP 152913)):
#0  0x00007f11b5aacd43 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
#1  0x000000000042698c in _start ()

Thread 1 (Thread 0x7f1173ff7700 (LWP 152912)):
#0  0x00000000004ac185 in ?? ()
#1  0x00000000004ae6fe in ?? ()
#2  0x0000000000522ee9 in si_cs_recv ()
#3  0x0000000000523750 in si_cs_io_cb ()
#4  0x0000000000551a43 in process_runnable_tasks ()
#5  0x0000000000503bff in ?? ()
#6  0x00007f11b6e98dc5 in start_thread (arg=0x7f1173ff7700) at pthread_create.c:308
#7  0x00007f11b5aac76d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113
```

**Comment by zino7825** [comment]
### core dump ( with symbol )
```
((gdb) info threads
  Id   Target Id         Frame
  18   Thread 0x7f1174ff9700 (LWP 152910) 0x00007f11b5aacd43 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  17   Thread 0x7f1175ffb700 (LWP 152908) 0x00007f11b5aacd43 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  16   Thread 0x7f11767fc700 (LWP 152907) 0x00007f11b5aacd43 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  15   Thread 0x7f11777fe700 (LWP 152905) 0x00007f11b5aacd43 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  14   Thread 0x7f1176ffd700 (LWP 152906) 0x00007f11b5aacd43 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  13   Thread 0x7f117ce75700 (LWP 152903) 0x00007f11b5aacd43 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  12   Thread 0x7f1177fff700 (LWP 152904) 0x00007f11b5aacd43 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  11   Thread 0x7f117fcfc700 (LWP 152901) 0x00007f11b5aacd43 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  10   Thread 0x7f117d676700 (LWP 152902) 0x00007f11b5aacd43 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  9    Thread 0x7f11b78f5140 (LWP 152894) 0x00007f11b5aacd43 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  8    Thread 0x7f11747f8700 (LWP 152911) 0x00007f11b5aacd43 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  7    Thread 0x7f11804fd700 (LWP 152900) 0x00007f11b5aacd43 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  6    Thread 0x7f1171ff3700 (LWP 152916) 0x00007f11b5aacd43 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  5    Thread 0x7f11727f4700 (LWP 152915) 0x0000000000590360 in luaD_precall ()
  4    Thread 0x7f1172ff5700 (LWP 152914) 0x00007f11b5aacd43 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  3    Thread 0x7f11757fa700 (LWP 152909) 0x00007f11b5aacd43 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  2    Thread 0x7f11737f6700 (LWP 152913) 0x00007f11b5aacd43 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
* 1    Thread 0x7f1173ff7700 (LWP 152912) h1_capture_bad_message (h1c=0x7f11433cb2c0, h1m=h1m@entry=0x7f114d29d7f8, buf=buf@entry=0x7f11433cb2d8, h1s=<optimized out>, h1s=<optimized out>) at src/mux_h1.c:1066
(gdb) thread 1
[Switching to thread 1 (Thread 0x7f1173ff7700 (LWP 152912))]
#0  h1_capture_bad_message (h1c=0x7f11433cb2c0, h1m=h1m@entry=0x7f114d29d7f8, buf=buf@entry=0x7f11433cb2d8, h1s=<optimized out>, h1s=<optimized out>) at src/mux_h1.c:1066
1066            struct proxy *other_end = sess->fe;
(gdb) bt full
#0  h1_capture_bad_message (h1c=0x7f11433cb2c0, h1m=h1m@entry=0x7f114d29d7f8, buf=buf@entry=0x7f11433cb2d8, h1s=<optimized out>, h1s=<optimized out>) at src/mux_h1.c:1066
        sess = 0x0
        proxy = 0x2818bf0
        other_end = <optimized out>
        ctx = {http = {sid = 3, state = 0, b_flags = 5602376, s_flags = 0, t_flags = 2016, m_flags = 0, m_clen = 139712285759344, m_blen = 139712136198640}, h1 = {state = 3, c_flags = 0, s_flags = 5602376, m_flags = 0, m_clen = 2016,
            m_blen = 139712285759344}}
```
```c
(gdb) list
1061    static void h1_capture_bad_message(struct h1c *h1c, struct h1s *h1s,
1062                                       struct h1m *h1m, struct buffer *buf)
1063    {
1064            struct session *sess = h1c->conn->owner;
1065            struct proxy *proxy = h1c->px;
1066            struct proxy *other_end = sess->fe;
1067            union error_snapshot_ctx ctx;
1068
1069            if (h1s->cs->data && !(h1m->flags & H1_MF_RESP))
1070                    other_end = si_strm(h1s->cs->data)->be;
```
```
(gdb) f 0
#0  h1_capture_bad_message (h1c=0x7f11433cb2c0, h1m=h1m@entry=0x7f114d29d7f8, buf=buf@entry=0x7f11433cb2d8, h1s=<optimized out>, h1s=<optimized out>) at src/mux_h1.c:1066
1066            struct proxy *other_end = sess->fe;
(gdb) print  h1c->conn->owner
$18 = (void *) 0x0
(gdb) p sess->fe
Cannot access memory at address 0x0
```

**Comment by zino7825** [comment]
I found below
http://git.haproxy.org/?p=haproxy-2.1.git;a=commitdiff;h=259b94cebda755276f1becc25d6142ec5a58ad84

is it bug fix ?
```c

-- a/src/mux_h1.c
+++ b/src/mux_h1.c
@@ -1087,7 +1087,7 @@ static void h1_show_error_snapshot(struct buffer *out, const struct error_snapsh
 static void h1_capture_bad_message(struct h1c *h1c, struct h1s *h1s,
                                   struct h1m *h1m, struct buffer *buf)
 {
-       struct session *sess = h1c->conn->owner;
+       struct session *sess = h1s->sess;
        struct proxy *proxy = h1c->px;
        struct proxy *other_end = sess->fe;
        union error_snapshot_ctx ctx;
```

**Comment by wlallemand** [comment]
That's probably the bugfix to your problem, yes.

Please update your haproxy version to the latest 2.1 version as it contains 276 know bugs that were fix since your version: https://www.haproxy.org/bugs/bugs-2.1.4.html

**Comment by wtarreau** [comment]
And by the way when you update, please take this opportunity to switch to 2.2 which is a longterm supported branch, while 2.1 is reaching end of life in a few weeks at best.

**Comment by zino7825** [comment]
@wlallemand I didn't know "bugs site", thanks for sharing.

@wtarreau I will, actually we are preparing to upgrade 2.2.6

**Comment by wtarreau** [comment]
Please take 2.2.10, not 2.2.6 which for which 98 bugs are already known according to the bugs site.

**Comment by capflam** [comment]
I guess db2c17da6 fixed the issue. I'm closing it now.

**Comment by zino7825** [comment]
@capflam 
The issue was not reproduced after the patch(db2c17da60e80091615ddbe8d97cb964d1f00ac7)  was applied.

**Comment by capflam** [comment]
Thanks for the confirmation.
