### ISSUE TITLE
Segmentation fault when running conf check on misspelt tcp-check

### ISSUE THREAD

**Issue by ziegenberg** [haproxy/haproxy#1290]
## Detailed description of the problem

HAProxy crashes with SIG_SEGV when checking crafted configuration file.

## Expected behavior

HAProxy should verify the configuration without crashing and display an appropriate message.

## Steps to reproduce the behavior

1. create a crafted config file `haproxy.cfg` (see below)
2. run `haproxy -f haproxy.cfg -c`

## Do you have any idea what may have caused this?

In the config the `tcp-check expect` is misspelt.

## Do you have an idea how to solve the issue?

No.

## What is your configuration?

Minimal config:

```
backend http-in
    mode tcp
    option tcp-check
    tcp-check connect
    tcp-check send PING
    tcp-check xpect string +PONG
```

## Output of `haproxy -vv` and `uname -a`

<details>
  <summary>haproxy -vv</summary>

```
$ haproxy -vv
HA-Proxy version 2.2.2 2020/07/31 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.2.html
Running on: Linux 4.18.0-240.22.1.el8_3.x86_64 #1 SMP Thu Apr 8 19:01:30 UTC 2021 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_LINUX_TPROXY=1 USE_CRYPT_H=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.1c FIPS  28 May 2019
Running on OpenSSL version : OpenSSL 1.1.1g FIPS  21 Apr 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.4
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : no (USE_PCRE2_JIT not set)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.3.1 20191121 (Red Hat 8.3.1-5)
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services :
	prometheus-exporter

Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace
	[CACHE] cache
	[FCGI] fcgi-app

```
</details>

<details>
  <summary>uname -a</summary>

```
$ uname -a
Linux moodle-web-01.xxx.xxx.xxx.xxx.at 4.18.0-240.22.1.el8_3.x86_64 #1 SMP Thu Apr 8 19:01:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
</details>

## If HAProxy crashed: Last outputs and backtraces

<details>
  <summary>journalctl</summary>

```
Jun 14 20:54:12 moodle-web-01.xxx.xxx.xxx.xxx.at kernel: haproxy[511120]: segfault at 8 ip 0000563d8d890ff9 sp 00007ffe1ed770b0 error 6 in haproxy[563d8d767000+270000]
Jun 14 20:54:12 moodle-web-01.xxx.xxx.xxx.xxx.at kernel: Code: bd 0b 00 48 8b 7d 38 e8 25 96 f1 ff 48 8b 7d 00 48 8b 07 48 39 fd 74 2d 66 0f 1f 84 00 00 00 00 00 48 8b 57 08 48 89 c3 31 f6 <48> 89 50 08 48 8b 57 08 48 89 02 e8 a7 fa ff ff 48 89 df 48 8b 03
Jun 14 20:54:12 moodle-web-01.xxx.xxx.xxx.xxx.at systemd[1]: Started Process Core Dump (PID 511121/UID 0).
-- Subject: Unit systemd-coredump@10-511121-0.service has finished start-up
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit systemd-coredump@10-511121-0.service has finished starting up.
-- 
-- The start-up result is done.
Jun 14 20:54:13 moodle-web-01.xxx.xxx.xxx.xxx.at systemd-coredump[511122]: Process 511120 (haproxy) of user 1101 dumped core.
                                                                             
                                                                             Stack trace of thread 511120:
                                                                             #0  0x0000563d8d890ff9 free_tcpcheck_ruleset (haproxy)
                                                                             #1  0x0000563d8d89b241 free_tcpcheck_ruleset (haproxy)
                                                                             #2  0x0000563d8d83e329 cfg_parse_listen (haproxy)
                                                                             #3  0x0000563d8d82a7da readcfgfile (haproxy)
                                                                             #4  0x0000563d8d8dd3be init (haproxy)
                                                                             #5  0x0000563d8d7aba97 main (haproxy)
                                                                             #6  0x00007f1c3b8827b3 __libc_start_main (libc.so.6)
                                                                             #7  0x0000563d8d7ad7be _start (haproxy)
-- Subject: Process 511120 (haproxy) dumped core
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- Documentation: man:core(5)
-- 
-- Process 511120 (haproxy) crashed and dumped core.
-- 
-- This usually indicates a programming error in the crashing program and
-- should be reported to its vendor as a bug.
Jun 14 20:54:13 moodle-web-01.xxx.xxx.xxx.xxx.at systemd[1]: systemd-coredump@10-511121-0.service: Succeeded.
-- Subject: Unit succeeded
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- The unit systemd-coredump@10-511121-0.service has successfully entered the 'dead' state.
```
</details>

<details>
  <summary>(gdb) t a a bt full</summary>

```
(gdb) t a a bt full

Thread 1 (Thread 0x7ffff7fe0340 (LWP 511138)):
#0  0x000055555567dff9 in free_tcpcheck_ruleset (rs=0x555555b61670) at src/tcpcheck.c:336
        __ret = 0x555555b32280
        r = 0x555555b32280
        rb = 0x0
#1  0x0000555555688241 in free_tcpcheck_ruleset (rs=0x555555b61670) at src/tcpcheck.c:3776
        r = <optimized out>
        rb = <optimized out>
        r = <optimized out>
        rb = <optimized out>
        __ret = <optimized out>
#2  proxy_parse_tcpcheck (args=<optimized out>, section=<optimized out>, curpx=<optimized out>, defpx=<optimized out>, file=<optimized out>, line=<optimized out>, errmsg=0x7fffffffd088) at src/tcpcheck.c:3776
        rs = 0x555555b61670
        chk = <optimized out>
        index = <optimized out>
        cur_arg = 1
        ret = <optimized out>
#3  0x000055555562b329 in cfg_parse_listen (file=0x555555b5e180 "ha.cfg", linenum=9, args=0x7fffffffd140, kwm=<optimized out>) at src/cfgparse-listen.c:3150
        kwl = <optimized out>
        index = <optimized out>
        curproxy = 0x555555b5fdd0
        err = <optimized out>
        rc = 0
        val = 0
        err_code = 0
        cond = 0x0
        tmplogsrv = <optimized out>
        errmsg = 0x555555b618d0 "'tcp-check' only supports 'comment', 'connect', 'send', 'send-binary', 'expect', 'set-var(*)', 'unset-var(*)'. but got 'xpect'"
        bind_conf = <optimized out>
#4  0x00005555556177da in readcfgfile (file=0x555555b5e180 "ha.cfg") at src/cfgparse.c:2076
        status = <optimized out>
        kwm = <optimized out>
        end = <optimized out>
        line = <optimized out>
        arg = 4
        args = {0x555555b5f9c0 "tcp-check", 0x555555b5f9ca "xpect", 0x555555b5f9d0 "string", 0x555555b5f9d7 "+PONG", 0x555555b5f9dc "" <repeats 61 times>}
        thisline = <optimized out>
        linesize = 2048
        f = 0x555555b132f0
        linenum = 9
        err_code = 0
        cs = 0x555555b329e0
        pcs = 0x0
        ics = 0x5555559d1410 <sections>
        readbytes = 0
        outline = 0x555555b5f9c0 "tcp-check"
        outlen = 29
        outlinesize = 1024
        fatal = 0
        missing_lf = -1
#5  0x00005555556ca3be in init (argc=<optimized out>, argv=<optimized out>) at src/haproxy.c:2032
        ret = <optimized out>
        trash = 0x7ffff7fd82e0
        arg_mode = <optimized out>
        tmp = <optimized out>
        cfg_pidfile = <optimized out>
        err_code = 0
        err_msg = 0x0
        wl = 0x555555b5e160
        progname = 0x7fffffffdc4f "haproxy"
        change_dir = <optimized out>
        px = <optimized out>
        pcf = <optimized out>
        ideal_maxconn = <optimized out>
#6  0x0000555555598a97 in main (argc=4, argv=0x7fffffffd938) at src/haproxy.c:3140
        err = <optimized out>
        retry = <optimized out>
        limit = {rlim_cur = 1024, rlim_max = 262144}
        errmsg = "\030\000\000\000\000\000\000\000\002\000\000\000\000\000\000\000p\327\377\377\377\177\000\000\265\246YUUU\000\000\320T\377\377\377\377\377\377@!\263UUU\000\000\003", '\000' <repeats 50 times>
        pidfd = -1
```
</details>

## Additional information (if helpful)

Does not happen with `HA-Proxy version 2.3.10-4764f0e 2021/04/23`

**Comment by TimWolla** [comment]
> HA-Proxy version 2.2.2 2020/07/31 - https://haproxy.org/

This version is almost one year old and affected by 317 bugs: https://www.haproxy.org/bugs/bugs-2.2.2.html.

> Does not happen with `HA-Proxy version 2.3.10-4764f0e 2021/04/23`

This indicates that the bug already is fixed and indeed I'm unable to reproduce on the current HEAD of the 2.2 branch (2.2.14 + additional fixes):

```
$ ./haproxy -c -f ./crasher.cfg
[NOTICE] 164/210330 (22066) : haproxy version is 2.2.14-9aba44-43
[NOTICE] 164/210330 (22066) : path to executable is ./haproxy
[ALERT] 164/210330 (22066) : parsing [./crasher.cfg:6] : 'tcp-check' only supports 'comment', 'connect', 'send', 'send-binary', 'expect', 'set-var(*)', 'unset-var(*)'. but got 'xpect'
[ALERT] 164/210330 (22066) : Error(s) found in configuration file : ./crasher.cfg
[ALERT] 164/210330 (22066) : Fatal errors found in configuration.
```
