### ISSUE TITLE
Program terminated with signal SIGSEGV, Segmentation fault. #0  0x00007f4b97be2f9a in ?? ()

### ISSUE THREAD

**Issue by hkd2020** [haproxy/haproxy#1686]
### Detailed Description of the Problem

We have HAP that runs on RHEL version 8 and it started to crash intermittently on high load with segmentation fault. We have several HAPs running with different config but only one HAP that handles load crashes.

### Expected Behavior

HAP shouldn't crash with segmentation fault

### Steps to Reproduce the Behavior

Run HAP with routing based on soapAction to several backends
Observe HAP crash randomly

### What is your configuration?

```haproxy
global
        log 127.0.0.1 format rfc5424 local1
        log-send-hostname
        pidfile ****/pid/haproxy.pid
        maxconn 8000
        debug
        stats socket ****/stats mode 777
        tune.chksize 32768
        ca-base /***/***
resolvers dns
        nameserver dns1 1*****
        nameserver dns2 1*****
        resolve_retries 3
        timeout retry 1s
        hold valid 10s
listen stats
        mode http
        bind *:4140
        stats admin if TRUE
        stats enable
        stats uri /
        stats realm Haproxy\ Statistics
        stats auth *****
        timeout connect 5000
        timeout client 50000
        timeout server 50000
defaults
        mode http
        log global
        option httplog
        option dontlognull
        option http-server-close
        retries 3
        timeout connect 10s
        timeout client 1m
        timeout server 1m
        maxconn 60000
        balance roundrobin
listen http_frontend
        mode http
        option http-buffer-request

        declare capture response len 200000

        declare capture request len 400000000
        http-request capture req.body id 0
```

### Output of `haproxy -vv`

```plain
HA-Proxy version 1.8.19 2019/02/11
Copyright 2000-2019 Willy Tarreau <willy@haproxy.org>

Build options :
  TARGET  = linux2628
  CPU     = generic
  CC      = gcc
  CFLAGS  = -m64 -march=x86-64 -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label
  OPTIONS = USE_OPENSSL=1 USE_STATIC_PCRE=1

Default settings :
  maxconn = 2000, bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with OpenSSL version : OpenSSL 1.0.2r  26 Feb 2019
Running on OpenSSL version : OpenSSL 1.0.2r  26 Feb 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Encrypted password support via crypt(3): yes
Built with multi-threading support.
Built with PCRE version : 8.32 2012-11-30
Running on PCRE version : 8.32 2012-11-30
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Built without compression support (neither USE_ZLIB nor USE_SLZ are set).
Compression algorithms supported : identity("identity")
Built with network namespace support.

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available filters :
        [SPOE] spoe
        [COMP] compression
        [TRACE] trace
```

### Last Outputs and Backtraces

```plain
May  4 07:35:12 ****** kernel: haproxy[2776912]: segfault at 7ca5000 ip 00007f4b97be2f9a sp 00007ffc60c18ad8 error 4 in libc-2.28.so[7f4b97b3f000+1bc000]

Core Dump:
GNU gdb (GDB) Red Hat Enterprise Linux 8.2-16.el8
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
BFD: warning: /tmp/core.haproxy.70618.cf90b57a42194d5b807e1dfa66827785.2776912.1651674912000000 is truncated: expected core file size >= 28097708032, found: 2147483648
BFD: warning: /tmp/core.haproxy.70618.cf90b57a42194d5b807e1dfa66827785.2776912.1651674912000000 is truncated: expected core file size >= 28097708032, found: 2147483648
[New LWP 2776912]
Missing separate debuginfo for the main executable file
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/61/f2ca8cc3c76a82303dd5823491dd3abd8d82e6
Failed to read a valid object file image from memory.
Core was generated by `/var/prod/proxy-shared/HAPS/hapbinary/haproxy -D -f /var/prod/proxy-shared/HAPS'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f4b97be2f9a in ?? ()
```

### Additional Information

uname -a
Linux ppollchrh00001 4.18.0-348.7.1.el8_5.x86_64 #1 SMP Wed Dec 8 21:51:17 EST 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by git001** [comment]
Well looks like you use the HAProxy package from the Red Hat Repos as the latest 1.8 version is 1.8.30 https://www.haproxy.org/

Have you tried to open a ticket on Red Hat's customer portal?
Have you the latest Red Hat kernel on the machine?

If you want to use a more recent version of HAProxy can you search in the RH Repos for HAProxy 2.2 and maybe 2.4.  
You can also build your own rpm based on this git repo https://github.com/DBezemer/rpm-haproxy

**Comment by hkd2020** [comment]
Thank you for quick response.
Yes, our SA team opened case with Red Hat.  We do patch every 6 months and it was patched last march and now with 4.18.0-348.7.1.el8_5.x86_64 kernel version
Prior kernel version before patch - 4.18.0-305.3.1.el8_0.x86_64

**Comment by git001** [comment]
Okay perfect, so this issue can be closed as you have opened a ticket to Red Hat?

One more small suggestion, please install the debug packages after "yum --enablerepo='*debug*'" so that the "bt" (Backtrace) can show where the  SIGSEGV was raised, this will also help the Red Hat team to see if any bugfix should be backported

**Comment by chipitsine** [comment]
in your case haproxy is built with no compression support `Built without compression support (neither USE_ZLIB nor USE_SLZ are set).`

if that is on purpose, I would suggest to perform general audit. if there are significant amount of  text/html or application/json responses, you may benefit from compressing.

(but it might be no option if you are bound to that particular rpm which is built that way)

**Comment by capflam** [comment]
any news about this issue ?

**Comment by capflam** [comment]
I'm closing because of inactivity.
