### ISSUE TITLE
HAProxy 2.6.0 Crashes With Code 139 Segmentation Fault On Start

### ISSUE THREAD

**Issue by canth1** [haproxy/haproxy#1744]
### Detailed Description of the Problem

I just compiled the latest version of HAProxy (2.6.0) and I'm upgrading from 2.5.5, but now HAProxy crashes upon start:

```
/usr/sbin/haproxy -Ws -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid
[NOTICE]   (1543690) : New worker (1543692) forked
[NOTICE]   (1543690) : Loading success.
[WARNING]  (1543692) : Server XXX/XXX is DOWN, reason: Layer4 connection problem, info: "Connection refused at initial connection step of tcp-check", check duration: 3ms. 9 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
[WARNING]  (1543692) : Server XXX/XXX is DOWN, reason: Layer4 connection problem, info: "Connection refused at initial connection step of tcp-check", check duration: 3ms. 8 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
[WARNING]  (1543692) : Backup Server XXX/XXX is DOWN, reason: Layer7 wrong status, code: 429, info: "Too Many Requests", check duration: 22ms. 5 active and 4 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
[WARNING]  (1543692) : Server XXX/XXX is DOWN, reason: Layer7 wrong status, code: 429, info: "Too Many Requests", check duration: 25ms. 4 active and 4 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
[NOTICE]   (1543690) : haproxy version is 2.6.0-a1efc04
[NOTICE]   (1543690) : path to executable is /usr/sbin/haproxy
[ALERT]    (1543690) : Current worker (1543692) exited with code 139 (Segmentation fault)
[ALERT]    (1543690) : exit-on-failure: killing every processes with SIGTERM
[WARNING]  (1543690) : All workers exited. Exiting... (139)
```

### Expected Behavior

Start correctly as 2.5.5 does

### Steps to Reproduce the Behavior

Launch HAProxy 2.6.0

### What is your configuration?

```haproxy
global
        master-worker
        busy-polling
        description XXX
        group haproxy
        log 127.0.0.1 local0
        node XXX
        maxconn 20000
        spread-checks 3
        stats socket /var/run/haproxy.socket mode 600 level admin
        stats timeout 5m
        strict-limits
        tune.bufsize 32768
        tune.comp.maxlevel 9
        tune.ssl.default-dh-param 2048
        user haproxy

defaults
        balance source
        compression algo gzip
        compression type application/javascript application/json application/x-javascript application/xml text/css text/csv text/html text/javascript text/plain text/xml
        default-server init-addr libc,none # Never fail on address resolution
        http-reuse never
        mode http
        option abortonclose
        option allbackups
        option contstats
        option forwardfor
        option http-keep-alive
        option httpchk
        option httplog
        option prefer-last-server
        option redispatch
        stats enable
        stats refresh 30s
        stats show-desc XXX
        stats show-legends
        stats show-node XXX
        stats uri /haproxy_stats
        timeout client 180s
        timeout connect 15s
        timeout http-keep-alive 30s
        timeout http-request 30s
        timeout server 180s
        unique-id-format %{+X}o\ %ci:%cp_%fi:%fp_%Ts_%rt:%pid
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.6.0-a1efc04 2022/05/31 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2027.
Known bugs: http://www.haproxy.org/bugs/bugs-2.6.0.html
Running on: Linux 5.13.0-39-generic #44~20.04.1-Ubuntu SMP Thu Mar 24 16:43:35 UTC 2022 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_PCRE_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_SYSTEMD=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE +PCRE_JIT -PCRE2 -PCRE2_JIT +POLL +THREAD +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -ENGINE +GETADDRINFO +OPENSSL +LUA +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC -PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=1).
Built with OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
Running on OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Support for malloc_trim() is enabled.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.39 2016-06-14
Running on PCRE version : 8.39 2016-06-14
PCRE library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 9.4.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : none

Available filters :
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
        [TRACE] trace
```

### Last Outputs and Backtraces

```plain
Reading symbols from /usr/sbin/haproxy...
[New LWP 1542499]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/sbin/haproxy -Ws -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid -S /run/h'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000558c99f4f652 in sock_conn_iocb (fd=<optimized out>) at src/sock.c:869
869     src/sock.c: No such file or directory.
(gdb) thread apply all bt full

Thread 1 (Thread 0x7f847dc8af80 (LWP 1542499)):
#0  0x0000558c99f4f652 in sock_conn_iocb (fd=<optimized out>) at src/sock.c:869
        conn = 0x558c9ac91410
        flags = 0
        need_wake = 0
#1  0x0000558c99f578c4 in fd_update_events (fd=fd@entry=27, evts=<optimized out>) at src/fd.c:542
        locked = <optimized out>
        old = <optimized out>
        new = <optimized out>
        new_flags = <optimized out>
        must_stop = 0
        rmask = <optimized out>
        tmask = <optimized out>
#2  0x0000558c99db01eb in _do_poll (p=<optimized out>, exp=<optimized out>, wake=<optimized out>) at src/ev_epoll.c:241
        ev = {events = 0, data = {ptr = 0x400000000, fd = 0, u32 = 0, u64 = 17179869184}}
        n = <optimized out>
        e = <optimized out>
        ret = <optimized out>
        status = <optimized out>
        fd = 27
        count = <optimized out>
        updt_idx = <optimized out>
        wait_time = <optimized out>
        old_fd = <optimized out>
#3  0x0000558c99ef6c84 in run_poll_loop () at src/haproxy.c:2845
        next = <optimized out>
        wake = <optimized out>
#4  0x0000558c99ef7149 in run_thread_poll_loop (data=<optimized out>) at src/haproxy.c:2963
        ptaf = <optimized out>
        ptif = <optimized out>
        ptdf = <optimized out>
        ptff = <optimized out>
        init_left = 0
        init_mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}
        init_cond = {__data = {{__wseq = 0, __wseq32 = {__low = 0, __high = 0}}, {__g1_start = 0, __g1_start32 = {__low = 0, __high = 0}}, __g_refs = {0, 0}, __g_size = {0, 0}, __g1_orig_size = 0, __wrefs = 0, __g_signals = {0, 0}}, __size = '\000' <repeats 47 times>, __align = 0}
#5  0x0000558c99dacf6e in main (argc=<optimized out>, argv=<optimized out>) at src/haproxy.c:3587
        err = <optimized out>
        retry = <optimized out>
        limit = {rlim_cur = 40324, rlim_max = 1048576}
        pidfd = <optimized out>
        intovf = <optimized out>
```

**Comment by akomelj** [comment]
Same here.

HAproxy 2.6.0 - official alpine Docker image. Starts successfully and segfaults immediately when a backend server changes status to DOWN.

2.5.x works without a problem.

```
Linux gw 5.4.188 #0 SMP Sat Apr 16 12:59:34 2022 x86_64 GNU/Linux

Mon Jun 13 09:30:40 2022 daemon.err start.sh[2244]: [WARNING]  (8) : Server nagios/nas-nagios is DOWN, reason: Layer4 connection problem, info: "Connection refused", check duration: 0ms. 2 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
Mon Jun 13 09:30:40 2022 kern.info kernel: [222944.513781] haproxy[2456]: segfault at 28 ip 00005555d9a3ead2 sp 00007f0d394a3180 error 4 in haproxy[5555d98a0000+1cd000]
Mon Jun 13 09:30:40 2022 kern.info kernel: [222944.525466] Code: 31 e4 8b 50 30 89 d1 83 e1 03 83 f9 03 0f 85 52 ff ff ff 0f 1f 44 00 00 48 8b 4d 40 48 85 c9 74 57 f6 41 08 01 74 51 48 8b 39 <8b> 77 28 8b 07 a8 40 75 10 89 c2 83 ca 40 f0 0f b1 17 75 f1 e8 b5
Mon Jun 13 09:30:40 2022 daemon.err start.sh[2244]: [NOTICE]   (1) : haproxy version is 2.6.0-a1efc04
Mon Jun 13 09:30:40 2022 daemon.err start.sh[2244]: [ALERT]    (1) : Current worker (8) exited with code 139 (Segmentation fault)
Mon Jun 13 09:30:40 2022 daemon.err start.sh[2244]: [ALERT]    (1) : exit-on-failure: killing every processes with SIGTERM
Mon Jun 13 09:30:40 2022 daemon.err start.sh[2244]: [WARNING]  (1) : All workers exited. Exiting... (139)
```

**Comment by capflam** [comment]
@akomelj, your issue is similar to #1734. Do you use email alerts ?

**Comment by capflam** [comment]
@canth1, same question. your trace seems to be different but I prefer to ask. In addition, could you share your frontends/backends configuration ?

**Comment by akomelj** [comment]
> @akomelj, your issue is similar to #1734. Do you use email alerts ?

Hi, my apologies - you are correct, it is in fact #1734. I disabled notifications and the problem went away.

**Comment by canth1** [comment]
I also use notifications, so I'm sure this is also my issue. I'll verify by testing if https://github.com/haproxy/haproxy/commit/58e35019108a69d5ac9d68d07732a92499783376 fixes my issue.

**Comment by capflam** [comment]
Copy that !

**Comment by canth1** [comment]
This was indeed fixed with https://github.com/haproxy/haproxy/commit/58e35019108a69d5ac9d68d07732a92499783376
