### ISSUE TITLE
Segmentation fault on parse_alpn [musl/alpine]

### ISSUE THREAD

**Issue by fabianonunes** [haproxy/haproxy#1804]
### Detailed Description of the Problem

HAProxy segfaults when parsing a valid config file on Alpine-based Docker images. Oddly, the error depends on the file name.

Can't reproduce on Debian-based images.

### Expected Behavior

HAProxy parses a valid file and doesn't segfault.

### Steps to Reproduce the Behavior

1. Use any Alpine-based image newer or equal to 1.9.0 (must support `default-server alpn` option).
2. Run haproxy to check the following file:

    <details>
    <summary>haproxy.cfg</summary>
    
    ```text
    global
      log stdout format raw local0 notice

    defaults
      timeout connect 5s
      timeout client  5s
      timeout server  5s
      default-server  alpn h2,http/1.1

    frontend http
      mode http
      bind 0.0.0.0:80
      default_backend default

    backend app-a
      default-server ssl alpn h2,http/1.1 verify none
      server srv_1 192.168.0.1:443

    backend app-b
      default-server ssl alpn h2,http/1.1 verify none
      server srv_1 192.168.0.2:443

    backend default
      mode http
      server srv_1 192.168.0.3:80
    ```
    </details>

3. I can't explain why, but if you use the same file with a different name, the verification will pass:
    ```text
    /app # ls -l *cfg
    -rw-r--r--    3 haproxy  haproxy        475 Jul 25 20:37 abcdefghijklmnopqrstuvw.cfg
    -rw-r--r--    3 haproxy  haproxy        475 Jul 25 20:37 haproxy.cfg
    -rw-r--r--    3 haproxy  haproxy        475 Jul 25 20:37 usr-local-etc-haproxy-haproxy.cfg
    ```
    ```text
    /app # sha1sum *cfg
    0332e888fe2c66a8625345295036253f0adc0db9  abcdefghijklmnopqrstuvw.cfg
    0332e888fe2c66a8625345295036253f0adc0db9  haproxy.cfg
    0332e888fe2c66a8625345295036253f0adc0db9  usr-local-etc-haproxy-haproxy.cfg
    ```
    ```text
    /app # haproxy -c -f abcdefghijklmnopqrstuvw.cfg
    Configuration file is valid

    /app # haproxy -c -f haproxy.cfg
    Segmentation fault (core dumped)

    /app # haproxy -c -f usr-local-etc-haproxy-haproxy.cfg
    Segmentation fault (core dumped)
    ```

### What is your configuration?

```haproxy
global
  log stdout format raw local0 notice

defaults
  timeout connect 5s
  timeout client  5s
  timeout server  5s
  default-server  alpn h2,http/1.1

frontend http
  mode http
  bind 0.0.0.0:80
  default_backend default

backend app-a
  default-server ssl alpn h2,http/1.1 verify none
  server srv_1 192.168.0.1:443

backend app-b
  default-server ssl alpn h2,http/1.1 verify none
  server srv_1 192.168.0.2:443

backend default
  mode http
  server srv_1 192.168.0.3:80
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.6.0-a1efc04 2022/05/31 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2027.
Known bugs: http://www.haproxy.org/bugs/bugs-2.6.0.html
Running on: Linux 5.15.0-41-generic #44-Ubuntu SMP Wed Jun 22 14:20:53 UTC 2022 x86_64
Build options :
  TARGET  = linux-musl
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_PROMEX=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL +THREAD -BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -ENGINE +GETADDRINFO +OPENSSL +LUA +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=24).
Built with OpenSSL version : OpenSSL 1.1.1o  3 May 2022
Running on OpenSSL version : OpenSSL 1.1.1o  3 May 2022
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.6
Built with the Prometheus exporter as a service
Built with network namespace support.
Support for malloc_trim() is enabled.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.39 2021-10-29
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 11.2.1 20220219

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
```

### Last Outputs and Backtraces

```plain
#0  a_crash () at ./arch/x86_64/atomic_arch.h:108
#1  get_meta (p=p@entry=0x7effd60485b0 "\002h2\bhttp/1.1") at src/malloc/mallocng/meta.h:141
#2  0x00007effd65b7c2e in __libc_free (p=0x7effd60485b0) at src/malloc/mallocng/free.c:105
#3  0x00007effd65b73c2 in free (p=<optimized out>) at src/malloc/free.c:5
#4  0x000055a222e825eb in parse_alpn (err=0x7fff63e05670, out_alpn_len=0x7effd6014c50,
    out_alpn_str=0x7effd6014c48, alpn=0x7effd6043b48 "h2,http/1.1") at src/cfgparse-ssl.c:1377
#5  srv_parse_alpn (args=0x7fff63e059f0, cur_arg=0x7fff63e056e0, px=<optimized out>,
    newsrv=0x7effd6014150, err=0x7fff63e05670) at src/cfgparse-ssl.c:1386
#6  0x000055a222f198ca in _srv_parse_kw (srv=0x7effd6014150, args=args@entry=0x7fff63e059f0,
    cur_arg=cur_arg@entry=0x7fff63e056e0, curproxy=curproxy@entry=0x7effd6014020,
    parse_flags=parse_flags@entry=1) at src/server.c:2788
#7  0x000055a222f1cf94 in parse_server (file=file@entry=0x7effd61ac870 "haproxy.cfg",
    linenum=linenum@entry=20, args=args@entry=0x7fff63e059f0, curproxy=0x7effd6014020,
    defproxy=0x7fff63e056e0, parse_flags=parse_flags@entry=1) at src/server.c:2911
#8  0x000055a222f8d3fe in cfg_parse_listen (file=0x7effd61ac870 "haproxy.cfg", linenum=20,
    args=0x7fff63e059f0, kwm=0) at src/cfgparse-listen.c:445
#9  0x000055a222f55a6e in readcfgfile (file=0x7effd61ac870 "haproxy.cfg") at src/cfgparse.c:2180
#10 0x000055a222e5cf54 in init (argc=<optimized out>, argv=0x7fff63e05f98) at src/haproxy.c:2013
#11 main (argc=<optimized out>, argv=0x7fff63e05f98) at src/haproxy.c:3084
```

**Comment by capflam** [comment]
I'm able to reproduce the error. I'm on the fix.

**Comment by capflam** [comment]
It should be fixed in DEV now. thanks !
