### ISSUE TITLE
http-request set-header with empty value causes segfault during config check

### ISSUE THREAD

**Issue by idl0r** [haproxy/haproxy#1850]
### Detailed Description of the Problem

Jus something minor this time:
A http-request set-header with empty value causes segfault during a config check
Affects at least 2.6.2, 2.6.4 as well as current master/2.7

### Expected Behavior

Only the error should be printed, no segfault

### Steps to Reproduce the Behavior

1. Two line config:
```
frontend foobar
http-request set-header foo
```
2. haproxy -f config -c
3. crash

### What is your configuration?

```haproxy
frontend foobar
http-request set-header foo
# or
http-request set-header foo ""
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.7-dev4 2022/08/20 - https://haproxy.org/
Status: development branch - not safe for use in production.
Known bugs: https://github.com/haproxy/haproxy/issues?q=is:issue+is:open
Running on: Linux 5.19.2-gentoo #1 SMP PREEMPT_DYNAMIC Thu Aug 18 09:01:02 CEST 2022 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -O0 -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment -DMAX_SESS_STKCTR=12
  OPTIONS = USE_PCRE= USE_PCRE_JIT= USE_PCRE2=1 USE_PCRE2_JIT= USE_LIBCRYPT=1 USE_OPENSSL=1 USE_LUA= USE_ZLIB= USE_SLZ=1 USE_NS= USE_SYSTEMD= USE_PROMEX=
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 -PCRE2_JIT +POLL +THREAD -PTHREAD_EMULATION +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -ENGINE +GETADDRINFO +OPENSSL -LUA +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO -NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC -PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=16).
Built with OpenSSL version : OpenSSL 1.1.1q  5 Jul 2022
Running on OpenSSL version : OpenSSL 1.1.1q  5 Jul 2022
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Support for malloc_trim() is enabled.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.40 2022-04-14
PCRE2 library supports JIT : no (USE_PCRE2_JIT not set)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 11.3.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=

Available services : none

Available filters :
	[BWLIM] bwlim-in
	[BWLIM] bwlim-out
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
```

### Last Outputs and Backtraces

```plain
(gdb) run -f haproxy.cfg-crash -c
Starting program: /home/idl0r/haproxy/haproxy -f haproxy.cfg-crash -c
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7ffff7807640 (LWP 4515)]
[Thread 0x7ffff7807640 (LWP 4515) exited]
[NOTICE]   (4511) : haproxy version is 2.7-dev4
[NOTICE]   (4511) : path to executable is /home/idl0r/haproxy/haproxy
[ALERT]    (4511) : config : parsing [haproxy.cfg-crash:2] : error detected in frontend 'foobar' while parsing 'http-request set-header' rule : expects exactly 2 arguments.

Thread 1 "haproxy" received signal SIGSEGV, Segmentation fault.
0x0000555555787fd9 in release_http_action (rule=0x555555bde1d0) at src/http_act.c:54
54		list_for_each_entry_safe(lf, lfb, &rule->arg.http.fmt, list) {
(gdb) t a a bt full

Thread 1 (Thread 0x7ffff7e0b800 (LWP 4511) "haproxy"):
#0  0x0000555555787fd9 in release_http_action (rule=0x555555bde1d0) at src/http_act.c:54
        lf = 0x0
        lfb = 0x555555bd3c8d
#1  0x0000555555847eb6 in free_act_rule (rule=0x555555bde1d0) at src/action.c:311
No locals.
#2  0x000055555582723c in parse_http_req_cond (args=0x7fffffffcaf8, file=0x555555bdd900 "haproxy.cfg-crash", linenum=2, proxy=0x555555c322c0) at src/http_rules.c:166
        rule = 0x555555bde1d0
        custom = 0x55555594bfa0 <http_req_actions+656>
        cur_arg = 1
#3  0x000055555575103d in cfg_parse_listen (file=0x555555bdd900 "haproxy.cfg-crash", linenum=2, args=0x7fffffffcaf0, kwm=0) at src/cfgparse-listen.c:1229
        rule = 0x0
        where = 0
        curproxy = 0x555555c322c0
        curr_defproxy = 0x555555c307b0
        last_defproxy = 0x555555c307b0
        err = 0x0
        rc = 0
        err_code = 0
        cond = 0x0
        errmsg = 0x0
        bind_conf = 0x0
#4  0x00005555556ec2c1 in readcfgfile (file=0x555555bdd900 "haproxy.cfg-crash") at src/cfgparse.c:2183
        status = 0
        kwm = 0
        end = 0x555555bdd95f ""
        line = 0x555555bdd940 "http-request set-header foo \"\""
        arg = 4
        args = {0x555555bd3c80 "http-request", 0x555555bd3c8d "set-header", 0x555555bd3c98 "foo", 0x555555bd3c9c "" <repeats 62 times>}
        thisline = 0x555555bdd940 "http-request set-header foo \"\""
        linesize = 2048
        f = 0x555555bdd220
        linenum = 2
        err_code = 0
        cs = 0x555555bdc2a0
        pcs = 0x0
        ics = 0x555555948d30 <sections>
        readbytes = 0
        outline = 0x555555bd3c80 "http-request"
        outlen = 29
        outlinesize = 1024
        fatal = 0
        missing_lf = -1
        nested_cond_lvl = 0
        nested_conds = {NESTED_COND_IF_TAKE, NESTED_COND_IF_TAKE, NESTED_COND_IF_TAKE, NESTED_COND_IF_TAKE, NESTED_COND_IF_TAKE, NESTED_COND_IF_TAKE, NESTED_COND_IF_TAKE, NESTED_COND_IF_TAKE, 526339951, 926891871, 2071952703, 2139061119, 2139062135, 2136964991, 2134867839, 2138996607, NESTED_COND_IF_TAKE, NESTED_COND_IF_TAKE, NESTED_COND_IF_TAKE, NESTED_COND_IF_TAKE, NESTED_COND_IF_TAKE, NESTED_COND_IF_TAKE, 4294953504, 32767, 1438505265, 21845, 493726720, 2638253951, 1438505248, 21845, 4294953744, 32767, 1438505248, 21845, 17, NESTED_COND_IF_TAKE, 4294953504, 32767, 1435172357, 21845, 4294953952, 32767, 4152904168, 32767, 779169393, 1600348016, 1700752239, NESTED_COND_IF_TAKE, 4222451713, NESTED_COND_IF_TAKE, 1438505248, 21845, 1438505248, 21845, 1438505248, 21845, 1438505248, 21845, 1438505265, 21845, 1438505265, 21845, 1438505248, 21845, 1438505265, 21845, NESTED_COND_IF_TAKE <repeats 11 times>, 128, 4154419968, 32767, NESTED_COND_IF_TAKE, NESTED_COND_IF_SKIP, NESTED_COND_IF_TAKE, NESTED_COND_IF_TAKE, 18, NESTED_COND_IF_TAKE, NESTED_COND_IF_TAKE, NESTED_COND_IF_TAKE, 4294967295, 4294967295, NESTED_COND_IF_TAKE, NESTED_COND_IF_TAKE, NESTED_COND_IF_TAKE, NESTED_COND_IF_TAKE, NESTED_COND_IF_TAKE, NESTED_COND_IF_TAKE, 4294967295, 119, 110, 91}
        non_global_section_parsed = 0
        errmsg = 0x0
#5  0x0000555555773127 in init (argc=4, argv=0x7fffffffd2a8) at src/haproxy.c:2011
        ret = -4380
        env_cfgfiles = 0x555555bdd920 "haproxy.cfg-crash"
        env_err = 0
        progname = 0x555555bdd880 "haproxy"
        err_code = 0
        wl = 0x555555bdd8e0
        px = 0x7fffffffee79
        pcf = 0x7fffffffeeb0
        prcf = 0x7fffffffeec3
        ideal_maxconn = 32767
#6  0x0000555555776514 in main (argc=4, argv=0x7fffffffd2a8) at src/haproxy.c:3112
        err = 0
--Type <RET> for more, q to quit, c to continue without paging--c
        retry = -12145
        limit = {rlim_cur = 1024, rlim_max = 8000000}
        pidfd = -1
        intovf = 5
(gdb) p rule
$1 = (struct act_rule *) 0x555555bde1d0
(gdb) p rule->arg
$2 = {resolv = {expr = 0x0, varname = 0x0, resolvers_id = 0x0, resolvers = 0x0, opts = 0x0}, http = {i = 0, str = {ptr = 0x0, len = 0}, fmt = {n = 0x0, p = 0x0}, re = 0x0}, http_reply = 0x0, redir = 0x0, map = {ref = 0x0, key = {n = 0x0, p = 0x0}, 
    value = {n = 0x0, p = 0x0}}, expr = 0x0, cap = {expr = 0x0, hdr = 0x0}, capid = {expr = 0x0, idx = 0}, timeout = {value = 0, type = ACT_TIMEOUT_SERVER, expr = 0x0}, hlua_rule = 0x0, vars = {fmt = {n = 0x0, p = 0x0}, expr = 0x0, name_hash = 0, 
    scope = SCOPE_SESS, conditions = 0}, gpc = {sc = 0, idx = 0}, gpt = {sc = 0, idx = 0, value = 0, expr = 0x0}, trk_ctr = {expr = 0x0, table = {t = 0x0, n = 0x0}}, act = {p = {0x0, 0x0, 0x0, 0x0}}}
(gdb) p rule->arg.http
$3 = {i = 0, str = {ptr = 0x0, len = 0}, fmt = {n = 0x0, p = 0x0}, re = 0x0}
```

**Comment by wtarreau** [comment]
Amusing, thanks for reporting, Christian! I'm checking what causes this, in case I can fix it before releasing 2.6.5, many thanks for the report and for the trivial repro!

**Comment by wtarreau** [comment]
It's yet another free-on-error issue introduced by this commit between 2.5 and 2.6:

   dd7e6c6dc ("BUG/MINOR: http-rules: completely free incorrect TCP rules on error")

I'm checking.

**Comment by wtarreau** [comment]
OK now fixed and backported. I'm closing it. Thanks again Christian!
