### ISSUE TITLE
Early connection close from backend closes frontend connection

### ISSUE THREAD

**Issue by Makpoc** [haproxy/haproxy#188]
## Output of `haproxy -vv` and `uname -a`

```
# haproxy -vv
HA-Proxy version 2.0.3 2019/07/23 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-format-truncation -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=8).
Built with OpenSSL version : OpenSSL 1.1.1c  28 May 2019
Running on OpenSSL version : OpenSSL 1.1.1c  28 May 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services :
	prometheus-exporter

Available filters :
	[SPOE] spoe
	[COMP] compression
	[CACHE] cache
	[TRACE] trace

# uname -a
Linux makpoc 5.2.1-arch1-1-ARCH #1 SMP PREEMPT Sun Jul 14 14:52:52 UTC 2019 x86_64 GNU/Linux
```

The same behavior is reproducible with 1.9 and 2.0 docker images.

## What's the configuration?

```
global
  log /dev/log local0 debug

  ulimit-n 400000
  maxconn 200000

  stats socket /var/run/haproxy.sock mode 660 level admin
  stats timeout 30s

#  user nobody
#  group nobody

  daemon

  nbthread 4

  # Default SSL material locations
  ca-base /etc/ssl/certs
  crt-base /etc/ssl/private

  # Default ciphers to use on SSL-enabled listening sockets.
  # For more information, see ciphers(1SSL).
  ssl-default-bind-ciphers kEECDH+aRSA+AES:kRSA+AES:+AES256:RC4-SHA:!kEDH:!LOW:!EXP:!MD5:!aNULL:!eNULL


defaults
  log global

  maxconn 200000

  timeout connect 5s
  timeout client 15m
  timeout server 1h

  retries 3

  log-format {"timestamp":%Ts,"actconn":%ac,"backend_concurrent_conn":%bc,"backend_name":"%b","backend_queue":%bq,"backend_source_ip":"%bi","backend_source_port":%bp,"bytes_read":%B,"bytes_uploaded":%U,"client_ip":"%ci","client_port":%cp,"frontend_concurrent_conn":%fc,"frontend_ip":"%fi","frontend_name":"%f","frontend_name_transport":"%ft","frontend_port":%fp,"hostname":"%H","pid":%pid,"request_counter":%rt,"retries":%rc,"server_ip":"%si","server_name":"%s","server_port":%sp,"session_duration":%Tt,"srv_conn":%sc,"srv_queue":%sq,"status_code":%ST,"t_connect":%Tc,"t_wait":%Tw,"termination_state":"%ts"}

listen stats
  bind :8000

  mode http

  log 127.0.0.1:515 daemon

  stats enable
  stats hide-version
  stats uri /

  unique-id-format %{+X}o\ %ci:%cp_%fi:%fp_%Ts_%rt:%pid
  unique-id-header X-Unique-ID

  log-format {"timestamp":"%Ts","actconn":"%ac","backend_concurrent_conn":"%bc","backend_name":"%b","backend_queue":"%bq","backend_source_ip":"%bi","backend_source_port":"%bp","bytes_read":"%B","bytes_uploaded":"%U","client_ip":"%ci","client_port":"%cp","frontend_concurrent_conn":"%fc","frontend_ip":"%fi","frontend_name":"%f","frontend_name_transport":"%ft","frontend_port":"%fp","hostname":"%H","pid":"%pid","request_counter":"%rt","retries":"%rc","server_ip":"%si","server_name":"%s","server_port":"%sp","session_duration":"%Tt","srv_conn":"%sc","srv_queue":"%sq","status_code":"%ST","t_connect":"%Tc","t_wait":"%Tw","termination_state":"%ts","unique_id":"%ID","t_query":"%Tq","t_reponse":"%Tr","http_request":"%r","termination_state_cookie_status":"%ts"}

listen be-service
  log global
  bind :8080

  retries 3

  mode http
  balance hdr(X-Tenant-ID)

  option forwardfor header X-Real-IP
  option redispatch
  option http-keep-alive
  option log-health-checks
  option httplog

  unique-id-format %{+X}o\ %ci:%cp_%fi:%fp_%Ts_%rt:%pid
  unique-id-header X-Unique-ID

  log-format {"timestamp":"%Ts","actconn":"%ac","backend_concurrent_conn":"%bc","backend_name":"%b","backend_queue":"%bq","backend_source_ip":"%bi","backend_source_port":"%bp","bytes_read":"%B","bytes_uploaded":"%U","client_ip":"%ci","client_port":"%cp","frontend_concurrent_conn":"%fc","frontend_ip":"%fi","frontend_name":"%f","frontend_name_transport":"%ft","frontend_port":"%fp","hostname":"%H","pid":"%pid","request_counter":"%rt","retries":"%rc","server_ip":"%si","server_name":"%s","server_port":"%sp","session_duration":"%Tt","srv_conn":"%sc","srv_queue":"%sq","status_code":"%ST","t_connect":"%Tc","t_wait":"%Tw","termination_state":"%ts","unique_id":"%ID","t_query":"%Tq","t_reponse":"%Tr","termination_state_cookie_status":"%ts","http_request":"%r"}
  option httpchk GET / HTTP/1.0\r\nUser-Agent:\ HAProxy


  stick-table type string len 16 size 100M expire 20m
  stick on hdr(X-Tenant-ID)

  retry-on all-retryable-errors
  server be-local 172.17.0.1:2690 check inter 50s rise 2 fall 6 maxconn 10000 weight 100
  server be-local-1 172.17.0.1:2690 check inter 50s rise 2 fall 6 maxconn 10000 weight 100
```

## Steps to reproduce the behavior

1. Make a PUT/POST request with relatively big body (in the example - 4 MB is enough)
2. Have a backend server close the connection and return a response early, while the client is still sending the request body.
3. Try to reuse the client connection for another request after the first one is done.

A minimal reproducible example can be found here https://github.com/Makpoc/haproxy-connreset.

Instead of the go client you could also use curl against the same server:

```
 # curl -kv \
 -X PUT \
 -H "Expect:" \
 --data-binary @/a-4MBish-pic.jpeg \
 "http://127.0.0.1:8080/" \
 --next \
 -X PATCH -d '{"complete": true}' \
 -H "Content-type: application/json" \
 --retry-max-time 0 \
 --retry 0 \
 "http://127.0.0.1:8080/"
*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> PUT / HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.65.1
> Accept: */*
> Content-Length: 4194304
> Content-Type: application/x-www-form-urlencoded
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 204 No Content
< date: Thu, 25 Jul 2019 14:58:36 GMT
< 
* We are completely uploaded and fine
* Connection #0 to host 127.0.0.1 left intact
* Found bundle for host 127.0.0.1: 0x560ba84f6180 [serially]


# Trying to reuse the connection:


* Re-using existing connection! (#0) with host 127.0.0.1
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> PATCH / HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.65.1
> Accept: */*
> Content-type: application/json
> Content-Length: 18
> 
* upload completely sent off: 18 out of 18 bytes


# But it's dead ;(.
# Curl retries and all is good


* Connection died, retrying a fresh connect
* Closing connection 0

* Issue another request to this URL: 'http://127.0.0.1:8080/'
* Hostname 127.0.0.1 was found in DNS cache
*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#1)
> PATCH / HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.65.1
> Accept: */*
> Content-type: application/json
> Content-Length: 18
> 
* upload completely sent off: 18 out of 18 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< date: Thu, 25 Jul 2019 14:58:37 GMT
< content-length: 0
< 
* Connection #1 to host 127.0.0.1 left intact

```
## Actual behavior

The second request fails to go through to the backend server. HAProxy closes the connection

From the example repo:
```
Sending request
Got response: 204 No Content
Response headers:
Date: [Thu, 25 Jul 2019 14:47:58 GMT]

Sending request
panic: Patch http://localhost:8080/: EOF

goroutine 1 [running]:
main.performRequest(0x8d28e0, 0xc00016e000)
	/home/makpoc/git/go/src/github.com/Makpoc/haproxy-connreset/client/main.go:44 +0x1b3
main.main()
	/home/makpoc/git/go/src/github.com/Makpoc/haproxy-connreset/client/main.go:37 +0x2f3
exit status 2
```

## Expected behavior

It would be great if HAProxy can create a new connection and send the second request to the backend service.

## Do you have any idea what may have caused this?

Check out the traffic capture here: https://github.com/Makpoc/haproxy-connreset/tree/master/files

## Do you have an idea how to solve the issue?

**Comment by wtarreau** [comment]
The problem here is that the server completely closes and does not just shutdown. Thus it creates the classical TCP RST issue by which the data it has sent may be removed from its own buffers or the TCP stack on haproxy's side. In some cases haproxy could be able to properly read the response as happens in your example since some time is elapsed between the response and the actual close, but in some cases those data will be destroyed in flight before haproxy can even read them.

I see what you'd like to have, basically haproxy could possibly try to drain the data from the client if a response was given and the other side is dead.  While I'm not fundamentally opposed to this, I'd be extremely cautious because this means blocking error propagation between the two sides and reopening a new can of worms with the occasional lot of close_wait and consorts. And as I explained above it will not always solve everything with such a server. Typically too small request bodies may be destroyed by this server (those with enough packets in flight but not too many so that the RST happens immediately after the response).

I'm turning this into a feature request so that we don't lose it and it continues to fuel the thoughts around error propagation but I'm not promising much more.

**Comment by Makpoc** [comment]
This sounds reasonable.

Something I've discovered while preparing the sample project is that if we set "Transfer-Encoding: chunked" for the initial PUT request the RST does not happen and the subsequent PATCH request reaches the backend. I haven't had time enough yet to review how it looks like in a caption but I can provide one soon enough if needed.

**Comment by wtarreau** [comment]
This could be useful indeed. It may be a slightly different behaviour of the server when emitting chunks, which would try harder to stay synchronized with the stream.

**Comment by Makpoc** [comment]
I've added the capture from a Transfer-Encoding: chunked PUT request: https://github.com/Makpoc/haproxy-connreset/tree/master/files

**Comment by anvpetrov** [comment]
we have same issue  with haproxy ingress and chunked response from java application
