### ISSUE TITLE
segfault on config file parsing with http-error hdr argument missing value

### ISSUE THREAD

**Issue by Tristan971** [haproxy/haproxy#1925]
### Detailed Description of the Problem

HAProxy crashes with a SIGSEGV while parsing the configuration file

### Expected Behavior

No crash

### Steps to Reproduce the Behavior

1. /usr/bin/env haproxy -dW -c -V -f /etc/haproxy/haproxy.cfg

### Do you have any idea what may have caused this?

The following causes the crash:
```haproxy
http-error status 200 content-type "text/html; charset=utf-8" lf-file "/etc/haproxy/static/mangadex/errorfiles/200.html" hdr Cache-Control "no-store" hdr
```

Specifically the stray `hdr` at the end. Removing it fixes this.

The coredump points to the following call used to release aborted parsing http rule references on error

https://github.com/haproxy/haproxy/blob/4639689d89db2d18c4afbbe68e688a2b26b14b57/src/http_htx.c#L1034-L1039

Though I'm unsure if the line is mangled because it's a macro of if it's really in the macro that the issue resides (looks like the former tho)

Note that in my config there are 13 of those in a row (for all the possible errorfiles status codes, basically), but it does crash on the first one (as per the backtrace)

Looks like 

### What is your configuration?

It is a bit cursed and hard to redact, and the issue seems potentially clear-cut, but I can share it privately if my assumption is wrong.

### Output of `haproxy -vv`

```plain
HAProxy version 2.7-dev8-aa529f7+mangadex-5277602 2022-11-04T13:58+00:00 - https://haproxy.org/
Status: development branch - not safe for use in production.
Known bugs: https://github.com/haproxy/haproxy/issues?q=is:issue+is:open
Running on: Linux 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -ggdb3 -gdwarf-4 -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wnull-dereference -fwrapv -Wno-unknown-warning-option -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment -DMAX_SESS_STKCTR=5
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_STATIC_PCRE2=1 USE_LIBCRYPT=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_TFO=1 USE_NS=1 USE_SYSTEMD=1 USE_QUIC=1 USE_PROMEX=1
  DEBUG   = -DDEBUG_MEMORY_POOLS -DDEBUG_STRICT

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL +THREAD -PTHREAD_EMULATION +BACKTRACE -STATIC_PCRE +STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -ENGINE +GETADDRINFO +OPENSSL +LUA +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT +QUIC +PROMEX -MEMORY_PROFILING +SHM_OPEN

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=8).
Built with OpenSSL version : OpenSSL 1.1.1s+quic-mangadex-5277602  4 Nov 2022
Running on OpenSSL version : OpenSSL 1.1.1s+quic-mangadex-5277602  4 Nov 2022
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.6
Built with the Prometheus exporter as a service
Built with network namespace support.
Support for malloc_trim() is enabled.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.40 2022-04-14
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with clang compiler version 14.0.6

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
       quic : mode=HTTP  side=FE     mux=QUIC  flags=HTX|NO_UPG|FRAMED
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=

Available services : prometheus-exporter
Available filters :
        [BWLIM] bwlim-in
        [BWLIM] bwlim-out
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
        [TRACE] trace
```

### Last Outputs and Backtraces

Crashes without producing any output.

```plain
Core was generated by `/usr/sbin/haproxy -Ws -f /etc/haproxy/haproxy.cfg -c -q -S /run/haproxy-master.'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00005ad3931fb770 in release_http_reply (http_reply=http_reply@entry=0x5ad394f00960) at src/http_htx.c:1034
1034    src/http_htx.c: No such file or directory.
(gdb) t a a bt full

Thread 1 (Thread 0x7306972f2180 (LWP 37587)):
#0  0x00005ad3931fb770 in release_http_reply (http_reply=http_reply@entry=0x5ad394f00960) at src/http_htx.c:1034
        hdr = 0x5ad394f00950
        lf = 0x0
        lfb = <optimized out>
        hdrb = <optimized out>
#1  0x00005ad3931fc958 in http_parse_http_reply (args=args@entry=0x7ffd57c7a130, orig_arg=orig_arg@entry=0x7ffd57c79fa4, px=px@entry=0x5ad394eebcf0, default_status=default_status@entry=0, errmsg=errmsg@entry=0x7ffd57c7a018) at src/http_htx.c:1726
        stat = {
          st_dev = 2050,
          st_ino = 791266,
          st_nlink = 1,
          st_mode = 33188,
          st_uid = 0,
          st_gid = 0,
          __pad0 = 0,
          st_rdev = 0,
          st_size = 9874,
          st_blksize = 4096,
          st_blocks = 24,
          st_atim = {
            tv_sec = 1668281046,
            tv_nsec = 3940841
          },
          st_mtim = {
            tv_sec = 1667718765,
            tv_nsec = 542242527
          },
          st_ctim = {
            tv_sec = 1667718765,
            tv_nsec = 480218934
          },
          __glibc_reserved = {0, 0, 0}
        }
        reply = 0x5ad394f00960
        act_arg = <optimized out>
        obj = <optimized out>
        cap = <optimized out>
        objlen = <optimized out>
        fd = <optimized out>
        cur_arg = <optimized out>
        hdr = <optimized out>
        lf = <optimized out>
        lfb = <optimized out>
        hdrb = <optimized out>
#2  0x00005ad3931fe4bb in proxy_parse_http_error (args=0x7ffd57c7a130, section=<optimized out>, curpx=0x5ad394eebcf0, defpx=<optimized out>, file=0x5ad394df0c30 "/etc/haproxy/haproxy.cfg", line=202, errmsg=0x7ffd57c7a018) at src/http_htx.c:2091
        reply = 0x0
        ret = 0
        cur_arg = 1
        rc = <optimized out>
        conf_err = <optimized out>
#3  0x00005ad3932059e9 in cfg_parse_listen (file=0x5ad394f009f0 "", linenum=1472699568, args=0x7ffd57c7a130, kwm=<optimized out>) at src/cfgparse-listen.c:3157
        kwl = 0x5ad3936c8a68 <cfg_kws>
        index = <optimized out>
        best = <optimized out>
        curproxy = 0x5ad394eebcf0
        curr_defproxy = 0x5ad394ecae60
        last_defproxy = 0x5ad394edf580
        err_code = <optimized out>
        cond = 0x0
        errmsg = 0x5ad394f00a80 "'hdr' expects <name> and <value> as arguments"
        rc = <optimized out>
        err = <optimized out>
        bind_conf = <optimized out>
#4  0x00005ad3931c76ef in readcfgfile (file=0x7 <error: Cannot access memory at address 0x7>) at src/cfgparse.c:2488
        status = <optimized out>
        kwm = <optimized out>
        line = <optimized out>
        end = <optimized out>
        args = {0x5ad394eacf40 "http-error", 0x5ad394eacf4b "status", 0x5ad394eacf52 "200", 0x5ad394eacf56 "content-type", 0x5ad394eacf63 "text/html; charset=utf-8", 0x5ad394eacf7c "lf-file", 0x5ad394eacf84 "/etc/haproxy/static/mangadex/errorfiles/200.html", 0x5ad394eacfb5 "hdr",
 0x5ad394eacfb9 "Cache-Control", 0x5ad394eacfc7 "no-store", 0x5ad394eacfd0 "hdr", 0x5ad394eacfd3 "" <repeats 54 times>}
        arg = <optimized out>
        nested_conds = {NESTED_COND_IF_TAKE, NESTED_COND_IF_TAKE, 124, 119, 110, 91, NESTED_COND_IF_TAKE, NESTED_COND_IF_TAKE, 2498243432, 23251, 4294825320, 4294967295, 25, NESTED_COND_IF_TAKE, 2541333632, 29446, 25, NESTED_COND_IF_TAKE, 3585979392, 1384785183, 1472701488, 32765, 2498410224, 23251, 25, NESTED_COND_IF_TAKE, 2471863763, 23251, 25, NESTED_COND_IF_TAKE, 24, NESTED_COND_IF_TAKE, 1472701488, 32765, 2468057045, 23251, NESTED_COND_IF_TAKE, NESTED_COND_IF_TAKE, 1472701720, 32765, 40, 48, 1472701712, 32765, 1472701520, 32765, 2497645584, 23251, NESTED_COND_IF_TAKE, NESTED_COND_IF_TAKE, 2471832923, 23251, 2471655465, 23251, NESTED_COND_IF_DROP, NESTED_COND_IF_TAKE, 2473367536, 23251, 2468034307, 23251, 16, 48, 1472701712, 32765, 1472701520, 32765, NESTED_COND_IF_TAKE, NESTED_COND_IF_TAKE, NESTED_COND_IF_TAKE, NESTED_COND_IF_TAKE, NESTED_COND_IF_TAKE, NESTED_COND_IF_TAKE, 2471655465, 23251, 2471655465, 23251, 2497645616, 23251, 2498406080, 23251, NESTED_COND_IF_TAKE <repeats 16 times>, 2471517969, 23251, 2539412532, 29446}
        thisline = 0x5ad394eab720 "    http-error status 200 content-type \"text/html; charset=utf-8\" lf-file \"/etc/haproxy/static/mangadex/errorfiles/200.html\" hdr Cache-Control \"no-store\" hdr"
        linesize = 2048
        f = 0x5ad394df08c0
        linenum = 202
        err_code = 0
        cs = 0x4
        pcs = 0x0
        readbytes = 0
        outline = 0x5ad394eacf40 "http-error"
        outlen = 148
        outlinesize = 1024
        fatal = 0
        missing_lf = -1
        nested_cond_lvl = 0
        non_global_section_parsed = <optimized out>
        errmsg = 0x0
        ics = 0x5ad3936c6c90 <sections>
#5  0x00005ad393211e4c in init (argv=0x7ffd57c7a918, argc=<optimized out>) at src/haproxy.c:2032
        ret = <optimized out>
        env_cfgfiles = <optimized out>
        env_err = 0
        progname = <optimized out>
        err_code = 0
        wl = <optimized out>
        prcf = <optimized out>
        px = <optimized out>
        pcf = <optimized out>
        ideal_maxconn = <optimized out>
        args = <optimized out>
        errmsg = <optimized out>
        arg = <optimized out>
        outlen = <optimized out>
        errptr = <optimized out>
        err = <optimized out>
        w = <optimized out>
        result = <optimized out>
        env_cfgfiles = <optimized out>
        env_err = <optimized out>
        ret = <optimized out>
        tmproc = <optimized out>
        c = <optimized out>
        it = <optimized out>
        path = <optimized out>
        __ret = <optimized out>
        __x = <optimized out>
        pscf = <optimized out>
        srv = <optimized out>
        ppcf = <optimized out>
        pr = <optimized out>
        px = <optimized out>
        p = <optimized out>
        sides = <optimized out>
        mem = <optimized out>
        sslmem = <optimized out>
        sides = <optimized out>
        mem = <optimized out>
        retried = <optimized out>
        clearmem = <optimized out>
        sides = <optimized out>
        mem = <optimized out>
        retried = <optimized out>
        s = <optimized out>
#6  main (argc=<optimized out>, argv=0x7ffd57c7a918) at src/haproxy.c:3162
        limit = {
          rlim_cur = 1024,
          rlim_max = 524288
        }
        pidfd = -1
        retry = <optimized out>
        err = <optimized out>
        intovf = <optimized out>
```

### Additional Information

<details>
<summary>half-relevant q about http-error and errorfile</summary>

Confused as to what explains the difference between http-error and errorfile?
- the former supports lf-file(s) but can't be used to define an http-errors set
- the latter doesn't support lf-file(s), but I do need the unique request id in there ;_;

</details>

**Comment by capflam** [comment]
Thanks ! Indeed, there is a bug. I'm able to reproduce it and it is trivial to fix. I'll do it soon.

**Comment by capflam** [comment]
Now fixed. Thanks !
