### ISSUE TITLE
AB/BA locking issue in process_srv_queue() vs pendconn_grab_from_px()

### ISSUE THREAD

**Issue by wtarreau** [haproxy/haproxy#197]
This was reported by @max2k1 in continuation of issue https://github.com/haproxy/haproxy/issues/181

Looks like it still not fixed. Haproxy=2.0.3:

backtrace:

```
Core was generated by `/usr/sbin/haproxy -Ws -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fd665728428 in raise () from /lib/x86_64-linux-gnu/libc.so.6
[Current thread is 1 (Thread 0x7fd66701f180 (LWP 29741))]
(gdb) t a a bt

Thread 4 (Thread 0x7fd662526700 (LWP 29745)):
#0  0x0000564c376805c6 in process_srv_queue (s=0x564c3ab726e0) at src/queue.c:316
#1  0x0000564c375afe2a in stream_free (s=0x7fd65c542670) at src/stream.c:382
#2  process_stream (t=<optimized out>, context=0x7fd65c542670, state=<optimized out>) at src/stream.c:2739
#3  0x0000564c37684169 in process_runnable_tasks () at src/task.c:412
#4  0x0000564c375ed7a8 in run_poll_loop () at src/haproxy.c:2516
#5  run_thread_poll_loop (data=<optimized out>) at src/haproxy.c:2637
#6  0x00007fd66682a6ba in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#7  0x00007fd6657fa41d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 3 (Thread 0x7fd663528700 (LWP 29743)):
#0  0x0000564c37680ca7 in pendconn_grab_from_px (s=s@entry=0x564c3ab726e0) at src/queue.c:446
#1  0x0000564c375e233e in server_warmup (t=0x564c3cc81d20, context=0x564c3ab726e0, state=<optimized out>) at src/checks.c:1505
#2  0x0000564c376844c5 in process_runnable_tasks () at src/task.c:414
#3  0x0000564c375ed7a8 in run_poll_loop () at src/haproxy.c:2516
#4  run_thread_poll_loop (data=<optimized out>) at src/haproxy.c:2637
#5  0x00007fd66682a6ba in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007fd6657fa41d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 2 (Thread 0x7fd662d27700 (LWP 29744)):
#0  0x0000564c376809df in pendconn_queue_lock (p=<optimized out>, p=<optimized out>) at src/queue.c:157
#1  pendconn_add (strm=strm@entry=0x7fd654194dc0) at src/queue.c:369
#2  0x0000564c3763dd38 in assign_server_and_queue (s=s@entry=0x7fd654194dc0) at src/backend.c:1037
#3  0x0000564c37640f28 in assign_server_and_queue (s=0x7fd654194dc0) at include/proto/backend.h:104
#4  srv_redispatch_connect (s=s@entry=0x7fd654194dc0) at src/backend.c:1700
#5  0x0000564c375abad5 in sess_prepare_conn_req (s=0x7fd654194dc0) at src/stream.c:1237
#6  process_stream (t=<optimized out>, context=0x7fd654194dc0, state=<optimized out>) at src/stream.c:2400
#7  0x0000564c37684169 in process_runnable_tasks () at src/task.c:412
#8  0x0000564c375ed7a8 in run_poll_loop () at src/haproxy.c:2516
#9  run_thread_poll_loop (data=<optimized out>) at src/haproxy.c:2637
#10 0x00007fd66682a6ba in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#11 0x00007fd6657fa41d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 1 (Thread 0x7fd66701f180 (LWP 29741)):
#0  0x00007fd665728428 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007fd66572a02a in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x0000564c376a764e in ha_panic () at src/debug.c:164
#3  0x0000564c376a78c8 in wdt_handler (sig=14, si=<optimized out>, arg=<optimized out>) at src/wdt.c:123
#4  <signal handler called>
#5  0x0000564c37680a5a in pendconn_queue_lock (p=<optimized out>, p=<optimized out>) at src/queue.c:157
#6  pendconn_add (strm=strm@entry=0x564c3d1259e0) at src/queue.c:369
#7  0x0000564c3763dd38 in assign_server_and_queue (s=s@entry=0x564c3d1259e0) at src/backend.c:1037
#8  0x0000564c37640f28 in assign_server_and_queue (s=0x564c3d1259e0) at include/proto/backend.h:104
#9  srv_redispatch_connect (s=s@entry=0x564c3d1259e0) at src/backend.c:1700
#10 0x0000564c375abad5 in sess_prepare_conn_req (s=0x564c3d1259e0) at src/stream.c:1237
#11 process_stream (t=<optimized out>, context=0x564c3d1259e0, state=<optimized out>) at src/stream.c:2400
#12 0x0000564c37684169 in process_runnable_tasks () at src/task.c:412
#13 0x0000564c375ed7a8 in run_poll_loop () at src/haproxy.c:2516
#14 run_thread_poll_loop (data=<optimized out>) at src/haproxy.c:2637
#15 0x0000564c3754aa27 in main (argc=<optimized out>, argv=0x7ffe193247a8) at src/haproxy.c:3314
```

```
haproxy -vv
HA-Proxy version 2.0.3-1 2019/07/24 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_REGPARM=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_TFO=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=56).
Built with OpenSSL version : OpenSSL 1.0.2g  1 Mar 2016
Running on OpenSSL version : OpenSSL 1.0.2g  1 Mar 2016
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2
Built with Lua version : Lua 5.3.1
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.8
Running on zlib version : 1.2.8
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE2 version : 10.21 2016-01-12
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services :
	prometheus-exporter

Available filters :
	[SPOE] spoe
	[COMP] compression
	[CACHE] cache
	[TRACE] trace
```

As can be seen, process_srv_queue() takes the proxy lock then the server's lock. pendconn_grab_from_px takes the px lock and expects to be called with the server lock held. Other functions like cli_parse_enable_dyncookie_backend() take the proxy's lock then the server's lock. And srv_update_status() must be called with the server's lock held exclusively, and NOT the proxy lock (nor can it take it) because this one propagates along the track chain and will randomly visit multiple proxies, sometimes multiple times the same.

So for now we have an inconsistency between the proxy's lock and the server's lock. Both may be taken in any order and that must not be possible.

At this point it still looks like it would be "easier" to change the lock ordering so that the proxy's lock is always taken under the server's lock or alone, but that we never take the server's lock under the proxy's lock. The dyncookie functions seem to be adaptable to do this. process_srv_queue() is trivial to change for this. It's unclear whether other places present the same problem.

**Comment by wtarreau** [comment]
This was fixed in all affected branches. Closing now.
