### ISSUE TITLE
Haproxy 1.9.2 crashes when agent-check is used

### ISSUE THREAD

**Issue by serimin** [haproxy/haproxy#20]
## Output of `haproxy -vv` and `uname -a`

```
# haproxy -vv
HA-Proxy version 1.9.2 2019/01/17 - https://haproxy.org/
Build options :
  TARGET  = linux2628
  CPU     = native
  CC      = gcc
  CFLAGS  = -O2 -march=native -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits -DTLS_TICKETS_NO=4
  OPTIONS = USE_ZLIB=1 USE_REGPARM=1 USE_OPENSSL=1 USE_LUA=1 USE_PCRE=1 USE_PCRE_JIT=1

Default settings :
  maxconn = 2000, bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with OpenSSL version : OpenSSL 1.1.1a-v1  21 Nov 2018
Running on OpenSSL version : OpenSSL 1.1.1a-v1  21 Nov 2018
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.4
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE version : 8.41 2017-07-05
Running on PCRE version : 8.41 2017-07-05
PCRE library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with multi-threading support.

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE
              h2 : mode=HTTP       side=FE
       <default> : mode=HTX        side=FE|BE
       <default> : mode=TCP|HTTP   side=FE|BE

Available filters :
	[SPOE] spoe
	[COMP] compression
	[CACHE] cache
	[TRACE] trace

# uname -a
Linux test1 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

## What's the configuration?

```
backend bk_rr
    balance roundrobin
    option http-server-close

    server test1 10.1.1.1:80 check agent-check
    server test2 10.1.1.2:80 check agent-check

```

## Steps to reproduce the behavior

1. As soon as haproxy started, it crashes.
2. if removing agent-check, it starts normally.

```
(gdb) bt full
#0  0x00000000004b5e84 in process_chk_conn (state=<optimized out>, context=0x2073fb0, t=0x21b8830) at src/checks.c:2165
        cs = 0x0
        conn = <optimized out>
        rv = <optimized out>
        check = 0x2073fb0
        proxy = 0x0
#1  process_chk (t=0x21b8830, context=0x2073fb0, state=<optimized out>) at src/checks.c:2327
        check = 0x2073fb0
#2  0x000000000053a77a in process_runnable_tasks () at src/task.c:435
        t = 0x21b8830
        state = <optimized out>
        ctx = <optimized out>
        process = <optimized out>
        t = <optimized out>
        max_processed = 200
#3  0x00000000004bc81d in run_poll_loop () at src/haproxy.c:2619
        next = <optimized out>
        exp = <optimized out>
#4  run_thread_poll_loop (data=data@entry=0x1fbdb60) at src/haproxy.c:2684
        ptif = 0x7f0050 <per_thread_init_list>
        ptdf = <optimized out>
        start_lock = 0
#5  0x000000000041e94b in main (argc=<optimized out>, argv=0x7ffdeea928e8) at src/haproxy.c:3313
        tids = 0x1fbdb60
        threads = 0x1f98b80
        i = <optimized out>
        old_sig = {__val = {0, 0, 0, 0, 0, 0, 0, 140029491259232, 24, 32962176, 335544638, 140029507024752, 33038688, 140029487866124, 0, 0}}
        blocked_sig = {__val = {18446744067199990583, 18446744073709551615 <repeats 15 times>}}
        err = <optimized out>
        retry = <optimized out>
        limit = {rlim_cur = 1500228, rlim_max = 1500228}
        errmsg = '\000' <repeats 96 times>, "\002\000\000"
        pidfd = <optimized out>
```

**Comment by wtarreau** [comment]
On Sun, Jan 20, 2019 at 07:12:41PM -0800, serimin wrote:
> 1. As soon as haproxy started, it crashes.
> 2. if removing agent-check, it starts normally.

This sounds like a byproduct of the recent check fixes to work around
mailer issues :-(  I'll take a look at it today. Thanks for the report!

**Comment by wtarreau** [comment]
OK now fixed. Please apply this patch to your tree, it will fix it : https://github.com/haproxy/haproxy/commit/1ba32032ef93ed14fc2eb25003b05b7087c835ac

Thanks!

**Comment by wtarreau** [comment]
Clicked the wrong button. Still needs to be backported to 1.9.

**Comment by serimin** [comment]
It works great!!

Thanks!!

**Comment by wtarreau** [comment]
Thanks for confirming. Now backported to 1.9.
