### ISSUE TITLE
2.8-dev3: SPOE filter(bwlim) segfault

### ISSUE THREAD

**Issue by idl0r** [haproxy/haproxy#2042]
### Detailed Description of the Problem

It seems to be bwlim related

### Expected Behavior

No crash

### Steps to Reproduce the Behavior

N/A

### What is your configuration?

```haproxy
...
frontend genfrontend_61610-ourcomp_drupal_prod
...
filter bwlim-in in_100mbit_limit_by_src limit 12500k key src table genbackend_sourceip
filter bwlim-out out_100mbit_limit_by_src limit 12500k key src table genbackend_sourceip

...
        http-request set-var(req.bandwidth_limit) fe_name,map_str(/etc/haproxy/bandwidth-limit.map,"disabled")

        http-request set-bandwidth-limit out_100mbit_limit_by_src if { var(req.bandwidth_limit) -m str "default" }
        http-request set-bandwidth-limit in_100mbit_limit_by_src if { var(req.bandwidth_limit) -m str "default" }
...
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.8-dev3-e74d77b 2023/02/04 - https://haproxy.org/
Status: development branch - not safe for use in production.
Known bugs: https://github.com/haproxy/haproxy/issues?q=is:issue+is:open
Running on: Linux 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment -DMAX_SESS_STKCTR=12
  OPTIONS = USE_LIBCRYPT=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB= USE_SLZ=1 USE_NS= USE_SYSTEMD=1 USE_PROMEX=1 USE_PCRE= USE_PCRE_JIT= USE_PCRE2=1 USE_PCRE2_JIT=
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER -NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 -PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION -QUIC +RT +SHM_OPEN +SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=8).
Built with OpenSSL version : OpenSSL 1.1.1n  15 Mar 2022
Running on OpenSSL version : OpenSSL 1.1.1n  15 Mar 2022
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Support for malloc_trim() is enabled.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.36 2020-12-04
PCRE2 library supports JIT : no (USE_PCRE2_JIT not set)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 10.2.1 20210110

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[BWLIM] bwlim-in
	[BWLIM] bwlim-out
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
```

### Last Outputs and Backtraces

```plain
Core was generated by `/usr/sbin/haproxy -Ws -f /etc/haproxy/haproxy.cfg -S /run/haproxy-master.sock -'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  ha_crash_now () at include/haproxy/bug.h:52
52	include/haproxy/bug.h: No such file or directory.
[Current thread is 1 (Thread 0x7f485a2be700 (LWP 1287983))]
(gdb) set print elements 0
(gdb) t a a bt full

Thread 8 (Thread 0x7f485aabf700 (LWP 1287982)):
#0  0x00007f49252c1d56 in epoll_wait (epfd=1969, events=0x7f482404fb60, maxevents=200, timeout=timeout@entry=4) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
No locals.
#1  0x00005631b0f19231 in _do_poll (p=<optimized out>, exp=<optimized out>, wake=<optimized out>) at src/ev_epoll.c:232
        timeout = 4
        status = <optimized out>
        fd = <optimized out>
        count = <optimized out>
        updt_idx = <optimized out>
        wait_time = 4
        old_fd = <optimized out>
#2  0x00005631b1060f3a in run_poll_loop () at src/haproxy.c:3005
        next = <optimized out>
        wake = <optimized out>
        __func__ = {<optimized out> <repeats 14 times>}
#3  0x00005631b1061569 in run_thread_poll_loop (data=<optimized out>) at src/haproxy.c:3126
        ptaf = <optimized out>
        ptif = <optimized out>
        ptdf = <optimized out>
        ptff = <optimized out>
        init_left = 0
        init_mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}
        init_cond = {__data = {{__wseq = 27, __wseq32 = {__low = 27, __high = 0}}, {__g1_start = 23, __g1_start32 = {__low = 23, __high = 0}}, __g_refs = {0, 0}, __g_size = {0, 0}, __g1_orig_size = 8, __wrefs = 0, __g_signals = {0, 0}}, __size = "\033\000\000\000\000\000\000\000\027", '\000' <repeats 23 times>, "\b", '\000' <repeats 14 times>, __align = 27}
#4  0x00007f49258fcea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139948735592192, -8671228983104977403, 140727671654174, 140727671654175, 139948735546752, 8396800, 8735064045703710213, 8735804811278992901}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#5  0x00007f49252c1a2f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 7 (Thread 0x7f485ff0f700 (LWP 1287981)):
#0  0x00007f49252c1d56 in epoll_wait (epfd=1972, events=0x7f481804fb60, maxevents=200, timeout=timeout@entry=3) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
No locals.
#1  0x00005631b0f19231 in _do_poll (p=<optimized out>, exp=<optimized out>, wake=<optimized out>) at src/ev_epoll.c:232
        timeout = 3
        status = <optimized out>
        fd = <optimized out>
        count = <optimized out>
        updt_idx = <optimized out>
        wait_time = 3
        old_fd = <optimized out>
#2  0x00005631b1060f3a in run_poll_loop () at src/haproxy.c:3005
        next = <optimized out>
        wake = <optimized out>
        __func__ = {<optimized out> <repeats 14 times>}
#3  0x00005631b1061569 in run_thread_poll_loop (data=<optimized out>) at src/haproxy.c:3126
        ptaf = <optimized out>
        ptif = <optimized out>
        ptdf = <optimized out>
        ptff = <optimized out>
        init_left = 0
        init_mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}
        init_cond = {__data = {{__wseq = 27, __wseq32 = {__low = 27, __high = 0}}, {__g1_start = 23, __g1_start32 = {__low = 23, __high = 0}}, __g_refs = {0, 0}, __g_size = {0, 0}, __g1_orig_size = 8, __wrefs = 0, __g_signals = {0, 0}}, __size = "\033\000\000\000\000\000\000\000\027", '\000' <repeats 23 times>, "\b", '\000' <repeats 14 times>, __align = 27}
#4  0x00007f49258fcea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139948824000256, -8671228983104977403, 140727671654174, 140727671654175, 139948823954816, 8396800, 8735053419954619909, 8735804811278992901}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#5  0x00007f49252c1a2f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
--Type <RET> for more, q to quit, c to continue without paging--c
No locals.

Thread 6 (Thread 0x7f4859abd700 (LWP 1287984)):
#0  0x00007f49252c1d56 in epoll_wait (epfd=1966, events=0x7f483004fb60, maxevents=200, timeout=timeout@entry=4) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
No locals.
#1  0x00005631b0f19231 in _do_poll (p=<optimized out>, exp=<optimized out>, wake=<optimized out>) at src/ev_epoll.c:232
        timeout = 4
        status = <optimized out>
        fd = <optimized out>
        count = <optimized out>
        updt_idx = <optimized out>
        wait_time = 4
        old_fd = <optimized out>
#2  0x00005631b1060f3a in run_poll_loop () at src/haproxy.c:3005
        next = <optimized out>
        wake = <optimized out>
        __func__ = {<optimized out> <repeats 14 times>}
#3  0x00005631b1061569 in run_thread_poll_loop (data=<optimized out>) at src/haproxy.c:3126
        ptaf = <optimized out>
        ptif = <optimized out>
        ptdf = <optimized out>
        ptff = <optimized out>
        init_left = 0
        init_mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}
        init_cond = {__data = {{__wseq = 27, __wseq32 = {__low = 27, __high = 0}}, {__g1_start = 23, __g1_start32 = {__low = 23, __high = 0}}, __g_refs = {0, 0}, __g_size = {0, 0}, __g1_orig_size = 8, __wrefs = 0, __g_signals = {0, 0}}, __size = "\033\000\000\000\000\000\000\000\027", '\000' <repeats 23 times>, "\b", '\000' <repeats 14 times>, __align = 27}
#4  0x00007f49258fcea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139948718806784, -8671228983104977403, 140727671654174, 140727671654175, 139948718761344, 8396800, 8735057451855169029, 8735804811278992901}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#5  0x00007f49252c1a2f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 5 (Thread 0x7f4924e0f180 (LWP 1287965)):
#0  0x00007f49252c1d56 in epoll_wait (epfd=6, events=0x5631be400740, maxevents=200, timeout=timeout@entry=2) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
No locals.
#1  0x00005631b0f19231 in _do_poll (p=<optimized out>, exp=<optimized out>, wake=<optimized out>) at src/ev_epoll.c:232
        timeout = 2
        status = <optimized out>
        fd = <optimized out>
        count = <optimized out>
        updt_idx = <optimized out>
        wait_time = 2
        old_fd = <optimized out>
#2  0x00005631b1060f3a in run_poll_loop () at src/haproxy.c:3005
        next = <optimized out>
        wake = <optimized out>
        __func__ = {<optimized out> <repeats 14 times>}
#3  0x00005631b1061569 in run_thread_poll_loop (data=<optimized out>) at src/haproxy.c:3126
        ptaf = <optimized out>
        ptif = <optimized out>
        ptdf = <optimized out>
        ptff = <optimized out>
        init_left = 0
        init_mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}
        init_cond = {__data = {{__wseq = 27, __wseq32 = {__low = 27, __high = 0}}, {__g1_start = 23, __g1_start32 = {__low = 23, __high = 0}}, __g_refs = {0, 0}, __g_size = {0, 0}, __g1_orig_size = 8, __wrefs = 0, __g_signals = {0, 0}}, __size = "\033\000\000\000\000\000\000\000\027", '\000' <repeats 23 times>, "\b", '\000' <repeats 14 times>, __align = 27}
#4  0x00005631b0f160c2 in main (argc=<optimized out>, argv=<optimized out>) at src/haproxy.c:3782
        err = <optimized out>
        retry = <optimized out>
        limit = {rlim_cur = 18446744073709551615, rlim_max = 18446744073709551615}
        pidfd = <optimized out>
        intovf = <optimized out>
        msg = <optimized out>

Thread 4 (Thread 0x7f4924e03700 (LWP 1287978)):
#0  0x00007f49252c1d56 in epoll_wait (epfd=1954, events=0x7f4920050250, maxevents=200, timeout=timeout@entry=4) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
No locals.
#1  0x00005631b0f19231 in _do_poll (p=<optimized out>, exp=<optimized out>, wake=<optimized out>) at src/ev_epoll.c:232
        timeout = 4
        status = <optimized out>
        fd = <optimized out>
        count = <optimized out>
        updt_idx = <optimized out>
        wait_time = 4
        old_fd = <optimized out>
#2  0x00005631b1060f3a in run_poll_loop () at src/haproxy.c:3005
        next = <optimized out>
        wake = <optimized out>
        __func__ = {<optimized out> <repeats 14 times>}
#3  0x00005631b1061569 in run_thread_poll_loop (data=<optimized out>) at src/haproxy.c:3126
        ptaf = <optimized out>
        ptif = <optimized out>
        ptdf = <optimized out>
        ptff = <optimized out>
        init_left = 0
        init_mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}
        init_cond = {__data = {{__wseq = 27, __wseq32 = {__low = 27, __high = 0}}, {__g1_start = 23, __g1_start32 = {__low = 23, __high = 0}}, __g_refs = {0, 0}, __g_size = {0, 0}, __g1_orig_size = 8, __wrefs = 0, __g_signals = {0, 0}}, __size = "\033\000\000\000\000\000\000\000\027", '\000' <repeats 23 times>, "\b", '\000' <repeats 14 times>, __align = 27}
#4  0x00007f49258fcea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139952128014080, -8671228983104977403, 140727671654174, 140727671654175, 139952127968640, 94771430052720, 8735807425085752837, 8735804811278992901}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#5  0x00007f49252c1a2f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 3 (Thread 0x7f4860710700 (LWP 1287980)):
#0  0x00007f49252c1d56 in epoll_wait (epfd=1960, events=0x7f484804fb60, maxevents=200, timeout=timeout@entry=4) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
No locals.
#1  0x00005631b0f19231 in _do_poll (p=<optimized out>, exp=<optimized out>, wake=<optimized out>) at src/ev_epoll.c:232
        timeout = 4
        status = <optimized out>
        fd = <optimized out>
        count = <optimized out>
        updt_idx = <optimized out>
        wait_time = 4
        old_fd = <optimized out>
#2  0x00005631b1060f3a in run_poll_loop () at src/haproxy.c:3005
        next = <optimized out>
        wake = <optimized out>
        __func__ = {<optimized out> <repeats 14 times>}
#3  0x00005631b1061569 in run_thread_poll_loop (data=<optimized out>) at src/haproxy.c:3126
        ptaf = <optimized out>
        ptif = <optimized out>
        ptdf = <optimized out>
        ptff = <optimized out>
        init_left = 0
        init_mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}
        init_cond = {__data = {{__wseq = 27, __wseq32 = {__low = 27, __high = 0}}, {__g1_start = 23, __g1_start32 = {__low = 23, __high = 0}}, __g_refs = {0, 0}, __g_size = {0, 0}, __g1_orig_size = 8, __wrefs = 0, __g_signals = {0, 0}}, __size = "\033\000\000\000\000\000\000\000\027", '\000' <repeats 23 times>, "\b", '\000' <repeats 14 times>, __align = 27}
#4  0x00007f49258fcea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139948832392960, -8671228983104977403, 140727671654174, 140727671654175, 139948832347520, 8396800, 8735113893631018501, 8735804811278992901}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#5  0x00007f49252c1a2f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 2 (Thread 0x7f4860f11700 (LWP 1287979)):
#0  0x00007f49252c1d56 in epoll_wait (epfd=1957, events=0x7f485404fb60, maxevents=200, timeout=timeout@entry=4) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
No locals.
#1  0x00005631b0f19231 in _do_poll (p=<optimized out>, exp=<optimized out>, wake=<optimized out>) at src/ev_epoll.c:232
        timeout = 4
        status = <optimized out>
        fd = <optimized out>
        count = <optimized out>
        updt_idx = <optimized out>
        wait_time = 4
        old_fd = <optimized out>
#2  0x00005631b1060f3a in run_poll_loop () at src/haproxy.c:3005
        next = <optimized out>
        wake = <optimized out>
        __func__ = {<optimized out> <repeats 14 times>}
#3  0x00005631b1061569 in run_thread_poll_loop (data=<optimized out>) at src/haproxy.c:3126
        ptaf = <optimized out>
        ptif = <optimized out>
        ptdf = <optimized out>
        ptff = <optimized out>
        init_left = 0
        init_mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}
        init_cond = {__data = {{__wseq = 27, __wseq32 = {__low = 27, __high = 0}}, {__g1_start = 23, __g1_start32 = {__low = 23, __high = 0}}, __g_refs = {0, 0}, __g_size = {0, 0}, __g1_orig_size = 8, __wrefs = 0, __g_signals = {0, 0}}, __size = "\033\000\000\000\000\000\000\000\027", '\000' <repeats 23 times>, "\b", '\000' <repeats 14 times>, __align = 27}
#4  0x00007f49258fcea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139948840785664, -8671228983104977403, 140727671654174, 140727671654175, 139948840740224, 8396800, 8735112794656261637, 8735804811278992901}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#5  0x00007f49252c1a2f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 1 (Thread 0x7f485a2be700 (LWP 1287983)):
#0  ha_crash_now () at include/haproxy/bug.h:52
No locals.
#1  stream_dump_and_crash (obj=0x7f483c07d690, rate=<optimized out>) at src/stream.c:2920
        s = <optimized out>
        msg = 0x7f483c0b4ae0 "A bogus STREAM [0x7f483c07d690] is spinning at 1061810 calls per second and refuses to die, aborting now! Please report this error to developers [strm=0x7f483c07d690,44c0a src=SOMEIPV6 fe=genfrontend_61610-ourcomp_drupal_prod be=genbackend_ourcomp_varnish_6172 dst=varnish txn=0x7f483c133c70,43000 txn.req=MSG_DONE,4c txn.rsp=MSG_DATA,d rqf=69842028 rqa=48000 rpf=c204a824 rpa=20000000 scf=0x7f483c0fbd50,CLO,80 scb=0x7f483c1980e0,CLO,11 af=(nil),0 sab=(nil),0 cof=0x5631be5226d0,801c0300:H2(0x7f483c062220)/SSL(0x7f483c0a9140)/tcpv6(1977) cob=0x7f483c12ef90,300:H1(0x7f483c1df2d0)/RAW((nil))/unix_stream(2015) filters={0x7f483c10abc0=\"bandwidth limitation filter\", 0x7f483c0a98f0=\"bandwidth limitation filter\", 0x7f483c1a0780=\"SPOE filter\", 0x7f483c085350=\"SPOE filter\"}]\n"
        ptr = 0x7f483c07d690
#2  0x00005631b0fb7c30 in process_stream (t=t@entry=0x7f483c14d6d0, context=0x7f483c07d690, state=516) at src/stream.c:1715
        srv = <optimized out>
        s = 0x7f483c07d690
        sess = 0x7f483c1b0d60
        rqf_last = <optimized out>
        rpf_last = <optimized out>
        rq_prod_last = <optimized out>
        rq_cons_last = <optimized out>
        rp_cons_last = <optimized out>
        rp_prod_last = <optimized out>
        req_ana_back = <optimized out>
        req = 0x7f483c07d6b0
        res = 0x7f483c07d710
        scf = <optimized out>
        scb = <optimized out>
        rate = <optimized out>
        resync_stconns = <optimized out>
        resync_request = <optimized out>
        resync_response = <optimized out>
#3  0x00005631b109079b in run_tasks_from_lists (budgets=<optimized out>) at src/task.c:632
        process = <optimized out>
        tl_queues = <optimized out>
        t = 0x7f483c14d6d0
        budget_mask = <optimized out>
        profile_entry = 0x0
        done = <optimized out>
        queue = <optimized out>
        state = <optimized out>
        ctx = <optimized out>
        __func__ = {<optimized out> <repeats 21 times>}
#4  0x00005631b1090fca in process_runnable_tasks () at src/task.c:861
        tt = 0x5631b142e680 <ha_thread_ctx+2304>
        lrq = <optimized out>
        grq = <optimized out>
        t = <optimized out>
        max = {0, 92, 0, 0}
        max_total = <optimized out>
        tmp_list = <optimized out>
        queue = <optimized out>
        max_processed = <optimized out>
        lpicked = <optimized out>
        gpicked = <optimized out>
        heavy_queued = 1
        budget = <optimized out>
        not_done_yet = <optimized out>
        __lk_r = <optimized out>
        __set_r = <optimized out>
        __msk_r = <optimized out>
        ret = <optimized out>
#5  0x00005631b1060f7a in run_poll_loop () at src/haproxy.c:2933
        next = <optimized out>
        wake = <optimized out>
        __func__ = {<optimized out> <repeats 14 times>}
#6  0x00005631b1061569 in run_thread_poll_loop (data=<optimized out>) at src/haproxy.c:3126
        ptaf = <optimized out>
        ptif = <optimized out>
        ptdf = <optimized out>
        ptff = <optimized out>
        init_left = 0
        init_mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}
        init_cond = {__data = {{__wseq = 27, __wseq32 = {__low = 27, __high = 0}}, {__g1_start = 23, __g1_start32 = {__low = 23, __high = 0}}, __g_refs = {0, 0}, __g_size = {0, 0}, __g1_orig_size = 8, __wrefs = 0, __g_signals = {0, 0}}, __size = "\033\000\000\000\000\000\000\000\027", '\000' <repeats 23 times>, "\b", '\000' <repeats 14 times>, __align = 27}
#7  0x00007f49258fcea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139948727199488, -8671228983104977403, 140727671654174, 140727671654175, 139948727154048, 8396800, 8735065148973434373, 8735804811278992901}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#8  0x00007f49252c1a2f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.
```

**Comment by idl0r** [comment]
The mentioned frontend is listed with "default" in the map so the bwlim is active here.

**Comment by capflam** [comment]
copy that

**Comment by capflam** [comment]
I have a reproducer ! I seems to only affect the 2.8-DEV. I'm on a fix now.

**Comment by idl0r** [comment]
> I have a reproducer ! I seems to only affect the 2.8-DEV. I'm on a fix now.

Oh, yeah, I forgot to mention that it must be a regression introduced in 2.8-dev3 since -dev2 was running fine for quite some time.

**Comment by capflam** [comment]
For me, the -dev2 is also affected. It seems there are 2 bugs. There is a spinning loop because of a bug in f2b02cf. It is your issue. And there is also a bug in the bwlim filter because the read timeout is still armed when the data are blocked.

**Comment by idl0r** [comment]
Interesting. Perhaps it just didn't trigger in -dev2 for some reason.

**Comment by capflam** [comment]
Most probably. Or there is another bug ...

**Comment by capflam** [comment]
Here is a patch that should solve your issue. However, I'm still reviewing the code to be sure it is the best way to fix it. I'm also working on a fix for the bwlim filter.

```diff
diff --git a/src/http_ana.c b/src/http_ana.c
index 09c374ff9..a4092a7ab 100644
--- a/src/http_ana.c
+++ b/src/http_ana.c
@@ -4229,9 +4229,10 @@ static void http_end_request(struct stream *s)
                 */
                chn->flags |= CF_NEVER_WAIT;
 
-               if (txn->rsp.msg_state < HTTP_MSG_DONE) {
-                       /* The server has not finished to respond, so we
-                        * don't want to move in order not to upset it.
+               if (txn->rsp.msg_state < HTTP_MSG_DONE && s->scb->state != SC_ST_CLO) {
+                       /* The server has not finished to respond and the
+                        * backend SC is not closed, so we don't want to move in
+                        * order not to upset it.
                         */
                        DBG_TRACE_DEVEL("waiting end of the response", STRM_EV_HTTP_ANA, s, txn);
                        return;
@@ -4338,7 +4339,7 @@ static void http_end_response(struct stream *s)
                 */
                /* channel_dont_read(chn); */
 
-               if (txn->req.msg_state < HTTP_MSG_DONE) {
+               if (txn->req.msg_state < HTTP_MSG_DONE && s->scf->state != SC_ST_CLO) {
                        /* The client seems to still be sending data, probably
                         * because we got an error response during an upload.
                         * We have the choice of either breaking the connection
```

**Comment by idl0r** [comment]
At least no more crashes at the moment. So it seems to have fixed that.

**Comment by capflam** [comment]
Good news. Thanks for the info !
