### ISSUE TITLE
High CPU usage on HAProxy 2.2.24

### ISSUE THREAD

**Issue by RS146BIJAY** [haproxy/haproxy#2064]
### Detailed Description of the Problem

We are observing a constant high CPU usage in many of our haproxy instances. CPU reaches around 100% (with the major contributor being HAP) until we bounce HAP on the faulty instance, after which the CPU comes back to ~10%. We also observe HAP going down randomly on few nodes.The issue is happening even on the instances with 0 traffic, so I don't think this may be related to traffic.

```strace``` result:

```
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
```

### Expected Behavior

HAP should not cause CPU utilisation to go to 100%. Also HAProxy should not be going down.

### Steps to Reproduce the Behavior

NA

### Do you have an idea how to solve the issue?

Bouncing the HAP on the affected instances.

### What is your configuration?

```haproxy
Some values are removed.


global
    maxconn     30000
    daemon
    tune.bufsize 32678  
    spread-checks 5
    user <>
    log 127.0.0.1 local0 info
    h1-case-adjust-file ENV_ROOT/etc/headers_adjust.map
    set-dumpable

defaults
    mode        http
    timeout client 300s
    timeout connect 1000ms
    timeout http-keep-alive 300s
    option http-server-close
    option redispatch
    option splice-auto

    option httplog

    errorfile 403 ENV_ROOT/etc/es_403.json
    errorfile 500 ENV_ROOT/etc/es_500.json
    errorfile 502 ENV_ROOT/etc/es_502.json
    errorfile 503 ENV_ROOT/etc/es_503.json
    errorfile 504 ENV_ROOT/etc/es_504.json

resolvers local_res
    nameserver dns1 xxx.xxx.xxx.xxx:53
    timeout resolve 30s
    hold valid 60s

frontend single_box
    bind 0.0.0.0:443 interface eth0 SSL_CERT
    bind :::443 interface eth0 SSL_CERT
    bind 0.0.0.0:443 interface lo SSL_CERT
    bind :::443 interface lo SSL_CERT

    maxconn 7000

    http-request add-header <> 1
    http-request del-header <>

    option h1-case-adjust-bogus-client
    acl h_xff_exists req.hdr(X-Forwarded-For) -m found
    http-request replace-header X-Forwarded-For .*,(.*) \1 if h_xff_exists
    http-response del-header Server

    acl allowed_meth method GET HEAD POST PUT DELETE OPTIONS PATCH
    acl is_healthcheck path /some-path
    acl is_proxy_stats path_beg /some-path
    acl is_proxy_health path_beg /some-path
    acl is_<> path_beg /
    acl is_internal_auth path_sub <>
    http-request deny if <>
    http-request set-nice -1024 if is_healthcheck

    acl <> capture.req.uri -m beg /<>
    http-request set-var(txn.https) hdr(X-Forwarded-Proto)
    acl is_https var(txn.https) -m str https
    http-response add-header Strict-Transport-Security "max-age=31536000" if <> is_https
    use_backend dne unless allowed_meth
    use_backend <> if is_healthcheck
    use_backend <> if is_proxy_stats
    use_backend <> if is_proxy_health
    use_backend <> if <>

    default_backend <>
    option httplog
    capture request header <> len 50
    capture request header Host len 50
    capture request header <> len 50
```

### Output of `haproxy -vv`

```
HA-Proxy version 2.2.24 2022/05/13 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.24.html
Running on: Linux 5.4.209-116.363.amzn2.x86_64 #1 SMP Wed Aug 10 21:19:18 UTC 2022 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = /usr/bin/gcc
  CFLAGS  = -pthread -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fdiagnostics-color=auto -O3 -march=core2 -msse -mfpmath=sse -g -fPIC -Wchar-subscripts -Wcomment -Wformat -Winit-self -Wmain -Wmissing-braces -Wno-pragmas -Wparentheses -Wreturn-type -Wsequence-point -Wstrict-aliasing -Wswitch -Wtrigraphs -Wuninitialized -Wunknown-pragmas -Wunused-label -Wunused-variable -Wunused-value -Wno-error=missing-include-dirs -Wno-error=narrowing -Wpointer-sign -Wimplicit -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-stringop-overflow -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.0.2zf  21 Jun 2022
Running on OpenSSL version : OpenSSL 1.0.2zf  21 Jun 2022
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2
Built with Lua version : Lua 5.4.3
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.33 2019-04-16
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 7.3.1 20180712 (Red Hat 7.3.1-6)

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : none

Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace
	[CACHE] cache
	[FCGI] fcgi-app

```

### Last Outputs and Backtraces

```plain
Thread 16 (Thread 0x7f518f7fe700 (LWP 2477)):
#0  0x00007f51a51fe297 in sched_get_priority_min () from /lib64/libc.so.6
#1  0x00000000005557b0 in ha_thread_relax () at include/haproxy/thread.h:233
#2  debug_handler (sig=<optimized out>, si=<optimized out>, arg=<optimized out>) at src/debug.c:838
#3  <signal handler called>
#4  0x0000000000511867 in tcpcheck_eval_recv (check=check@entry=0xc250f0, rule=rule@entry=0xcf3250) at src/tcpcheck.c:1506
#5  0x0000000000513f1b in tcpcheck_main (check=check@entry=0xc250f0) at src/tcpcheck.c:2047
#6  0x00000000004e4f8a in wake_srv_chk (cs=<optimized out>) at src/check.c:786
#7  0x00000000004e532d in event_srv_chk_io (t=t@entry=0xc216c0, ctx=ctx@entry=0xc250f0, state=<optimized out>) at src/check.c:841
#8  0x00000000005a8993 in run_tasks_from_lists (budgets=budgets@entry=0x7f518f7db324) at src/task.c:473
#9  0x00000000005a9335 in process_runnable_tasks () at src/task.c:713
#10 0x000000000055db88 in run_poll_loop () at src/haproxy.c:2977
#11 0x000000000055df68 in run_thread_poll_loop (data=<optimized out>) at src/haproxy.c:3142
#12 0x00007f51a615f44b in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#13 0x00007f51a521556f in umount2 () from /lib64/libc.so.6
No symbol table info available.
#14 0x0000000000000000 in ?? ()
No symbol table info available.

Thread 15 (Thread 0x7f518ffff700 (LWP 2476)):
#0  0x00007f51a51fe297 in sched_get_priority_min () from /lib64/libc.so.6
No symbol table info available.
#1  0x00000000005557b0 in ha_thread_relax () at include/haproxy/thread.h:233
No locals.
#2  debug_handler (sig=<optimized out>, si=<optimized out>, arg=<optimized out>) at src/debug.c:838
No locals.
#3  <signal handler called>
No symbol table info available.
#4  0x0000000000511867 in tcpcheck_eval_recv (check=check@entry=0xc30660, rule=rule@entry=0xcf3250) at src/tcpcheck.c:1506
#5  0x0000000000513f1b in tcpcheck_main (check=check@entry=0xc30660) at src/tcpcheck.c:2047
#6  0x00000000004e4f8a in wake_srv_chk (cs=<optimized out>) at src/check.c:786
#7  0x00000000004e532d in event_srv_chk_io (t=t@entry=0xc23c10, ctx=ctx@entry=0xc30660, state=<optimized out>) at src/check.c:841
#8  0x00000000005a8993 in run_tasks_from_lists (budgets=budgets@entry=0x7f518ffdc324) at src/task.c:473
#9  0x00000000005a9335 in process_runnable_tasks () at src/task.c:713
#10 0x000000000055db88 in run_poll_loop () at src/haproxy.c:2977
#11 0x000000000055df68 in run_thread_poll_loop (data=<optimized out>) at src/haproxy.c:3142
#12 0x00007f51a615f44b in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#13 0x00007f51a521556f in umount2 () from /lib64/libc.so.6
No symbol table info available.
#14 0x0000000000000000 in ?? ()
No symbol table info available.

Thread 14 (Thread 0x7f5194ff9700 (LWP 2475)):
#0  0x00007f51a51fe297 in sched_get_priority_min () from /lib64/libc.so.6
No symbol table info available.
#1  0x00000000005557b0 in ha_thread_relax () at include/haproxy/thread.h:233
No locals.
#2  debug_handler (sig=<optimized out>, si=<optimized out>, arg=<optimized out>) at src/debug.c:838
No locals.
#3  <signal handler called>
No symbol table info available.
#4  0x000000000057b573 in dns_resolve_recv (dgram=0xcf2940) at src/dns.c:2141

#5  0x00000000005d2193 in dgram_fd_handler (fd=<optimized out>) at src/dgram.c:25
#6  0x00000000004285de in fd_update_events (evts=<optimized out>, fd=58) at include/haproxy/fd.h:415
#7  _do_poll, exp=<optimized out>, wake=<optimized out>) at src/ev_epoll.c:251
#8  0x000000000055db2d in run_poll_loop () at src/haproxy.c:3024
#9  0x000000000055df68 in run_thread_poll_loop (data=<optimized out>) at src/haproxy.c:3142
#10 0x00007f51a615f44b in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#11 0x00007f51a521556f in umount2 () from /lib64/libc.so.6
No symbol table info available.
#12 0x0000000000000000 in ?? ()
No symbol table info available.

Thread 13 (Thread 0x7f51957fa700 (LWP 2474)):
#0  0x00007f51a51fe297 in sched_get_priority_min () from /lib64/libc.so.6
No symbol table info available.
#1  0x00000000005557b0 in ha_thread_relax () at include/haproxy/thread.h:233
No locals.
#2  debug_handler (sig=<optimized out>, si=<optimized out>, arg=<optimized out>) at src/debug.c:838
No locals.
#3  <signal handler called>
No symbol table info available.
#4  0x000000000057b573 in dns_resolve_recv (dgram=0xcf2940) at src/dns.c:2141
#5  0x00000000005d2193 in dgram_fd_handler (fd=<optimized out>) at src/dgram.c:25
#6  0x00000000004285de in fd_update_events (evts=<optimized out>, fd=58) at include/haproxy/fd.h:415
#7  _do_poll (p=<optimized out>, exp=<optimized out>, wake=<optimized out>) at src/ev_epoll.c:251
#8  0x000000000055db2d in run_poll_loop () at src/haproxy.c:3024
#9  0x000000000055df68 in run_thread_poll_loop (data=<optimized out>) at src/haproxy.c:3142
No symbol table info available.
#11 0x00007f51a521556f in umount2 () from /lib64/libc.so.6
No symbol table info available.
#12 0x0000000000000000 in ?? ()
No symbol table info available.

Thread 12 (Thread 0x7f5195ffb700 (LWP 2473)):
#0  0x00007f51a51fe297 in sched_get_priority_min () from /lib64/libc.so.6
No symbol table info available.
#1  0x00000000005557b0 in ha_thread_relax () at include/haproxy/thread.h:233
No locals.
#2  debug_handler (sig=<optimized out>, si=<optimized out>, arg=<optimized out>) at src/debug.c:838
No locals.
#3  <signal handler called>
No symbol table info available.
#4  dns_resolve_recv (dgram=0xcf2940) at src/dns.c:2141
#5  0x00000000005d2193 in dgram_fd_handler (fd=<optimized out>) at src/dgram.c:25
#6  0x00000000004285de in fd_update_events (evts=<optimized out>, fd=58) at include/haproxy/fd.h:415
#7  _do_poll (p=<optimized out>, exp=<optimized out>, wake=<optimized out>) at src/ev_epoll.c:251
#8  0x000000000055db2d in run_poll_loop () at src/haproxy.c:3024
#9  0x000000000055df68 in run_thread_poll_loop (data=<optimized out>) at src/haproxy.c:3142
#10 0x00007f51a615f44b in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#11 0x00007f51a521556f in umount2 () from /lib64/libc.so.6
No symbol table info available.
#12 0x0000000000000000 in ?? ()
No symbol table info available.
#0  0x00007f51a51fe297 in sched_get_priority_min () from /lib64/libc.so.6
No symbol table info available.
#1  0x00000000005557b0 in ha_thread_relax () at include/haproxy/thread.h:233
No locals.
#2  debug_handler (sig=<optimized out>, si=<optimized out>, arg=<optimized out>) at src/debug.c:838
No locals.
#3  <signal handler called>
No symbol table info available.
#4  run_tasks_from_lists (budgets=budgets@entry=0x7f51967d9324) at src/task.c:506
#5  0x00000000005a9335 in process_runnable_tasks () at src/task.c:713
#6  0x000000000055db88 in run_poll_loop () at src/haproxy.c:2977
#7  0x000000000055df68 in run_thread_poll_loop (data=<optimized out>) at src/haproxy.c:3142
#8  0x00007f51a615f44b in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#9  0x00007f51a521556f in umount2 () from /lib64/libc.so.6
No symbol table info available.
#10 0x0000000000000000 in ?? ()
No symbol table info available.

#0  0x00007f51a51fe297 in sched_get_priority_min () from /lib64/libc.so.6
No symbol table info available.
#1  0x00000000005557b0 in ha_thread_relax () at include/haproxy/thread.h:233
No locals.
#2  debug_handler (sig=<optimized out>, si=<optimized out>, arg=<optimized out>) at src/debug.c:838
No locals.
#3  <signal handler called>
No symbol table info available.
#4  ha_thread_dump_all_to_trash () at src/debug.c:809
#5  0x0000000000553d59 in ha_panic () at src/debug.c:268
No locals.
#6  0x00000000005c3b4b in wdt_handler (sig=14, si=<optimized out>, arg=<optimized out>) at src/wdt.c:121
#7  <signal handler called>
No symbol table info available.
#8  0x000000000057b573 in dns_resolve_recv (dgram=0xcf2940) at src/dns.c:2141
#9  0x00000000005d2193 in dgram_fd_handler (fd=<optimized out>) at src/dgram.c:25
#10 0x00000000004285de in fd_update_events (evts=<optimized out>, fd=58) at include/haproxy/fd.h:415
#11 _do_poll (p=<optimized out>, exp=<optimized out>, wake=<optimized out>) at src/ev_epoll.c:251
#12 0x000000000055db2d in run_poll_loop () at src/haproxy.c:3024
#13 0x000000000055df68 in run_thread_poll_loop (data=<optimized out>) at src/haproxy.c:3142
#14 0x00007f51a615f44b in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#15 0x00007f51a521556f in umount2 () from /lib64/libc.so.6
No symbol table info available.
#16 0x0000000000000000 in ?? ()
No symbol table info available.

Thread 9 (Thread 0x7f51977fe700 (LWP 2470)):
#0  0x00007f51a51fe297 in sched_get_priority_min () from /lib64/libc.so.6
No symbol table info available.
#1  0x00000000005557b0 in ha_thread_relax () at include/haproxy/thread.h:233
No locals.
#2  debug_handler (sig=<optimized out>, si=<optimized out>, arg=<optimized out>) at src/debug.c:838
No locals.
#3  <signal handler called>
No symbol table info available.
#4  0x00007f51a6bf7db6 in strcmp () from /lib64/ld-linux-x86-64.so.2
No symbol table info available.
#5  0x00007f51a6bedec5 in _dl_name_match_p () from /lib64/ld-linux-x86-64.so.2
No symbol table info available.
#6  0x00007f51a6be700e in do_lookup_x () from /lib64/ld-linux-x86-64.so.2
No symbol table info available.
#7  0x00007f51a6be7b63 in _dl_lookup_symbol_x () from /lib64/ld-linux-x86-64.so.2
No symbol table info available.
#8  0x00007f51a6bec623 in _dl_fixup () from /lib64/ld-linux-x86-64.so.2
No symbol table info available.
#9  0x00007f51a6bf340a in _dl_runtime_resolve_xsavec () from /lib64/ld-linux-x86-64.so.2
---Type <return> to continue, or q <return> to quit---
No symbol table info available.
#10 0x0000000000553cf7 in ha_thread_relax () at include/haproxy/thread.h:233
No locals.
#11 ha_thread_dump_all_to_trash () at src/debug.c:811
        old = <optimized out>
#12 0x0000000000553d59 in ha_panic () at src/debug.c:268
No locals.
#13 0x00000000005c3b4b in wdt_handler (sig=14, si=<optimized out>, arg=<optimized out>) at src/wdt.c:121
#14 <signal handler called>
No symbol table info available.
#15 0x000000000057b573 in dns_resolve_recv (dgram=0xcf2940) at src/dns.c:2141
#16 0x00000000005d2193 in dgram_fd_handler (fd=<optimized out>) at src/dgram.c:25
#17 0x00000000004285de in fd_update_events (evts=<optimized out>, fd=58) at include/haproxy/fd.h:415
#18 _do_poll (p=<optimized out>, exp=<optimized out>, wake=<optimized out>) at src/ev_epoll.c:251
#19 0x000000000055db2d in run_poll_loop () at src/haproxy.c:3024
#20 0x000000000055df68 in run_thread_poll_loop (data=<optimized out>) at src/haproxy.c:3142
#21 0x00007f51a615f44b in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#22 0x00007f51a521556f in umount2 () from /lib64/libc.so.6
No symbol table info available.
#23 0x0000000000000000 in ?? ()
No symbol table info available.

Thread 8 (Thread 0x7f5197fff700 (LWP 2469)):
#0  0x00007f51a51fe297 in sched_get_priority_min () from /lib64/libc.so.6
No symbol table info available.
#1  0x00000000005557b0 in ha_thread_relax () at include/haproxy/thread.h:233
No locals.
#2  debug_handler (sig=<optimized out>, si=<optimized out>, arg=<optimized out>) at src/debug.c:838
No locals.
#3  <signal handler called>
No symbol table info available.
#4  0x000000000057b320 in dns_resolve_recv (dgram=0xcf2940) at src/dns.c:2141
#5  0x00000000005d2193 in dgram_fd_handler (fd=<optimized out>) at src/dgram.c:25
#6  0x00000000004285de in fd_update_events (evts=<optimized out>, fd=58) at include/haproxy/fd.h:415
#7  _do_poll (p=<optimized out>, exp=<optimized out>, wake=<optimized out>) at src/ev_epoll.c:251
#8  0x000000000055db2d in run_poll_loop () at src/haproxy.c:3024
#9  0x000000000055df68 in run_thread_poll_loop (data=<optimized out>) at src/haproxy.c:3142
#10 0x00007f51a615f44b in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#11 0x00007f51a521556f in umount2 () from /lib64/libc.so.6
No symbol table info available.
#12 0x0000000000000000 in ?? ()
No symbol table info available.

Thread 7 (Thread 0x7f519cdb3700 (LWP 2468)):
#0  0x00007f51a51fe297 in sched_get_priority_min () from /lib64/libc.so.6
No symbol table info available.
#1  0x00000000005557b0 in ha_thread_relax () at include/haproxy/thread.h:233
No locals.
#2  debug_handler (sig=<optimized out>, si=<optimized out>, arg=<optimized out>) at src/debug.c:838
No locals.
#3  <signal handler called>
No symbol table info available.
#4  0x000000000057b320 in dns_resolve_recv (dgram=0xcf2940) at src/dns.c:2141
#5  0x00000000005d2193 in dgram_fd_handler (fd=<optimized out>) at src/dgram.c:25
#6  0x00000000004285de in fd_update_events (evts=<optimized out>, fd=58) at include/haproxy/fd.h:415
#7  _do_poll (p=<optimized out>, exp=<optimized out>, wake=<optimized out>) at src/ev_epoll.c:251
#8  0x000000000055db2d in run_poll_loop () at src/haproxy.c:3024
        next = <optimized out>
        wake = <optimized out>
#9  0x000000000055df68 in run_thread_poll_loop (data=<optimized out>) at src/haproxy.c:3142
        ptaf = <optimized out>
        ptif = <optimized out>
        ptdf = <optimized out>
        ptff = <optimized out>
        init_left = 0
```

**Comment by capflam** [comment]
The 2.2.24 is a bit old. You should upgrade to 2.2.28 first. The issue seems similar to #1952 but in addition you seems to have a race on the watchdog.

**Comment by RS146BIJAY** [comment]
@capflam I can see the issue pointed by you is already opened. Is this issue fixed in any latest version of HAProxy? Wanted to know if upgrading to 2.2.28 will fix this issue. 

Also back trace of the thread seems different. The top operation in each of the thread is ```sched_get_priority_min``` in this issue whereas it is ```resolv_process_responses``` in the issue you pointed out.

**Comment by capflam** [comment]
Traces are not the same. On your side, you are blocked in the debug handler. Probably a race in the watchdog. But the watchdog was triggered because of the resolvers. At least, it seems to be the issue. In #1952, the watchdog managed to finish and the process was aborted.

Now, I don't know if the issue is fixed in recent versions or not. There were several fixes on the resolvers but not for this issue specifically. It remains mandatory to upgrade to the latest version.

**Comment by capflam** [comment]
any update on this issue ?

**Comment by RS146BIJAY** [comment]
We are upgrading to latest version of HAP and validating if we are still seeing these issues.

**Comment by capflam** [comment]
I'm closing this issue because of inactivity. FYI, the 2.2.30 was released. If you still experience the bug on it, feel free to reopen this issue. Thanks !
