### ISSUE TITLE
Haproxy 2.8.0 and 2.6.14 crash with accept-proxy on bind directive

### ISSUE THREAD

**Issue by rapsys** [haproxy/haproxy#2186]
### Detailed Description of the Problem

When defining a bind directive like this:
`bind quic6@:::8443 ssl crt haproxy.pem alpn h3 accept-proxy`

Any request on the quic port will trigger a server crash.

Gdb output:
```
Thread 1 "haproxy" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x0000000000594cd8 in xprt_add_hs (conn=conn@entry=0x1058840) at src/connection.c:581
#2  0x0000000000622440 in session_accept_fd (cli_conn=0x1058840) at src/session.c:183
#3  0x00000000005d3577 in accept_queue_process (t=<optimized out>, context=0x786e00 <accept_queue_rings>, state=<optimized out>) at src/listener.c:152
#4  0x00000000005ed108 in run_tasks_from_lists (budgets=budgets@entry=0x7ffe3342b310) at src/task.c:596
#5  0x00000000005edbb6 in process_runnable_tasks () at src/task.c:876
#6  0x00000000005bb827 in run_poll_loop () at src/haproxy.c:2968
#7  0x00000000005bbe97 in run_thread_poll_loop (data=<optimized out>) at src/haproxy.c:3167
#8  0x000000000042d59e in main (argc=<optimized out>, argv=0x7ffe3342b898) at src/haproxy.c:3835
```

### Expected Behavior

No crash or refuse to start if this combination is not valid

### Steps to Reproduce the Behavior

1. Build and install haproxy with QUIC=1
2. Retrieve haproxy.conf
3. Run with haproxy -f haproxy.conf -db
4. Add directive to your 8443 backend
http-after-response add-header alt-svc 'h3=":8443"; ma=60'
5. Use https://http3check.net/?host=example.com:8443 to trigger the crash

### Do you have any idea what may have caused this?

Improper configuration validation or unsupported feature accept-proxy for alpn h3

### What is your configuration?

```haproxy
# HAProxy configuration file

# Global config
global
        # Log to systemd
        log stdout format short local0 info
        # Number of threads
        nbthread 8
        # Pid file
        pidfile ./haproxy.pid

        # Certificate base dir
        crt-base /etc/pki/tls/certs
        # Private key base dir
        key-base /etc/pki/tls/private
        # Don't load extra files
        ssl-load-extra-files none
        # Disable SSL-v3 TLSv1.0 TLSv1.1 and TLS tickets
        ssl-default-server-options ssl-min-ver TLSv1.2 no-tls-tickets
        # Do not verify certificate
        ssl-server-verify none
        # Supported bind ciphers
        #XXX: https://wiki.mozilla.org/Security/Server_Side_TLS#Recommended-configurations
        ssl-default-bind-ciphers TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384

        # SSL/TLS session cache size
        tune.ssl.cachesize 20000
        # SSL/TLS session life time in cache
        tune.ssl.lifetime 300
        # SSL/TLS layer maximum passed bytes at a time
        tune.ssl.maxrecord 0
        # Diffie-Hellman ephemeral keys max size
        tune.ssl.default-dh-param 2048
        # Buffer size
        tune.bufsize 16384
        # Reserved buffer size
        tune.maxrewrite 1024
        # Max number of headers
        tune.http.maxhdr 101


# Default config
defaults
        # Use global log
        log global

        # Set balance mode
        balance random
        # Set http mode
        mode http
        # Set http keep alive mode
        #XXX: https://cbonte.github.io/haproxy-dconv/2.3/configuration.html#4
        option http-keep-alive
        # Dont log empty line
        option dontlognull
        # Dissociate client from dead server
        option redispatch

        # Number of retries on connection failure
        retries 3
        # Max concurrent connections
        maxconn 30000
        # Max pending connections
        backlog 30000

        # Max time for a connection attempt
        timeout connect 5s
        # Max inactivitiy time on client side
        timeout client 60s
        # Max inactivitiy time on server side
        timeout server 60s
        # Max inactivitiy time on client and server for tunnels
        timeout tunnel 3600s
        # Max time for new request
        timeout http-keep-alive 1s
        # Max time for a complete http request
        timeout http-request 15s
        # Max time for a free slot
        timeout queue 5s
        # Duration for tarpitted connections
        timeout tarpit 5s

        # Error documents
        errorfile 400 /usr/share/doc/haproxy/error/400.http
        errorfile 403 /usr/share/doc/haproxy/error/403.http
        errorfile 408 /usr/share/doc/haproxy/error/408.http
        errorfile 500 /usr/share/doc/haproxy/error/500.http
        errorfile 502 /usr/share/doc/haproxy/error/502.http
        errorfile 503 /usr/share/doc/haproxy/error/503.http
        errorfile 504 /usr/share/doc/haproxy/error/504.http


# Default quic frontend
#XXX: copy of upper one, just done to skip logs here
frontend quic_default
        # Bind to 8443 tcp port as ssl
        bind :::8443 ssl crt haproxy.pem alpn h2,http/1.1,http/1.0 accept-proxy
        # Bind to 8443 port as ssl
        bind quic6@:::8443 ssl crt haproxy.pem alpn h3 accept-proxy
        #bind quic6@:::8443 ssl crt haproxy.pem alpn h3
        # Insert X-Forwarded-For header
        option forwardfor
        # Set http log format
        option httplog
        # Log enabled
        log global

        # Check if acme challenge
        acl acme_challenge path_beg /.well-known/acme-challenge/

        # Redirect to https scheme when unsecure and not acme challenge
        http-request redirect scheme https code 302 unless { ssl_fc } || acme_challenge

        # Store origin variable as txn
        http-request set-var(txn.origin) req.hdr(Origin)
        # Store host variable as txn
        http-request set-var(txn.host) req.hdr(Host),field(1,:),lower
        # Store proto variable as txn
        http-request set-var(txn.proto) ssl_fc,iif(https,http)

        # Set forwarded proto
        http-request set-header X-Forwarded-Proto %[var(txn.proto)]
        # Set forwarded port
        http-request set-header X-Forwarded-Port %[dst_port]
        # Set forwarded for
        #http-request set-header X-Forwarded-For %[src]
        # Set forwarded by
        http-request set-header X-Forwarded-By %[dst]

        # Set forwarded
        #http-request set-header Forwarded by=%[dst]:%[dst_port];for=%[src]:%[src_port];host=%[var(txn.host)];proto=%[var(txn.proto)]
        http-request set-header Forwarded by=%[dst]:%[dst_port];for=%[src]:%[src_port];proto=%[var(txn.proto)]

        # Send to https backend
        use_backend https_default if { ssl_fc }

        # Send to default backend
        default_backend http_default


# Default http backend
backend http_default
        # Enable check
        option httpchk
        # User server default
        http-check connect default
        # Send HEAD on / with protocol HTTP/1.1 for host example.com
        http-check send meth HEAD uri / ver HTTP/1.1 hdr Host example.com
        # Expect return code between 200 and 399
        http-check expect status 200-399
        # Insert header X-Server: apache
        #http-response add-header X-Server apache
        # Activate QUIC
        #http-response set-header alt-svc 'h3=":8443"; ma=60'
        http-after-response add-header alt-svc 'h3=":8443"; ma=60'
        # Set compression algorithm
        #compression algo gzip
        # Enable compression for html, plain and css text types
        #compression type text/html text/plain text/css
        # Server with ssl and check without certificate verification
        server apache 127.0.0.1:80 no-ssl verify none no-check #cookie apache


# Default https backend
backend https_default
        # Enable check
        option httpchk
        # User server default
        http-check connect default
        # Send HEAD on / with protocol HTTP/1.1 for host example.com
        http-check send meth HEAD uri / ver HTTP/1.1 hdr Host example.com
        # Expect return code between 200 and 399
        http-check expect status 200-399
        # Insert header X-Server: apache
        #http-response add-header X-Server apache
        # Force HSTS for 5 minutes on domain and all subdomains
        #http-response set-header Strict-Transport-Security max-age=300#;\ includeSubDomains#;\ preload
        # Activate QUIC
        #http-response set-header alt-svc 'h3=":8443"; ma=60'
        http-after-response add-header alt-svc 'h3=":8443"; ma=60'
        # Set compression algorithm
        #compression algo gzip
        # Enable compression for html, plain and css text types
        #compression type text/html text/plain text/css
        # Server with ssl and check without certificate verification
        server apache 127.0.0.1:443 ssl verify none no-check #cookie apache
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.8.0-fdd8154 2023/05/31 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2028.
Known bugs: http://www.haproxy.org/bugs/bugs-2.8.0.html
Running on: Linux 6.1.27-server-2.mga8 #1 SMP PREEMPT_DYNAMIC Mon May  8 21:26:21 UTC 2023 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -fasynchronous-unwind-tables -fwrapv
  OPTIONS = USE_EPOLL=1 USE_THREAD=1 USE_TPROXY=1 USE_LINUX_TPROXY=1 USE_LINUX_SPLICE=1 USE_LIBCRYPT=1 USE_CRYPT_H=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_TFO=1 USE_NS=1 USE_DL=1 USE_RT=1 USE_SYSTEMD=1 USE_THREAD_DUMP=1 USE_QUIC=1 USE_PROMEX=1 USE_PCRE2=1 USE_PCRE2_JIT=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION +QUIC +RT +SHM_OPEN -SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL +ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=8).
Built with OpenSSL version : OpenSSL 3.0.9+quic 30 May 2023
Running on OpenSSL version : OpenSSL 3.0.9+quic 30 May 2023
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
OpenSSL providers loaded : default
Built with Lua version : Lua 5.4.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with zlib version : 1.2.12
Running on zlib version : 1.2.12
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.40 2022-04-14
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 10.4.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
       quic : mode=HTTP  side=FE     mux=QUIC  flags=HTX|NO_UPG|FRAMED
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
        [BWLIM] bwlim-in
        [BWLIM] bwlim-out
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
        [TRACE] trace
```

### Last Outputs and Backtraces

```plain
Segmentation fault (core dumped)
```

### Additional Information

Mageia 8 + quic patch + rapsys-key-private patch

**Comment by rapsys** [comment]
haproxy-2.8.0-quic.patch:
```
diff -urNp haproxy-2.8.0/Makefile.orig haproxy-2.8.0/Makefile
--- haproxy-2.8.0/Makefile.orig 2023-06-19 20:15:14.083925300 +0200
+++ haproxy-2.8.0/Makefile      2023-06-19 20:17:35.594971863 +0200
@@ -584,8 +584,8 @@ endif
 ifneq ($(USE_OPENSSL),)
   # only preset these for the regular openssl
   ifeq ($(USE_OPENSSL_WOLFSSL),)
-    SSL_CFLAGS    := $(if $(SSL_INC),-I$(SSL_INC))
-    SSL_LDFLAGS   := $(if $(SSL_LIB),-L$(SSL_LIB)) -lssl -lcrypto
+    SSL_CFLAGS    := $(if $(SSL_INC),-I$(SSL_INC)) $(shell pkg-config --cflags libcrypto-quic libssl-quic)
+    SSL_LDFLAGS   := $(if $(SSL_LIB),-L$(SSL_LIB)) $(shell pkg-config --libs libcrypto-quic libssl-quic)
   endif
   USE_SSL         := $(if $(USE_SSL),$(USE_SSL),implicit)
   OPTIONS_OBJS += src/ssl_sock.o src/ssl_ckch.o src/ssl_sample.o src/ssl_crtlist.o src/cfgparse-ssl.o src/ssl_utils.o src/jwt.o src/ssl_ocsp.o
```

haproxy-2.8.0-rapsys-key-private.patch:
```
From: Raphaël Gertz < haproxy TA rapsys TOD eu >
Date: Mon Aug 02 01:00:00 CET 2021
Subject: [PATCH] Support for key-base and ssl-load-extra-files=private on haproxy

It is a long awaited feature for RedHat based distributions:
* Mageia
* CentOS
* Red Hat Entreprise Linux(RHEL)
* Fedora
* OpenSUSE
* [...]

This implement search for extra private PEM keys with two possibilities.

1/ Setting key-base in global section:

global
        key-base = /etc/pki/tls/private

listen
        bind *:443 ssl crt /etc/pki/tls/certs/example.com.pem


2/ Setting ssl-load-extra-files in global section:

global
        ssl-load-extra-files = private

listen
        bind *:443 ssl crt /etc/pki/tls/certs/example.com.pem


3/ Setting crt-base and key-base in global section:

global
        crt-base /etc/pki/tls/certs
        key-base /etc/pki/tls/private
        ssl-load-extra-files = none

listen
        bind :443 ssl crt example.com.pem


4/ Setting crt-base and ssl-load-extra-files in global section:

global
        crt-base /etc/pki/tls/certs
        ssl-load-extra-files = private

listen
        bind :443 ssl crt example.com.pem

The search process will try to load the extra key in all cases:
/etc/pki/tls/private/example.com.pem

When private key is missing we prevent call to X509_check_private_key to avoid
a segfault when NULL key member is accessed.


5/ Donation

Like my work, request a feature or want to do a donation ?

You may send me a beer, tea, coffee or more via PayPal at paypal TA rapsys TOD eu via:
https://www.paypal.com/myaccount/transfer/homepage/pay

diff -urNp haproxy-2.8.0/include/haproxy/ssl_sock-t.h.orig haproxy-2.8.0/include/haproxy/ssl_sock-t.h
--- haproxy-2.8.0/include/haproxy/ssl_sock-t.h.orig     2023-05-31 16:24:38.000000000 +0200
+++ haproxy-2.8.0/include/haproxy/ssl_sock-t.h  2023-06-19 18:36:50.320176791 +0200
@@ -81,8 +81,10 @@
 #define SSL_GF_OCSP         0x00000004   /* try to open the .ocsp file */
 #define SSL_GF_OCSP_ISSUER  0x00000008   /* try to open the .issuer file if an OCSP file was loaded */
 #define SSL_GF_KEY          0x00000010   /* try to open the .key file to load a private key */
+/* XXX: rapsys: private behaviour */
+#define SSL_GF_PRIVATE      0x00000020   /* try to open the same file name in private key directory */
 
-#define SSL_GF_ALL          (SSL_GF_BUNDLE|SSL_GF_SCTL|SSL_GF_OCSP|SSL_GF_OCSP_ISSUER|SSL_GF_KEY)
+#define SSL_GF_ALL          (SSL_GF_BUNDLE|SSL_GF_SCTL|SSL_GF_OCSP|SSL_GF_OCSP_ISSUER|SSL_GF_KEY|SSL_GF_PRIVATE)
 
 /* ssl_methods versions */
 enum {
@@ -265,6 +267,8 @@ struct ssl_sock_ctx {
 struct global_ssl {
        char *crt_base;             /* base directory path for certificates */
        char *ca_base;              /* base directory path for CAs and CRLs */
+       /* XXX: rapsys: private behaviour */
+       char *key_base;             /* base directory path for private keys */
        char *issuers_chain_path;   /* from "issuers-chain-path" */
        int  skip_self_issued_ca;
 
diff -urNp haproxy-2.8.0/src/cfgparse-ssl.c.orig haproxy-2.8.0/src/cfgparse-ssl.c
--- haproxy-2.8.0/src/cfgparse-ssl.c.orig       2023-05-31 16:24:38.000000000 +0200
+++ haproxy-2.8.0/src/cfgparse-ssl.c    2023-06-19 18:36:50.330176867 +0200
@@ -586,7 +586,7 @@ static int ssl_parse_global_default_dh(c
 
 /*
  * parse "ssl-load-extra-files".
- * multiple arguments are allowed: "bundle", "sctl", "ocsp", "issuer", "all", "none"
+ * multiple arguments are allowed: "bundle", "sctl", "ocsp", "issuer", "all", "none", "key", "private"
  */
 static int ssl_parse_global_extra_files(char **args, int section_type, struct proxy *curpx,
                                        const struct proxy *defpx, const char *file, int line,
@@ -615,6 +615,10 @@ static int ssl_parse_global_extra_files(
                } else if (strcmp("key", args[i]) == 0) {
                        gf |= SSL_GF_KEY;
 
+               /* XXX: rapsys: private behaviour */
+               } else if (strcmp("private", args[i]) == 0) {
+                       gf |= SSL_GF_PRIVATE;
+
                } else if (strcmp("none", args[i]) == 0) {
                        if (gf != SSL_GF_NONE)
                                goto err_alone;
@@ -1986,7 +1990,7 @@ static int ssl_parse_default_server_opti
        return 0;
 }
 
-/* parse the "ca-base" / "crt-base" keywords in global section.
+/* parse the "ca-base" / "crt-base" / "key-base" keywords in global section.
  * Returns <0 on alert, >0 on warning, 0 on success.
  */
 static int ssl_parse_global_ca_crt_base(char **args, int section_type, struct proxy *curpx,
@@ -1995,7 +1999,8 @@ static int ssl_parse_global_ca_crt_base(
 {
        char **target;
 
-       target = (args[0][1] == 'a') ? &global_ssl.ca_base : &global_ssl.crt_base;
+       /* XXX: rapsys: private behaviour */
+       target = (args[0][1] == 'a') ? &global_ssl.ca_base : (args[0][1] == 'r') ? &global_ssl.crt_base : &global_ssl.key_base;
 
        if (too_many_args(1, args, err, NULL))
                return -1;
@@ -2220,8 +2225,10 @@ static struct srv_kw_list srv_kws = { "S
 INITCALL1(STG_REGISTER, srv_register_keywords, &srv_kws);
 
 static struct cfg_kw_list cfg_kws = {ILH, {
+       /* XXX: rapsys: private behaviour */
        { CFG_GLOBAL, "ca-base",  ssl_parse_global_ca_crt_base },
        { CFG_GLOBAL, "crt-base", ssl_parse_global_ca_crt_base },
+       { CFG_GLOBAL, "key-base", ssl_parse_global_ca_crt_base },
        { CFG_GLOBAL, "issuers-chain-path", ssl_load_global_issuers_from_path },
        { CFG_GLOBAL, "maxsslconn", ssl_parse_global_int },
        { CFG_GLOBAL, "ssl-default-bind-options", ssl_parse_default_bind_options },
diff -urNp haproxy-2.8.0/src/ssl_ckch.c.orig haproxy-2.8.0/src/ssl_ckch.c
--- haproxy-2.8.0/src/ssl_ckch.c.orig   2023-05-31 16:24:38.000000000 +0200
+++ haproxy-2.8.0/src/ssl_ckch.c        2023-06-19 18:40:55.651985452 +0200
@@ -319,7 +319,8 @@ end:
  */
 int ssl_sock_load_files_into_ckch(const char *path, struct ckch_data *data, char **err)
 {
-       struct buffer *fp = NULL;
+       /* XXX: rapsys: private behaviour */
+       struct buffer *fp = NULL, *key = NULL;
        int ret = 1;
        struct stat st;
 
@@ -335,12 +336,90 @@ int ssl_sock_load_files_into_ckch(const
        }
 
        if (!chunk_strcpy(fp, path) || (b_data(fp) > MAXPATHLEN)) {
-               memprintf(err, "%s '%s' filename too long'.\n",
+               memprintf(err, "%s '%s' filename too long.\n",
                          err && *err ? *err : "", fp->area);
                ret = 1;
                goto end;
        }
 
+       /* XXX: rapsys: private behaviour */
+       /* Try to load external private key if it wasn't in the PEM
+        * On key-base=somewhere the same filename inside it then loaded if present
+        * on ssl-load-extra-files=private the same filename with parent directory replaced by private or ../private then loaded if present */
+       if ((data->key == NULL) && (global_ssl.key_base || (global_ssl.extra_files & SSL_GF_PRIVATE))) {
+               struct stat st;
+               char *pos = NULL, *ppos = NULL;
+
+               //Alloc trash key buffer
+               if (!(key = alloc_trash_chunk())) {
+                       memprintf(err, "%sCan't allocate memory\n", err && *err ? *err : "");
+                       ret = 1;
+                       goto end;
+               }
+
+               //Search / before filename
+               if ((pos = strrchr(fp->area, '/'))) {
+                       //Only preprend directory stuff without key base directory
+                       if (!global_ssl.key_base) {
+                               //Copy fp in key
+                               if (!chunk_cpy(key, fp)) {
+                                       memprintf(err, "%s '%s' filename too long.\n",
+                                                 err && *err ? *err : "", fp->area);
+                                       ret = 1;
+                                       goto end;
+                               }
+
+                               //Trash / before filename
+                               key->area[pos - fp->area] = '\0';
+
+                               //Search / before parent directory
+                               if ((ppos = strrchr(key->area, '/'))) {
+                                       //Truncate key before parent directory
+                                       key->area[ppos - key->area + 1] = '\0';
+                                       //Set key length
+                                       b_set_data(key, ppos - key->area + 1);
+                               //Without parent directory
+                               } else {
+                                       //Trash key
+                                       chunk_reset(key);
+                               }
+                       }
+               }
+
+               //Append private directory name
+               if (!chunk_strcat(key, global_ssl.key_base ? global_ssl.key_base : (pos ? "private/" : "../private/")) || (b_data(key) > MAXPATHLEN)) {
+                       memprintf(err, "%s '%s' filename too long.\n",
+                                       err && *err ? *err : "", key->area);
+                       ret = 1;
+                       goto end;
+               }
+
+               //Append / if missing
+               if (key->area[key->data-1] != '/' && (!chunk_memcat(key, (char *)&"/", 1) || (b_data(key) > MAXPATHLEN))) {
+                       memprintf(err, "%s '%s' filename too long.\n",
+                                       err && *err ? *err : "", key->area);
+                       ret = 1;
+                       goto end;
+               }
+
+               //Append filename
+               if (!chunk_strcat(key, pos ? pos + 1 : fp->area) || (b_data(key) > MAXPATHLEN)) {
+                       memprintf(err, "%s '%s' filename too long.\n",
+                                       err && *err ? *err : "", key->area);
+                       ret = 1;
+                       goto end;
+               }
+
+               //Check if key exists
+               if (stat(key->area, &st) == 0) {
+                       if (ssl_sock_load_key_into_ckch(key->area, NULL, data, err)) {
+                               memprintf(err, "%s '%s' is present but cannot be read or parsed.\n",
+                                         err && *err ? *err : "", key->area);
+                               goto end;
+                       }
+               }
+       }
+
        /* remove the ".crt" extension */
        if (global_ssl.extra_files_noext) {
                char *ext;
@@ -364,10 +443,9 @@ int ssl_sock_load_files_into_ckch(const
                        memprintf(err, "%sNo Private Key found in '%s'.\n", err && *err ? *err : "", fp->area);
                        goto end;
                }
-
                /* try to load an external private key if it wasn't in the PEM */
                if (!chunk_strcat(fp, ".key") || (b_data(fp) > MAXPATHLEN)) {
-                       memprintf(err, "%s '%s' filename too long'.\n",
+                       memprintf(err, "%s '%s' filename too long.\n",
                                  err && *err ? *err : "", fp->area);
                        ret = 1;
                        goto end;
@@ -375,7 +453,7 @@ int ssl_sock_load_files_into_ckch(const
 
                if (stat(fp->area, &st) == 0) {
                        if (ssl_sock_load_key_into_ckch(fp->area, NULL, data, err)) {
-                               memprintf(err, "%s '%s' is present but cannot be read or parsed'.\n",
+                               memprintf(err, "%s '%s' is present but cannot be read or parsed.\n",
                                          err && *err ? *err : "", fp->area);
                                goto end;
                        }
@@ -385,11 +463,17 @@ int ssl_sock_load_files_into_ckch(const
                        memprintf(err, "%sNo Private Key found in '%s'.\n", err && *err ? *err : "", fp->area);
                        goto end;
                }
+
                /* remove the added extension */
                *(fp->area + fp->data - strlen(".key")) = '\0';
                b_sub(fp, strlen(".key"));
        }
 
+       /* XXX: rapsys: private behaviour */
+       if (data->key == NULL) {
+               memprintf(err, "%sNo Private Key found for '%s'.\n", err && *err ? *err : "", path);
+               goto end;
+       }
 
        if (!X509_check_private_key(data->cert, data->key)) {
                memprintf(err, "%sinconsistencies between private key and certificate loaded '%s'.\n",
@@ -403,7 +487,7 @@ int ssl_sock_load_files_into_ckch(const
                struct stat st;
 
                if (!chunk_strcat(fp, ".sctl") || b_data(fp) > MAXPATHLEN) {
-                       memprintf(err, "%s '%s' filename too long'.\n",
+                       memprintf(err, "%s '%s' filename too long.\n",
                                  err && *err ? *err : "", fp->area);
                        ret = 1;
                        goto end;
@@ -411,7 +495,7 @@ int ssl_sock_load_files_into_ckch(const
 
                if (stat(fp->area, &st) == 0) {
                        if (ssl_sock_load_sctl_from_file(fp->area, NULL, data, err)) {
-                               memprintf(err, "%s '%s.sctl' is present but cannot be read or parsed'.\n",
+                               memprintf(err, "%s '%s.sctl' is present but cannot be read or parsed.\n",
                                          err && *err ? *err : "", fp->area);
                                ret = 1;
                                goto end;
@@ -428,7 +512,7 @@ int ssl_sock_load_files_into_ckch(const
                struct stat st;
 
                if (!chunk_strcat(fp, ".ocsp") || b_data(fp) > MAXPATHLEN) {
-                       memprintf(err, "%s '%s' filename too long'.\n",
+                       memprintf(err, "%s '%s' filename too long.\n",
                                  err && *err ? *err : "", fp->area);
                        ret = 1;
                        goto end;
@@ -452,7 +536,7 @@ int ssl_sock_load_files_into_ckch(const
                        struct stat st;
 
                        if (!chunk_strcat(fp, ".issuer") || b_data(fp) > MAXPATHLEN) {
-                               memprintf(err, "%s '%s' filename too long'.\n",
+                               memprintf(err, "%s '%s' filename too long.\n",
                                          err && *err ? *err : "", fp->area);
                                ret = 1;
                                goto end;
@@ -465,7 +549,7 @@ int ssl_sock_load_files_into_ckch(const
                                }
 
                                if (X509_check_issued(data->ocsp_issuer, data->cert) != X509_V_OK) {
-                                       memprintf(err, "%s '%s' is not an issuer'.\n",
+                                       memprintf(err, "%s '%s' is not an issuer.\n",
                                                  err && *err ? *err : "", fp->area);
                                        ret = 1;
                                        goto end;
@@ -488,6 +572,8 @@ end:
        if (ret != 0)
                ssl_sock_free_cert_key_and_chain_contents(data);
 
+       /* XXX: rapsys: private behaviour */
+       free_trash_chunk(key);
        free_trash_chunk(fp);
 
        return ret;
@@ -832,7 +918,7 @@ int ssl_sock_load_issuer_file_into_ckch(
 
        issuer = PEM_read_bio_X509_AUX(in, NULL, NULL, NULL);
        if (!issuer) {
-               memprintf(err, "%s'%s' cannot be read or parsed'.\n",
+               memprintf(err, "%s'%s' cannot be read or parsed.\n",
                          err && *err ? *err : "", path);
                goto end;
        }
diff -urNp haproxy-2.8.0/src/ssl_crtlist.c.orig haproxy-2.8.0/src/ssl_crtlist.c
--- haproxy-2.8.0/src/ssl_crtlist.c.orig        2023-05-31 16:24:38.000000000 +0200
+++ haproxy-2.8.0/src/ssl_crtlist.c     2023-06-19 18:36:50.330176867 +0200
@@ -750,9 +750,10 @@ int crtlist_load_cert_dir(char *path, st
                        struct dirent *de = de_list[i];
 
                        end = strrchr(de->d_name, '.');
+                       /* XXX: rapsys: private behaviour */
                        if (end && (de->d_name[0] == '.' ||
                                    strcmp(end, ".issuer") == 0 || strcmp(end, ".ocsp") == 0 ||
-                                   strcmp(end, ".sctl") == 0 || strcmp(end, ".key") == 0))
+                                   strcmp(end, ".sctl") == 0 || strcmp(end, ".key") == 0 || strcmp(end, ".pem") == 0))
                                goto ignore_entry;
 
                        snprintf(fp, sizeof(fp), "%s/%s", path, de->d_name);
```

**Comment by a-denoyelle** [comment]
In fact for now PROXY protocol is incompatible with QUIC. What is really unfortunate here is that you encounter a crash, instead we should generate a proper message on haproxy startup to warn about this incompatibility.

**Comment by capflam** [comment]
It is fixed now.

**Comment by capflam** [comment]
Only backported as far as 2.8. On older versions, the fix must be adapted. I guess we can wait that someone asks for it.
