### ISSUE TITLE
QUIC - Assert failure in quic_conn_release

### ISSUE THREAD

**Issue by Tristan971** [haproxy/haproxy#2243]
### Detailed Description of the Problem

Crash while serving QUIC traffic

### Expected Behavior

no crash

### Steps to Reproduce the Behavior

1. Serve QUIC traffic
2. good question

### What is your configuration?

```haproxy
as usual
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.9-dev2-6492f1f+mangadex-20d8fd4 2023-08-09T13:38+00:00 - https://haproxy.org/
Status: development branch - not safe for use in production.
Known bugs: https://github.com/haproxy/haproxy/issues?q=is:issue+is:open
Running on: Linux 5.15.85-1-pve #1 SMP PVE 5.15.85-1 (2023-02-01T00:00Z) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -ggdb3 -gdwarf-4 -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wnull-dereference -fwrapv -Wno-unknown-warning-option -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment -DMAX_SESS_STKCTR=5
  OPTIONS = USE_LIBCRYPT=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_TFO=1 USE_NS=1 USE_SYSTEMD=1 USE_QUIC=1 USE_PROMEX=1 USE_STATIC_PCRE2=1 USE_PCRE2=1 USE_PCRE2_JIT=1
  DEBUG   = -DDEBUG_MEMORY_POOLS -DDEBUG_STRICT

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION +QUIC -QUIC_OPENSSL_COMPAT +RT +SHM_OPEN +SLZ +SSL -STATIC_PCRE +STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=8).
Built with OpenSSL version : OpenSSL 1.1.1u+quic-mangadex-20d8fd4  9 Aug 2023
Running on OpenSSL version : OpenSSL 1.1.1u+quic-mangadex-20d8fd4  9 Aug 2023
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.4.4
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.40 2022-04-14
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with clang compiler version 16.0.6 (++20230610113348+7cbf1a259152-1~exp1~20230610233446.99)

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
       quic : mode=HTTP  side=FE     mux=QUIC  flags=HTX|NO_UPG|FRAMED
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=

Available services : prometheus-exporter
Available filters :
        [BWLIM] bwlim-in
        [BWLIM] bwlim-out
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
        [TRACE] trace
```

### Last Outputs and Backtraces

```plain
Program terminated with signal SIGILL, Illegal instruction.
#0  0x000055ea88732daa in quic_conn_release (qc=qc@entry=0x7f3f25e63dc0) at src/quic_conn.c:1397
1397    src/quic_conn.c: No such file or directory.
[Current thread is 1 (Thread 0x7f3f29f2c640 (LWP 504561))]
(gdb) t a a bt full

Thread 3 (Thread 0x7f3f30a02640 (LWP 504560)):
#0  0x00007f3f30dc2fde in epoll_wait () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#1  0x000055ea8870b957 in _do_poll (p=<optimized out>, exp=34934, wake=0) at src/ev_epoll.c:232
        timeout = 4
        updt_idx = <optimized out>
        fd = <optimized out>
        old_fd = <optimized out>
        wait_time = 4
        status = <optimized out>
        count = <optimized out>
#2  0x000055ea888a2b8c in run_poll_loop () at src/haproxy.c:3041
        _ = {
          func = 0x55ea88c0307c "run_poll_loop",
          file = 0x55ea88c0308a "src/haproxy.c",
          line = 2997,
          what = 1 '\001',
          arg8 = 0 '\000',
          arg32 = 0
        }
        wake = <optimized out>
        next = 738454656
#3  0x000055ea888a710f in run_thread_poll_loop (data=<optimized out>) at src/haproxy.c:3165
        init_left = 0
        init_mutex = {
          __data = {
            __lock = 0,
            __count = 0,
            __owner = 0,
            __nusers = 0,
            __kind = 0,
            __spins = 0,
            __elision = 0,
            __list = {
              __prev = 0x0,
              __next = 0x0
            }
          },
          __size = '\000' <repeats 39 times>,
          __align = 0
        }
        init_cond = {
          __data = {
            {
              __wseq = 4,
              __wseq32 = {
                __low = 4,
                __high = 0
              }
            },
            {
              __g1_start = 2,
              __g1_start32 = {
                __low = 2,
                __high = 0
              }
            },
            __g_refs = {0, 0},
            __g_size = {0, 0},
            __g1_orig_size = 4,
            __wrefs = 0,
            __g_signals = {0, 0}
          },
          __size = "\004\000\000\000\000\000\000\000\002", '\000' <repeats 23 times>, "\004", '\000' <repeats 14 times>,
          __align = 4
        }
        warn_fail = 0
        warn_fail = 0
        ptaf = <optimized out>
        ptif = <optimized out>
        ptdf = <optimized out>
        ptff = <optimized out>
#4  0x00007f3f30d31b43 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#5  0x00007f3f30dc3a00 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.

Thread 2 (Thread 0x7f3f30a0e200 (LWP 504559)):
#0  0x00007f3f30dc2fde in epoll_wait () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#1  0x000055ea8870b957 in _do_poll (p=<optimized out>, exp=34935, wake=0) at src/ev_epoll.c:232
        timeout = 2
        updt_idx = <optimized out>
        fd = <optimized out>
        old_fd = <optimized out>
        wait_time = 2
        status = <optimized out>
        count = <optimized out>
#2  0x000055ea888a2b8c in run_poll_loop () at src/haproxy.c:3041
        _ = {
          func = 0x55ea88c0307c "run_poll_loop",
          file = 0x55ea88c0308a "src/haproxy.c",
          line = 2997,
          what = 1 '\001',
          arg8 = 0 '\000',
          arg32 = 0
        }
        wake = <optimized out>
        next = -1971783760
#3  0x000055ea888a710f in run_thread_poll_loop (data=<optimized out>) at src/haproxy.c:3165
        init_left = 0
        init_mutex = {
          __data = {
            __lock = 0,
            __count = 0,
            __owner = 0,
            __nusers = 0,
            __kind = 0,
            __spins = 0,
            __elision = 0,
            __list = {
              __prev = 0x0,
              __next = 0x0
            }
          },
          __size = '\000' <repeats 39 times>,
          __align = 0
        }
        init_cond = {
          __data = {
            {
              __wseq = 4,
              __wseq32 = {
                __low = 4,
                __high = 0
              }
            },
            {
              __g1_start = 2,
              __g1_start32 = {
                __low = 2,
                __high = 0
              }
            },
            __g_refs = {0, 0},
            __g_size = {0, 0},
            __g1_orig_size = 4,
            __wrefs = 0,
            __g_signals = {0, 0}
          },
          __size = "\004\000\000\000\000\000\000\000\002", '\000' <repeats 23 times>, "\004", '\000' <repeats 14 times>,
          __align = 4
        }
        warn_fail = 0
        warn_fail = 0
        ptaf = <optimized out>
        ptif = <optimized out>
        ptdf = <optimized out>
        ptff = <optimized out>
#4  0x000055ea888a6174 in main (argc=<optimized out>, argv=0x7fff17bf26b8) at src/haproxy.c:3837
        limit = {
          rlim_cur = 18446744073709551615,
          rlim_max = 18446744073709551615
        }
        pidfd = 44
        retry = <optimized out>
        err = <optimized out>
        intovf = <optimized out>

Thread 1 (Thread 0x7f3f29f2c640 (LWP 504561)):
#0  0x000055ea88732daa in quic_conn_release (qc=qc@entry=0x7f3f25e63dc0) at src/quic_conn.c:1397
        cc_qc = <optimized out>
        node = <optimized out>
        pkt = <optimized out>
        pktback = <optimized out>
#1  0x000055ea88733045 in quic_conn_io_cb (t=t@entry=0x7f3f246d38b0, context=context@entry=0x7f3f25e63dc0, state=<optimized out>) at src/quic_conn.c:974
        qc = <optimized out>
        buf = <optimized out>
        st = <optimized out>
        ret = <optimized out>
#2  0x000055ea888d87cd in run_tasks_from_lists (budgets=budgets@entry=0x7f3f29f21290) at src/task.c:596
        _ = {
          func = 0x55ea88c0db47 "run_tasks_from_lists",
          file = 0x55ea88c0dab2 "src/task.c",
          line = 658,
          what = 5 '\005',
          arg8 = 0 '\000',
          arg32 = 0
        }
        tl_queues = 0x55ea88ff9c10 <ha_thread_ctx+1168>
        budget_mask = 15 '\017'
        profile_entry = 0x0
        done = 1
        queue = 0
        t = 0x7f3f246d38b0
        process = 0x55ea88732e40 <quic_conn_io_cb>
        ctx = 0x7f3f25e63dc0
        state = 83
#3  0x000055ea888d913a in process_runnable_tasks () at src/task.c:876
        max = {105, 80, 0, 0}
        tt = 0x55ea88ff9b80 <ha_thread_ctx+1024>
        default_weights = {64, 48, 16, 1}
        heavy_queued = 1
        max_processed = 186
        max_total = <optimized out>
        queue = 4
        budget = 80
        grq = <optimized out>
        lrq = <optimized out>
        gpicked = <optimized out>
        lpicked = <optimized out>
        t = <optimized out>
        tmp_list = <optimized out>
#4  0x000055ea888a2bc2 in run_poll_loop () at src/haproxy.c:2966
        _ = {
          func = 0x55ea88c0307c "run_poll_loop",
          file = 0x55ea88c0308a "src/haproxy.c",
          line = 2997,
          what = 1 '\001',
          arg8 = 0 '\000',
          arg32 = 0
        }
        wake = <optimized out>
        next = <optimized out>
#5  0x000055ea888a710f in run_thread_poll_loop (data=<optimized out>) at src/haproxy.c:3165
        init_left = 0
        init_mutex = {
          __data = {
            __lock = 0,
            __count = 0,
            __owner = 0,
            __nusers = 0,
            __kind = 0,
            __spins = 0,
            __elision = 0,
            __list = {
              __prev = 0x0,
              __next = 0x0
            }
          },
          __size = '\000' <repeats 39 times>,
          __align = 0
        }
        init_cond = {
          __data = {
            {
              __wseq = 4,
              __wseq32 = {
                __low = 4,
                __high = 0
              }
            },
            {
              __g1_start = 2,
              __g1_start32 = {
                __low = 2,
                __high = 0
              }
            },
            __g_refs = {0, 0},
            __g_size = {0, 0},
            __g1_orig_size = 4,
            __wrefs = 0,
            __g_signals = {0, 0}
          },
          __size = "\004\000\000\000\000\000\000\000\002", '\000' <repeats 23 times>, "\004", '\000' <repeats 14 times>,
          __align = 4
        }
        warn_fail = 0
        warn_fail = 0
        ptaf = <optimized out>
        ptif = <optimized out>
        ptdf = <optimized out>
        ptff = <optimized out>
#6  0x00007f3f30d31b43 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#7  0x00007f3f30dc3a00 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
```

### Additional Information

Regression is somewhere between 624979c and 6492f1f. Crashes consistently in <5 minutes here.

**Comment by haproxyFred** [comment]
Hello. Thank you for this report. In fact they are several issues. Still investigating.

**Comment by haproxyFred** [comment]
I have just pushed some bug fixes in this branch: https://github.com/haproxytech/quic-dev/commits/fle-quic-bugs which fix your issue and others.

**Comment by haproxyFred** [comment]
Tristan, please note that fle-quic-bugs branch has been merged into master.

**Comment by haproxyFred** [comment]
This issue should be fixed by this commit in master : https://github.com/haproxy/haproxy/commit/1ab6126ca79ed0f7406430b0be566d900e84d3a3

(forgot to add a reference to this issue in the commit message).

**Comment by Tristan971** [comment]
Thanks! I'll give it a try in a little while 👍

**Comment by Tristan971** [comment]
Can confirm that the issue is resolved on my end with https://github.com/haproxy/haproxy/commit/7f80d518124af10a5f8734bcf801dffc49ee2a10 🫡
