### ISSUE TITLE
musl  crashes 

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#2274]
### Detailed Description of the Problem

https://github.com/chipitsine/haproxy/actions/runs/6039686517/job/16388909333#step:12:10

```
core.1ef6ba30135b.haproxy.1693497777.4431
GNU gdb (GDB) 13.1
  Copyright (C) 2023 Free Software Foundation, Inc.
  License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
  This is free software: you are free to change and redistribute it.
  There is NO WARRANTY, to the extent permitted by law.
  Type "show copying" and "show warranty" for details.
  This GDB was configured as "x86_64-alpine-linux-musl".
  Type "show configuration" for configuration details.
  For bug reporting instructions, please see:
  <https://www.gnu.org/software/gdb/bugs/>.
  Find the GDB manual and other documentation resources online at:
      <http://www.gnu.org/software/gdb/documentation/>.
  
  For help, type "help".
  Type "apropos word" to search for commands related to "word"...
  Reading symbols from ./haproxy...
  
  warning: Can't open file /dev/shm/haproxy_startup_logs_4431 (deleted) during file-backed mapping note processing
  [New LWP 4431]
  [New LWP 4435]
  Core was generated by `/__w/haproxy/haproxy/haproxy -d -dM -f /tmp/haregtests-2023-08-31_16-02-09.FCHi'.
  Program terminated with signal SIGILL, Illegal instruction.
  #0  0x000055a3d4b6b565 in __pool_free (pool=<optimized out>, 
      ptr=<optimized out>) at src/pool.c:872
  872		POOL_DEBUG_CHECK_MARK(pool, ptr);
  [Current thread is 1 (LWP 4431)]
  
  Thread 2 (LWP 4435):
  #0  __cp_end () at src/thread/x86_64/syscall_cp.s:29
  No locals.
  #1  0x00007f500e0cf0fe in __syscall_cp_c (nr=281, u=<optimized out>, v=<optimized out>, w=<optimized out>, x=<optimized out>, y=<optimized out>, z=8) at src/thread/pthread_cancel.c:33
          self = 0x7f5003709b30
          r = <optimized out>
          st = <optimized out>
  #2  0x00007f500e098ed4 in epoll_pwait (fd=13, ev=0x7f5002e9c0d0, cnt=200, to=to@entry=60000, sigs=sigs@entry=0x0) at src/linux/epoll.c:28
          r = <optimized out>
  #3  0x00007f500e098f1f in epoll_wait (fd=<optimized out>, ev=<optimized out>, cnt=<optimized out>, to=to@entry=60000) at src/linux/epoll.c:37
  No locals.
  #4  0x000055a3d49c8e60 in _do_poll (p=<optimized out>, exp=<optimized out>, wake=<optimized out>) at src/ev_epoll.c:232
          timeout = 60000
          status = <optimized out>
          fd = <optimized out>
          count = <optimized out>
          updt_idx = <optimized out>
          wait_time = 60000
          old_fd = <optimized out>
  #5  0x000055a3d4b213eb in run_poll_loop () at src/haproxy.c:3044
          next = <optimized out>
          wake = <optimized out>
          __func__ = <optimized out>
  #6  0x000055a3d4b21a69 in run_thread_poll_loop (data=<optimized out>) at src/haproxy.c:3168
          ptaf = <optimized out>
          ptif = 0x55a3d4c9a4f0 <per_thread_init_list>
          ptdf = <optimized out>
          ptff = <optimized out>
          init_left = 0
          init_mutex = {__u = {__i = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, __vi = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, __p = {0x0, 0x0, 0x0, 0x0, 0x0}}}
          init_cond = {__u = {__i = {0 <repeats 12 times>}, __vi = {0 <repeats 12 times>}, __p = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0}}}
  #7  0x00007f500e0cfbd2 in start (p=0x7f5003707070) at src/thread/pthread_create.c:207
          args = 0x7f5003707070
          state = <optimized out>
  #8  0x00007f500e0d1f40 in __clone () at src/thread/x86_64/clone.s:22
  No locals.
  Backtrace stopped: frame did not save the PC
  
  Thread 1 (LWP 4431):
  #0  0x000055a3d4b6b565 in __pool_free (pool=<optimized out>, ptr=<optimized out>) at src/pool.c:872
          __p = <optimized out>
          __i = <optimized out>
          caller = <optimized out>
  #1  0x000055a3d4afa325 in conn_free (conn=0x7f500d835690) at src/connection.c:575
          __ptr = <optimized out>
          tlv = <optimized out>
          tlv_back = 0x7f500d835720
  #2  0x000055a3d4a51fb5 in h1_process (h1c=h1c@entry=0x7f500d835780) at src/mux_h1.c:3639
          conn = 0x7f500d835690
          __FUNCTION__ = "h1_process"
  #3  0x000055a3d4a596d6 in h1_io_cb (t=0x7f5003733f60, ctx=0x7f500d835780, state=<optimized out>) at src/mux_h1.c:3690
          conn = 0x7f500d835690
          tl = 0x7f5003733f60
          conn_in_list = 0
          h1c = 0x7f500d835780
          ret = <optimized out>
          __FUNCTION__ = "h1_io_cb"
  #4  0x000055a3d4b53ca0 in run_tasks_from_lists (budgets=<optimized out>) at src/task.c:596
          process = <optimized out>
          tl_queues = 0x55a3d4ef9d90 <ha_thread_ctx+144>
          t = 0x7f5003733f60
          budget_mask = 15 '\017'
          profile_entry = 0x0
          done = 0
          queue = 0
          state = <optimized out>
          ctx = <optimized out>
          __func__ = <optimized out>
  #5  0x000055a3d4b54773 in process_runnable_tasks () at src/task.c:876
          tt = 0x55a3d4ef9d00 <ha_thread_ctx>
          lrq = <optimized out>
          grq = <optimized out>
          t = <optimized out>
          max = {185, 0, 0, 0}
          max_total = <optimized out>
          tmp_list = <optimized out>
          queue = <optimized out>
          max_processed = <optimized out>
          lpicked = <optimized out>
          gpicked = <optimized out>
          heavy_queued = 1
          budget = <optimized out>
          not_done_yet = <optimized out>
  #6  0x000055a3d4b2142c in run_poll_loop () at src/haproxy.c:2969
          next = <optimized out>
          wake = <optimized out>
          __func__ = <optimized out>
  #7  0x000055a3d4b21a69 in run_thread_poll_loop (data=<optimized out>) at src/haproxy.c:3168
          ptaf = <optimized out>
          ptif = 0x55a3d4c9a4f0 <per_thread_init_list>
          ptdf = <optimized out>
          ptff = <optimized out>
          init_left = 0
          init_mutex = {__u = {__i = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, __vi = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, __p = {0x0, 0x0, 0x0, 0x0, 0x0}}}
          init_cond = {__u = {__i = {0 <repeats 12 times>}, __vi = {0 <repeats 12 times>}, __p = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0}}}
  #8  0x000055a3d49c5880 in main (argc=<optimized out>, argv=<optimized out>) at src/haproxy.c:3858
          err = <optimized out>
          retry = <optimized out>
          limit = {rlim_cur = [10](https://github.com/chipitsine/haproxy/actions/runs/6039686517/job/16388909333#step:12:11)48576, rlim_max = 1048576}
          pidfd = <optimized out>
          intovf = <optimized out>
          msg = <optimized out>
```

### Expected Behavior

not to crash

### Steps to Reproduce the Behavior

expand "show coredump" in musl workflow

### What is your configuration?

```haproxy
no configuration. caught in CI
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.9-dev4-2e51a0077eb9 2023/08/31 - https://haproxy.org/
Status: development branch - not safe for use in production.
Known bugs: https://github.com/haproxy/haproxy/issues?q=is:issue+is:open
Running on: Linux 5.15.0-1041-azure #48-Ubuntu SMP Tue Jun 20 20:34:08 UTC 2023 x86_64
Build options :
  TARGET  = linux-musl
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -ggdb3 -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_OPENSSL=1 USE_LUA=1 USE_PROMEX=1 USE_PCRE2=1 USE_PCRE2_JIT=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 -BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION -QUIC -QUIC_OPENSSL_COMPAT +RT +SHM_OPEN +SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 -SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=2).
Built with OpenSSL version : OpenSSL 3.1.2 1 Aug 2023
Running on OpenSSL version : OpenSSL 3.1.2 1 Aug 2023
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
OpenSSL providers loaded : default
Built with Lua version : Lua 5.3.6
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.42 2022-12-11
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 12.2.1 20220924

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[BWLIM] bwlim-in
	[BWLIM] bwlim-out
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
```

**Comment by wtarreau** [comment]
I can't find it, maybe I'm not looking at the right place. Also, do you know if it only happened once or is reproducible ?

**Comment by chipitsine** [comment]
it crashes from time to time.  the report above is from my fork. however ...

![image](https://github.com/haproxy/haproxy/assets/2217296/ba990c7e-21a4-42b3-8649-dd6069e2d129)


I'll send a patch to highlight "core dumps" if there's anything caught

![image](https://github.com/haproxy/haproxy/assets/2217296/ce131b52-53ee-4382-9903-bdc713065636)

**Comment by wtarreau** [comment]
Thanks Ilya. I've found it in #2275 and could reproduce and confirm the trivial fix works. I'm pushing it now.
