### ISSUE TITLE
freebsd (cirrus-ci) crash

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#2275]
### Detailed Description of the Problem

```
GNU gdb (GDB) 13.1 [GDB v13.1 for FreeBSD]
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-portbld-freebsd13.2".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./haproxy...
[New LWP 100145]
[New LWP 101195]
warning: Could not load shared library symbols for [vdso].
Do you need "set solib-search-path" or "set sysroot"?
Core was generated by `/tmp/cirrus-ci-build/haproxy -d -dM -f /tmp/haregtests-2023-08-31_18-50-41.1xAcI'.
Program terminated with signal SIGILL, Illegal instruction.
Privileged opcode.
#0  0x0000000000466e26 in __pool_free (pool=<optimized out>, 
    ptr=<optimized out>) at src/pool.c:872
872		POOL_DEBUG_CHECK_MARK(pool, ptr);
[Current thread is 1 (LWP 100145)]
Thread 2 (LWP 101195):
#0  _kevent () at _kevent.S:4
No locals.
#1  0x0000000825be62d3 in __thr_kevent (kq=12, changelist=0x0, nchanges=0, eventlist=0x83e390a80, nevents=200, timeout=0x83811cee0) at /usr/src/lib/libthr/thread/thr_syscalls.c:400
        curthread = 0x8294aa300
        ret = <optimized out>
#2  0x00000000002d9c69 in _do_poll (p=<optimized out>, exp=0, wake=0) at src/ev_kqueue.c:180
        timeout = 60000
        timeout_ts = {tv_sec = 60, tv_nsec = 0}
        changes = <optimized out>
        updt_idx = <optimized out>
        fd = 200
        old_fd = <optimized out>
        wait_time = 60000
        status = <optimized out>
        count = <optimized out>
#3  0x000000000041a55c in run_poll_loop () at src/haproxy.c:3044
        _ = {func = 0x252d14 "run_poll_loop", file = 0x2583a1 "src/haproxy.c", line = 3000, what = 1 '\001', arg8 = 0 '\000', arg32 = 0}
        wake = <optimized out>
        next = 0
#4  0x000000000041e861 in run_thread_poll_loop (data=<optimized out>) at src/haproxy.c:3168
        init_left = 0
        init_mutex = 0x82c7c6288
        init_cond = 0x82cf22e00
        warn_fail = 0
        ptaf = <optimized out>
        ptif = 0x4d3e60 <per_thread_init_list>
        ptdf = <optimized out>
        ptff = <optimized out>
#5  0x0000000825bdaa7a in thread_start (curthread=0x8294aa300) at /usr/src/lib/libthr/thread/thr_create.c:292
        set = {__bits = {0, 0, 0, 0}}
#6  0x0000000000000000 in ?? ()
No symbol table info available.
Backtrace stopped: Cannot access memory at address 0x83811d000
Thread 1 (LWP 100145):
#0  0x0000000000466e26 in __pool_free (pool=<optimized out>, ptr=<optimized out>) at src/pool.c:872
        __p = <optimized out>
        __i = <optimized out>
        caller = <optimized out>
#1  0x00000000003f614c in conn_free (conn=conn@entry=0x83d71d000) at src/connection.c:575
        tlv_back = <optimized out>
        tlv = 0x8294e54a0
#2  0x000000000035164d in h1_release (h1c=h1c@entry=0x8294be400) at src/mux_h1.c:1077
        _ = {func = 0x26e657 "h1_release", file = 0x24ad85 "src/mux_h1.c", line = 1045, what = 1 '\001', arg8 = 0 '\000', arg32 = 0}
        conn = <optimized out>
#3  0x000000000034fdf0 in h1_process (h1c=h1c@entry=0x8294be400) at src/mux_h1.c:3639
        conn = 0x83d71d000
#4  0x000000000034eb7a in h1_io_cb (t=0x82cf3b140, ctx=0x8294be400, state=<optimized out>) at src/mux_h1.c:3690
        ret = 1
        conn = 0x83d71d000
        conn_in_list = 0
        tl = <optimized out>
        h1c = <optimized out>
#5  0x000000000044f1ee in run_tasks_from_lists (budgets=budgets@entry=0x820bc96a0) at src/task.c:596
        _ = {func = 0x26afad "run_tasks_from_lists", file = 0x262add "src/task.c", line = 658, what = 5 '\005', arg8 = 0 '\000', arg32 = 0}
        tl_queues = 0x820bc96a8
        budget_mask = 15 '\017'
        profile_entry = 0x0
        done = 0
        queue = 0
        t = 0x82cf3b140
        process = <optimized out>
        ctx = <optimized out>
        state = 384
#6  0x000000000044fbf9 in process_runnable_tasks () at src/task.c:876
        max = {185, 0, 0, 0}
        tt = 0x6fe600 <ha_thread_ctx>
        heavy_queued = 1
        default_weights = {64, 48, 16, 1}
        max_processed = 186
        queue = 4
        budget = 0
        max_total = <optimized out>
        grq = <optimized out>
        lrq = <optimized out>
        gpicked = <optimized out>
        lpicked = <optimized out>
        t = <optimized out>
        tmp_list = <optimized out>
#7  0x000000000041a5a7 in run_poll_loop () at src/haproxy.c:2969
        _ = {func = 0x252d14 "run_poll_loop", file = 0x2583a1 "src/haproxy.c", line = 3000, what = 1 '\001', arg8 = 0 '\000', arg32 = 0}
        wake = <optimized out>
        next = <optimized out>
#8  0x000000000041e861 in run_thread_poll_loop (data=<optimized out>) at src/haproxy.c:3168
        init_left = 0
        init_mutex = 0x82c7c6288
        init_cond = 0x82cf22e00
        warn_fail = 0
        ptaf = <optimized out>
        ptif = 0x4d3e60 <per_thread_init_list>
        ptdf = <optimized out>
        ptff = <optimized out>
#9  0x000000000041db48 in main (argc=<optimized out>, argv=0x820bc9b00) at src/haproxy.c:3858
        limit = {rlim_cur = 234963, rlim_max = 234963}
        pidfd = -1
        retry = <optimized out>
        err = <optimized out>
        intovf = <optimized out>
(gdb) 
```

### Expected Behavior

not to crash

### Steps to Reproduce the Behavior

seen on cirrus-ci recently

### What is your configuration?

```haproxy
no config, caught in CI
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.9-dev4 2023/08/25 - https://haproxy.org/
Status: development branch - not safe for use in production.
Known bugs: https://github.com/haproxy/haproxy/issues?q=is:issue+is:open
Running on: FreeBSD 13.2-RELEASE FreeBSD 13.2-RELEASE releng/13.2-n254617-525ecfdad597 GENERIC amd64
Build options :
  TARGET  = freebsd
  CPU     = generic
  CC      = clang
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wnull-dereference -fwrapv -Wno-unknown-warning-option -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment -Werror
  OPTIONS = USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_PCRE=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS
Feature list : -51DEGREES +ACCEPT4 -BACKTRACE +CLOSEFROM +CPU_AFFINITY -CRYPT_H -DEVICEATLAS -DL -ENGINE -EPOLL -EVPORTS +GETADDRINFO +KQUEUE -LIBATOMIC +LIBCRYPT -LINUX_CAP -LINUX_SPLICE -LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING -NETFILTER -NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_WOLFSSL -OT +PCRE -PCRE2 -PCRE2_JIT -PCRE_JIT +POLL -PRCTL +PROCCTL -PROMEX -PTHREAD_EMULATION -QUIC -QUIC_OPENSSL_COMPAT -RT +SHM_OPEN -SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 -SYSTEMD -TFO +THREAD -THREAD_DUMP +TPROXY -WURFL +ZLIB
Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200
Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=2).
Built with OpenSSL version : OpenSSL 1.1.1v  1 Aug 2023
Running on OpenSSL version : OpenSSL 1.1.1v  1 Aug 2023
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.6
Built with zlib version : 1.2.13
Running on zlib version : 1.2.13
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_BINDANY IPV6_BINDANY
Built with PCRE version : 8.45 2021-06-15
Running on PCRE version : 8.45 2021-06-15
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes
Built with clang compiler version 14.0.5 (https://github.com/llvm/llvm-project.git llvmorg-14.0.5-0-gc12386ae247c)
Available polling systems :
     kqueue : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use kqueue.
Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
Available services : none
Available filters :
	[BWLIM] bwlim-in
	[BWLIM] bwlim-out
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
```

**Comment by wtarreau** [comment]
So in short we're facing memory corruption bugs both on musl and freebsd. I'm unsure what causes these.

**Comment by wtarreau** [comment]
Oh there's indeed a bug there when the object is exactly 128 with the TLV stuff, so the first failing regtests we saw was actually not a false positive, despite not being reproducible elsewhere. Look below:
```
$ git show f773ef721ca6424c25fe7da77a92f724572d518f^|grep -B1 -A1 HA_PP2_TLV_VALUE_128
+#define HA_PP2_AUTHORITY_MAX 255  /* Maximum length of an authority TLV */
+#define HA_PP2_TLV_VALUE_128 128  /* E.g., accomodate unique IDs (128 B) */
+#define HA_PP2_TLV_VALUE_256 256  /* E.g., accomodate authority TLVs (currently, <= 255 B) */
--
-DECLARE_POOL(pool_head_authority,      "authority",      HA_PP2_AUTHORITY_MAX);
+DECLARE_POOL(pool_head_pp_tlv_128,     "pp_tlv_128",     sizeof(struct conn_tlv_list) + HA_PP2_TLV_VALUE_128);
+DECLARE_POOL(pool_head_pp_tlv_256,     "pp_tlv_256",     sizeof(struct conn_tlv_list) + HA_PP2_TLV_VALUE_256);
--
+                       free(tlv);
+               else if (tlv->len < HA_PP2_TLV_VALUE_128)
+                       pool_free(pool_head_pp_tlv_128, tlv);
--
+                               new_tlv = malloc(get_tlv_length(tlv_packet) + sizeof(struct conn_tlv_list));
+                       else if (data_len <= HA_PP2_TLV_VALUE_128)
+                               new_tlv = pool_alloc(pool_head_pp_tlv_128);
```
See ? We allocate <= 128 from pool_tlv_128 but we release <128 to it, so 128 will be released to pool_tlv_256. I'm pretty sure that's it. Just trying to reproduce to be sure. Cc @alexanderstephan

**Comment by wtarreau** [comment]
OK if I build with all pool debugging options and start 1000 tests, 8 in parallel, I get ~10-12 failures so now it's getting clearer.

**Comment by wtarreau** [comment]
I'm proposing to close both this issue and #2274 as it should be fine now, and if we'd have to reopen we'd need to seek something else anyway. Thank you for the useful traces!
