### ISSUE TITLE
SEGV caught by QUIC Interop (https://interop.seemann.io/): LibreSSL

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#2276]
### Detailed Description of the Problem

while running QUIC Interop on haproxy (master branch) built against LibreSSL (master branch) with ASAN

server: haproxy
client: quic-go
test: longrtt

```
==28==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000048 (pc 0x556de5c1ca35 bp 0x7f27a59f4170 sp 0x7f27a59f3e40 T2)
==28==The signal is caused by a READ memory access.
==28==Hint: address points to the zero page.
    #0 0x556de5c1ca34 in qc_process_timer src/quic_conn.c:1097
    #1 0x556de62d2ebf in run_tasks_from_lists src/task.c:634
    #2 0x556de62d4917 in process_runnable_tasks src/task.c:876
    #3 0x556de61c6e51 in run_poll_loop src/haproxy.c:2969
    #4 0x556de61c7ceb in run_thread_poll_loop src/haproxy.c:3168
    #5 0x7f27a9533608 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x8608) 
    #6 0x7f27a8f2d162 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x11f162)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV src/quic_conn.c:1097 in qc_process_timer
Thread T2 created by T0 here:
    #0 0x7f27a983a815 in __interceptor_pthread_create ../../../../src/libsanitizer/asan/asan_interceptors.cc:208
    #1 0x556de6422024 in setup_extra_threads src/thread.c:252 
    #2 0x556de61cad69 in main src/haproxy.c:3852
    #3 0x7f27a8e320b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x240b2)

==28==ABORTING
```

### Expected Behavior

pour me coffee :)

### Steps to Reproduce the Behavior

run QUIC Interop against haproxy + libressl

### What is your configuration?

```haproxy
no config, caught by auto tests
```

### Output of `haproxy -vv`

```plain
haven't yet figured out how to get that from Interop
```

**Comment by chipitsine** [comment]
same crash on QuicTLS

```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==27==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000048 (pc 0x559bd2eeda35 bp 0x7fff667e0690 sp 0x7fff667e0360 T0)
==27==The signal is caused by a READ memory access.
==27==Hint: address points to the zero page.
    #0 0x559bd2eeda34 in qc_process_timer src/quic_conn.c:1097
    #1 0x559bd35a3ebf in run_tasks_from_lists src/task.c:634
    #2 0x559bd35a5917 in process_runnable_tasks src/task.c:876
    #3 0x559bd3497e51 in run_poll_loop src/haproxy.c:2969
    #4 0x559bd3498ceb in run_thread_poll_loop src/haproxy.c:3168
    #5 0x559bd349bd7a in main src/haproxy.c:3858
    #6 0x7fa90ca320b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x240b2)
    #7 0x559bd2e3dc5d in _start (/usr/local/sbin/haproxy+0x1b9c5d)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV src/quic_conn.c:1097 in qc_process_timer
==27==ABORTING
```

**Comment by chipitsine** [comment]
libressl only. not reproduced on quictls

**Comment by haproxyFred** [comment]
Ok, Thank you for this report.
I have just pushed a fix for this issue in this branch here:
https://github.com/haproxytech/quic-dev/commit/411ff1559ff2f94e14fb3ba28af2419ff791517b

**Comment by wtarreau** [comment]
Should I merge it now ?

**Comment by haproxyFred** [comment]
Yes, please. Thank you.

**Comment by wtarreau** [comment]
OK now merged, thanks!

**Comment by chipitsine** [comment]
thanks, I'll check interop again soon
