### ISSUE TITLE
QUIC Interop caught regression with LibreSSL

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#2279]
### Detailed Description of the Problem

server: [haproxy](https://github.com/haproxy/haproxy/commit/88988bb06ccadb1c5486d1e61d9aa6c75e36a404), libressl
client: quic-go
testcase: longrtt

```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==27==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000020 (pc 0x5612918ffc3a bp 0x7ffd95a7e470 sp 0x7ffd95a7dfe0 T0)
==27==The signal is caused by a WRITE memory access.
==27==Hint: address points to the zero page.
    #0 0x5612918ffc39 in qc_dgrams_retransmit src/quic_tx.c:1336
    #1 0x561291820c63 in quic_conn_io_cb src/quic_conn.c:913
    #2 0x561291ed9159 in run_tasks_from_lists src/task.c:596
    #3 0x561291edaf54 in process_runnable_tasks src/task.c:876
    #4 0x561291dcd495 in run_poll_loop src/haproxy.c:2978
    #5 0x561291dce32f in run_thread_poll_loop src/haproxy.c:3177
    #6 0x561291dd13be in main src/haproxy.c:3867
    #7 0x7f591ac320b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x240b2)
    #8 0x561291772d6d in _start (/usr/local/sbin/haproxy+0x1b9d6d)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV src/quic_tx.c:1336 in qc_dgrams_retransmit
==27==ABORTING

```

### Expected Behavior

buy me wine

### Steps to Reproduce the Behavior

running QUIC Interop suite against

### What is your configuration?

```haproxy
not sure how to get a configuration from quic interop
```

### Output of `haproxy -vv`

```plain
not sure
```

**Comment by chipitsine** [comment]
very similar failure for "handshakeloss" testcase

```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==27==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000020 (pc 0x55dd7bb04c3a bp 0x7f95247f3f40 sp 0x7f95247f3ab0 T2)
==27==The signal is caused by a WRITE memory access.
==27==Hint: address points to the zero page.
    #0 0x55dd7bb04c39 in qc_dgrams_retransmit src/quic_tx.c:1336
    #1 0x55dd7ba25c63 in quic_conn_io_cb src/quic_conn.c:913
    #2 0x55dd7c0de159 in run_tasks_from_lists src/task.c:596
    #3 0x55dd7c0dff54 in process_runnable_tasks src/task.c:876
    #4 0x55dd7bfd2495 in run_poll_loop src/haproxy.c:2978
    #5 0x55dd7bfd332f in run_thread_poll_loop src/haproxy.c:3177
    #6 0x7f952903f608 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x8608)
    #7 0x7f9527d2d162 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x11f162)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV src/quic_tx.c:1336 in qc_dgrams_retransmit
Thread T2 created by T0 here:
    #0 0x7f952863a815 in __interceptor_pthread_create ../../../../src/libsanitizer/asan/asan_interceptors.cc:208
    #1 0x55dd7c22d661 in setup_extra_threads src/thread.c:252 
    #2 0x55dd7bfd63ad in main src/haproxy.c:3861
    #3 0x7f9527c320b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x240b2)

==27==ABORTING

```

**Comment by haproxyFred** [comment]
Argh! Thank you again @chipitsine.

**Comment by haproxyFred** [comment]
Here is a fix: https://github.com/haproxytech/quic-dev/commit/6fcd73c301407ebf28571d1a6203f8af92c25457
@wtarreau it can me merged. Thank you.

**Comment by wtarreau** [comment]
Now merged, thanks Fred and Ilya.

**Comment by chipitsine** [comment]
as far as I can see, those are different commits

https://github.com/haproxytech/quic-dev/commit/6fcd73c301407ebf28571d1a6203f8af92c25457

https://github.com/haproxy/haproxy/commit/3afe54ed5b78646a5bcbda17ac8475031578a806

**Comment by wtarreau** [comment]
Then I'm confused, there was only one commit in Fred's branch. Or maybe he changed it later ? Indeed the commit Fred mentioned above is not in his fixes branch that I normally pull from. Fred, can you please clarify ? Did you change the commit or is it in a branch different from fle-quic-bugs ?

**Comment by haproxyFred** [comment]
https://github.com/haproxytech/quic-dev/commit/6fcd73c301407ebf28571d1a6203f8af92c25457 is in fle-gh2279.

**Comment by wtarreau** [comment]
ah OK, thanks for the info. Now merged for real.
