### ISSUE TITLE
segfault in SSL_CIPHER_get_id

### ISSUE THREAD

**Issue by Tristan971** [haproxy/haproxy#2329]
### Detailed Description of the Problem

HAProxy crashes

### Expected Behavior

No crash

### Steps to Reproduce the Behavior

1. Run HAProxy

### Do you have an idea how to solve the issue?

No idea, but it's frequent enough to happen on our dev environment which is nearly idling

### What is your configuration?

```haproxy
as usual, with this ssl config

# SSL server configuration
ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
ssl-default-bind-options prefer-client-ciphers no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets
ssl-dh-param-file /etc/haproxy/ssl/dhparams

# SSL client configuration
ssl-default-server-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
ssl-default-server-options no-sslv3 no-tlsv10 no-tlsv11 no-tlsv12 no-tls-tickets
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.9-dev8-47ed118+mangadex-4bfd942 2023-10-30T11:20+00:00 - https://haproxy.org/
Status: development branch - not safe for use in production.
Known bugs: https://github.com/haproxy/haproxy/issues?q=is:issue+is:open
Running on: Linux 6.2.16-12-pve #1 SMP PREEMPT_DYNAMIC PMX 6.2.16-12 (2023-09-04T13:21Z) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -ggdb3 -gdwarf-4 -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wnull-dereference -fwrapv -Wno-unknown-warning-option -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment -DMAX_SESS_STKCTR=5
  OPTIONS = USE_LIBCRYPT=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_TFO=1 USE_NS=1 USE_SYSTEMD=1 USE_QUIC=1 USE_PROMEX=1 USE_STATIC_PCRE2=1 USE_PCRE2=1 USE_PCRE2_JIT=1
  DEBUG   = -DDEBUG_MEMORY_POOLS -DDEBUG_STRICT

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_AWSLC -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION +QUIC -QUIC_OPENSSL_COMPAT +RT +SHM_OPEN +SLZ +SSL -STATIC_PCRE +STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=8).
Built with OpenSSL version : OpenSSL 1.1.1v+quic-mangadex-4bfd942 30 Oct 2023
Running on OpenSSL version : OpenSSL 1.1.1v+quic-mangadex-4bfd942 30 Oct 2023
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.4.6
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.42 2022-12-11
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with clang compiler version 16.0.6 (++20230710041738+7cbf1a259152-1~exp1~20230710161755.7)

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
       quic : mode=HTTP  side=FE     mux=QUIC  flags=HTX|NO_UPG|FRAMED
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=

Available services : prometheus-exporter
Available filters :
        [BWLIM] bwlim-in
        [BWLIM] bwlim-out
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
        [TRACE] trace
```

### Last Outputs and Backtraces

```plain
Core was generated by `/usr/sbin/haproxy -Ws -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid -dMno-mer'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000564e8478f5b0 in SSL_CIPHER_get_id ()
[Current thread is 1 (Thread 0x7f314675b640 (LWP 256001))]
(gdb) t a a bt full

Thread 7 (Thread 0x7f3145f5a640 (LWP 256002)):
#0  0x00007f314f12601e in epoll_wait () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#1  0x0000564e8453b947 in _do_poll (p=<optimized out>, exp=-3363, wake=0) at src/ev_epoll.c:232
        timeout = 55
        updt_idx = <optimized out>
        fd = <optimized out>
        old_fd = <optimized out>
        wait_time = 55
        status = <optimized out>
        count = <optimized out>
#2  0x0000564e846d984c in run_poll_loop () at src/haproxy.c:3055
        _ = {
          func = 0x564e84a42ca7 "run_poll_loop",
          file = 0x564e84a42cb5 "src/haproxy.c",
          line = 3011,
          what = 1 '\001',
          arg8 = 0 '\000',
          arg32 = 0
        }
        wake = <optimized out>
        next = 604232720
#3  0x0000564e846ddc5f in run_thread_poll_loop (data=<optimized out>) at src/haproxy.c:3179
        init_left = 0
        init_mutex = {
          __data = {
            __lock = 0,
            __count = 0,
            __owner = 0,
            __nusers = 0,
            __kind = 0,
            __spins = 0,
            __elision = 0,
            __list = {
              __prev = 0x0,
              __next = 0x0
            }
          },
          __size = '\000' <repeats 39 times>,
          __align = 0
        }
        init_cond = {
          __data = {
            __wseq = {
              __value64 = 24,
              __value32 = {
                __low = 24,
                __high = 0
              }
            },
            __g1_start = {
              __value64 = 16,
              __value32 = {
                __low = 16,
                __high = 0
              }
            },
            __g_refs = {0, 0},
            __g_size = {0, 0},
            __g1_orig_size = 16,
            __wrefs = 0,
            __g_signals = {0, 0}
          },
          __size = "\030\000\000\000\000\000\000\000\020", '\000' <repeats 23 times>, "\020", '\000' <repeats 14 times>,
          __align = 24
        }
        warn_fail = 0
        warn_fail = 0
        ptaf = <optimized out>
        ptif = <optimized out>
        ptdf = <optimized out>
        ptff = <optimized out>
#4  0x00007f314f094ac3 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#5  0x00007f314f126a40 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.

Thread 6 (Thread 0x7f3146f5c640 (LWP 256000)):
#0  0x00007f314f12601e in epoll_wait () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#1  0x0000564e8453b947 in _do_poll (p=<optimized out>, exp=-3243, wake=0) at src/ev_epoll.c:232
        timeout = 174
        updt_idx = <optimized out>
        fd = <optimized out>
        old_fd = <optimized out>
        wait_time = 174
        status = <optimized out>
        count = <optimized out>
#2  0x0000564e846d984c in run_poll_loop () at src/haproxy.c:3055
        _ = {
          func = 0x564e84a42ca7 "run_poll_loop",
          file = 0x564e84a42cb5 "src/haproxy.c",
          line = 3011,
          what = 1 '\001',
          arg8 = 0 '\000',
          arg32 = 0
        }
        wake = <optimized out>
        next = 738450448
#3  0x0000564e846ddc5f in run_thread_poll_loop (data=<optimized out>) at src/haproxy.c:3179
        init_left = 0
        init_mutex = {
          __data = {
            __lock = 0,
            __count = 0,
            __owner = 0,
            __nusers = 0,
            __kind = 0,
            __spins = 0,
            __elision = 0,
            __list = {
              __prev = 0x0,
              __next = 0x0
            }
          },
          __size = '\000' <repeats 39 times>,
          __align = 0
        }
        init_cond = {
          __data = {
            __wseq = {
              __value64 = 24,
              __value32 = {
                __low = 24,
                __high = 0
              }
            },
            __g1_start = {
              __value64 = 16,
              __value32 = {
                __low = 16,
                __high = 0
              }
            },
            __g_refs = {0, 0},
            __g_size = {0, 0},
            __g1_orig_size = 16,
            __wrefs = 0,
            __g_signals = {0, 0}
          },
          __size = "\030\000\000\000\000\000\000\000\020", '\000' <repeats 23 times>, "\020", '\000' <repeats 14 times>,
          __align = 24
        }
        warn_fail = 0
        warn_fail = 0
        ptaf = <optimized out>
        ptif = <optimized out>
        ptdf = <optimized out>
        ptff = <optimized out>
#4  0x00007f314f094ac3 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#5  0x00007f314f126a40 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.

Thread 5 (Thread 0x7f31477fe640 (LWP 255999)):
#0  0x00007f314f12601e in epoll_wait () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#1  0x0000564e8453b947 in _do_poll (p=<optimized out>, exp=-3148, wake=0) at src/ev_epoll.c:232
        timeout = 429
        updt_idx = <optimized out>
        fd = <optimized out>
        old_fd = <optimized out>
        wait_time = 429
        status = <optimized out>
        count = <optimized out>
#2  0x0000564e846d984c in run_poll_loop () at src/haproxy.c:3055
        _ = {
          func = 0x564e84a42ca7 "run_poll_loop",
          file = 0x564e84a42cb5 "src/haproxy.c",
          line = 3011,
          what = 1 '\001',
          arg8 = 0 '\000',
          arg32 = 0
        }
        wake = <optimized out>
        next = 671341584
#3  0x0000564e846ddc5f in run_thread_poll_loop (data=<optimized out>) at src/haproxy.c:3179
        init_left = 0
        init_mutex = {
          __data = {
            __lock = 0,
            __count = 0,
            __owner = 0,
            __nusers = 0,
            __kind = 0,
            __spins = 0,
            __elision = 0,
            __list = {
              __prev = 0x0,
              __next = 0x0
            }
          },
          __size = '\000' <repeats 39 times>,
          __align = 0
        }
        init_cond = {
          __data = {
            __wseq = {
              __value64 = 24,
              __value32 = {
                __low = 24,
                __high = 0
              }
            },
            __g1_start = {
              __value64 = 16,
              __value32 = {
                __low = 16,
                __high = 0
              }
            },
            __g_refs = {0, 0},
            __g_size = {0, 0},
            __g1_orig_size = 16,
            __wrefs = 0,
            __g_signals = {0, 0}
          },
          __size = "\030\000\000\000\000\000\000\000\020", '\000' <repeats 23 times>, "\020", '\000' <repeats 14 times>,
          __align = 24
        }
        warn_fail = 0
        warn_fail = 0
        ptaf = <optimized out>
        ptif = <optimized out>
        ptdf = <optimized out>
        ptff = <optimized out>
#4  0x00007f314f094ac3 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#5  0x00007f314f126a40 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.

Thread 4 (Thread 0x7f3147fff640 (LWP 255998)):
#0  0x00007f314f12601e in epoll_wait () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#1  0x0000564e8453b947 in _do_poll (p=<optimized out>, exp=-3241, wake=0) at src/ev_epoll.c:232
        timeout = 177
        updt_idx = <optimized out>
        fd = <optimized out>
        old_fd = <optimized out>
        wait_time = 177
        status = <optimized out>
        count = <optimized out>
#2  0x0000564e846d984c in run_poll_loop () at src/haproxy.c:3055
        _ = {
          func = 0x564e84a42ca7 "run_poll_loop",
          file = 0x564e84a42cb5 "src/haproxy.c",
          line = 3011,
          what = 1 '\001',
          arg8 = 0 '\000',
          arg32 = 0
        }
        wake = <optimized out>
        next = 805559312
#3  0x0000564e846ddc5f in run_thread_poll_loop (data=<optimized out>) at src/haproxy.c:3179
        init_left = 0
        init_mutex = {
          __data = {
            __lock = 0,
            __count = 0,
            __owner = 0,
            __nusers = 0,
            __kind = 0,
            __spins = 0,
            __elision = 0,
            __list = {
              __prev = 0x0,
              __next = 0x0
            }
          },
          __size = '\000' <repeats 39 times>,
          __align = 0
        }
        init_cond = {
          __data = {
            __wseq = {
              __value64 = 24,
              __value32 = {
                __low = 24,
                __high = 0
              }
            },
            __g1_start = {
              __value64 = 16,
              __value32 = {
                __low = 16,
                __high = 0
              }
            },
            __g_refs = {0, 0},
            __g_size = {0, 0},
            __g1_orig_size = 16,
            __wrefs = 0,
            __g_signals = {0, 0}
          },
          __size = "\030\000\000\000\000\000\000\000\020", '\000' <repeats 23 times>, "\020", '\000' <repeats 14 times>,
          __align = 24
        }
        warn_fail = 0
        warn_fail = 0
        ptaf = <optimized out>
        ptif = <optimized out>
        ptdf = <optimized out>
        ptff = <optimized out>
#4  0x00007f314f094ac3 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#5  0x00007f314f126a40 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.

Thread 3 (Thread 0x7f314edf2640 (LWP 255997)):
#0  0x00007f314f12601e in epoll_wait () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#1  0x0000564e8453b947 in _do_poll (p=<optimized out>, exp=-3054, wake=0) at src/ev_epoll.c:232
        timeout = 363
        updt_idx = <optimized out>
        fd = <optimized out>
        old_fd = <optimized out>
        wait_time = 363
        status = <optimized out>
        count = <optimized out>
#2  0x0000564e846d984c in run_poll_loop () at src/haproxy.c:3055
        _ = {
          func = 0x564e84a42ca7 "run_poll_loop",
          file = 0x564e84a42cb5 "src/haproxy.c",
          line = 3011,
          what = 1 '\001',
          arg8 = 0 '\000',
          arg32 = 0
        }
        wake = <optimized out>
        next = 1208216688
#3  0x0000564e846ddc5f in run_thread_poll_loop (data=<optimized out>) at src/haproxy.c:3179
        init_left = 0
        init_mutex = {
          __data = {
            __lock = 0,
            __count = 0,
            __owner = 0,
            __nusers = 0,
            __kind = 0,
            __spins = 0,
            __elision = 0,
            __list = {
              __prev = 0x0,
              __next = 0x0
            }
          },
          __size = '\000' <repeats 39 times>,
          __align = 0
        }
        init_cond = {
          __data = {
            __wseq = {
              __value64 = 24,
              __value32 = {
                __low = 24,
                __high = 0
              }
            },
            __g1_start = {
              __value64 = 16,
              __value32 = {
                __low = 16,
                __high = 0
              }
            },
            __g_refs = {0, 0},
            __g_size = {0, 0},
            __g1_orig_size = 16,
            __wrefs = 0,
            __g_signals = {0, 0}
          },
          __size = "\030\000\000\000\000\000\000\000\020", '\000' <repeats 23 times>, "\020", '\000' <repeats 14 times>,
          __align = 24
        }
        warn_fail = 0
        warn_fail = 0
        ptaf = <optimized out>
        ptif = <optimized out>
        ptdf = <optimized out>
        ptff = <optimized out>
#4  0x00007f314f094ac3 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#5  0x00007f314f126a40 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.

Thread 2 (Thread 0x7f314f249180 (LWP 255996)):
#0  0x00007f314f12601e in epoll_wait () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#1  0x0000564e8453b947 in _do_poll (p=<optimized out>, exp=-3275, wake=0) at src/ev_epoll.c:232
        timeout = 142
        updt_idx = <optimized out>
        fd = <optimized out>
        old_fd = <optimized out>
        wait_time = 142
        status = <optimized out>
        count = <optimized out>
#2  0x0000564e846d984c in run_poll_loop () at src/haproxy.c:3055
        _ = {
          func = 0x564e84a42ca7 "run_poll_loop",
          file = 0x564e84a42cb5 "src/haproxy.c",
          line = 3011,
          what = 1 '\001',
          arg8 = 0 '\000',
          arg32 = 0
        }
        wake = <optimized out>
        next = -2050589248
#3  0x0000564e846ddc5f in run_thread_poll_loop (data=<optimized out>) at src/haproxy.c:3179
        init_left = 0
        init_mutex = {
          __data = {
            __lock = 0,
            __count = 0,
            __owner = 0,
            __nusers = 0,
            __kind = 0,
            __spins = 0,
            __elision = 0,
            __list = {
              __prev = 0x0,
              __next = 0x0
            }
          },
          __size = '\000' <repeats 39 times>,
          __align = 0
        }
        init_cond = {
          __data = {
            __wseq = {
              __value64 = 24,
              __value32 = {
                __low = 24,
                __high = 0
              }
            },
            __g1_start = {
              __value64 = 16,
              __value32 = {
                __low = 16,
                __high = 0
              }
            },
            __g_refs = {0, 0},
            __g_size = {0, 0},
            __g1_orig_size = 16,
            __wrefs = 0,
            __g_signals = {0, 0}
          },
          __size = "\030\000\000\000\000\000\000\000\020", '\000' <repeats 23 times>, "\020", '\000' <repeats 14 times>,
          __align = 24
        }
        warn_fail = 0
        warn_fail = 0
        ptaf = <optimized out>
        ptif = <optimized out>
        ptdf = <optimized out>
        ptff = <optimized out>
#4  0x0000564e846dce77 in main (argc=<optimized out>, argv=0x7ffcaaa2ae88) at src/haproxy.c:3876
        limit = {
          rlim_cur = 18446744073709551615,
          rlim_max = 18446744073709551615
        }
        pidfd = <optimized out>
        retry = <optimized out>
        err = <optimized out>
        intovf = <optimized out>

Thread 1 (Thread 0x7f314675b640 (LWP 256001)):
#0  0x0000564e8478f5b0 in SSL_CIPHER_get_id ()
No symbol table info available.
#1  0x0000564e8453de73 in ssl_sock_switchctx_cbk (ssl=0x7f3120058370, al=0x7f3146750084, arg=<optimized out>) at src/ssl_sock.c:2509
        cipher_suites = <optimized out>
        len = 38
        cipher = 0x0
        cipher_id = <optimized out>
        conn = 0x7f31240635b0
        qc = <optimized out>
        s = 0x564e8570afc0
        has_rsa_sig = <optimized out>
        has_ecdsa_sig = 0
        wildp = 0x0
        node_ecdsa = 0x0
        node_rsa = 0x0
        node_anonymous = 0x0
        allow_early = 1
        extension_data = <optimized out>
        extension_len = <optimized out>
        servername = 0x7f312005a8c0 "canary.mangadex.dev"
        servername_len = 19
        i = <optimized out>
        node = <optimized out>
        n = <optimized out>
#2  0x0000564e847b8f4e in tls_post_process_client_hello ()
No symbol table info available.
#3  0x0000564e847a78e9 in state_machine ()
No symbol table info available.
#4  0x0000564e84792f92 in SSL_do_handshake ()
No symbol table info available.
#5  0x0000564e84793423 in SSL_read_early_data ()
No symbol table info available.
#6  0x0000564e84542ae4 in ssl_sock_handshake (conn=0x7f31240635b0, flag=134217728) at src/ssl_sock.c:5976
        read_data = 0
        ctx = 0x7f31200582d0
        counters = 0x564e85a63cf0
        counters_px = 0x564e85a639b0
        li = <optimized out>
        srv = <optimized out>
        skerr = <optimized out>
        lskerr = 4
        ret = <optimized out>
        read_data = <optimized out>
        area = <optimized out>
        __ptr = <optimized out>
        c = <optimized out>
        empty_handshake = <optimized out>
        state = <optimized out>
        empty_handshake = <optimized out>
        state = <optimized out>
        s = <optimized out>
        __lk_r = <optimized out>
        __set_r = <optimized out>
        __msk_r = <optimized out>
        __old_r = <optimized out>
        __old = <optimized out>
        __x = <optimized out>
#7  ssl_sock_io_cb (t=t@entry=0x7f3120062720, context=context@entry=0x7f31200582d0, state=<optimized out>) at src/ssl_sock.c:6435
        _ = {
          func = 0x564e849eae08 "ssl_sock_io_cb",
          file = 0x564e849ea75d "src/ssl_sock.c",
          line = 6452,
          what = 3 '\003',
          arg8 = 0 '\000',
          arg32 = 0
        }
        _ = {
          func = 0x564e849eae08 "ssl_sock_io_cb",
          file = 0x564e849ea75d "src/ssl_sock.c",
          line = 6475,
          what = 3 '\003',
          arg8 = 0 '\000',
          arg32 = 0
        }
        ret = 0
        conn = 0x7f31240635b0
        conn_in_list = 0
        tl = <optimized out>
        ctx = <optimized out>
#8  0x0000564e84710bc1 in run_tasks_from_lists (budgets=budgets@entry=0x7f3146750310) at src/task.c:596
        _ = {
          func = 0x564e84a4da67 "run_tasks_from_lists",
          file = 0x564e84a4d9d2 "src/task.c",
          line = 658,
          what = 5 '\005',
          arg8 = 0 '\000',
          arg32 = 0
        }
        tl_queues = 0x564e84e1c8a0 <ha_thread_ctx+2720>
        budget_mask = 15 '\017'
        profile_entry = 0x0
        done = 0
        queue = 3
        t = 0x7f3120062720
        process = 0x564e84542850 <ssl_sock_io_cb>
        ctx = 0x7f31200582d0
        state = 0
#9  0x0000564e8471153a in process_runnable_tasks () at src/task.c:876
        max = {0, 0, 0, 0}
        tt = 0x564e84e1c800 <ha_thread_ctx+2560>
        default_weights = {64, 48, 16, 1}
        heavy_queued = 1
        max_processed = 112
        max_total = <optimized out>
        queue = 4
        budget = 0
        grq = <optimized out>
        lrq = <optimized out>
        gpicked = <optimized out>
        lpicked = <optimized out>
        t = <optimized out>
        tmp_list = <optimized out>
#10 0x0000564e846d9882 in run_poll_loop () at src/haproxy.c:2980
        _ = {
          func = 0x564e84a42ca7 "run_poll_loop",
          file = 0x564e84a42cb5 "src/haproxy.c",
          line = 3011,
          what = 1 '\001',
          arg8 = 0 '\000',
          arg32 = 0
        }
        wake = <optimized out>
        next = <optimized out>
#11 0x0000564e846ddc5f in run_thread_poll_loop (data=<optimized out>) at src/haproxy.c:3179
        init_left = 0
        init_mutex = {
          __data = {
            __lock = 0,
            __count = 0,
            __owner = 0,
            __nusers = 0,
            __kind = 0,
            __spins = 0,
            __elision = 0,
            __list = {
              __prev = 0x0,
              __next = 0x0
            }
          },
          __size = '\000' <repeats 39 times>,
          __align = 0
        }
        init_cond = {
          __data = {
            __wseq = {
              __value64 = 24,
              __value32 = {
                __low = 24,
                __high = 0
              }
            },
            __g1_start = {
              __value64 = 16,
              __value32 = {
                __low = 16,
                __high = 0
              }
            },
            __g_refs = {0, 0},
            __g_size = {0, 0},
            __g1_orig_size = 16,
            __wrefs = 0,
            __g_signals = {0, 0}
          },
          __size = "\030\000\000\000\000\000\000\000\020", '\000' <repeats 23 times>, "\020", '\000' <repeats 14 times>,
          __align = 24
        }
        warn_fail = 0
        warn_fail = 0
        ptaf = <optimized out>
        ptif = <optimized out>
        ptdf = <optimized out>
        ptff = <optimized out>
#12 0x00007f314f094ac3 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#13 0x00007f314f126a40 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
```

**Comment by wlallemand** [comment]
Okay that's bad, I introduced the problem with 23093c72f139eddfce68ea5580193ee131901591, at least we didn't make any release with it yet. I'm pushing a fix, thanks for the report.
