### ISSUE TITLE
Assert failure in ssl_sock_free_ocsp during old process exit

### ISSUE THREAD

**Issue by Tristan971** [haproxy/haproxy#2462]
### Detailed Description of the Problem

HAProxy process crashes with assert failure

### Expected Behavior

No assert failure

### Steps to Reproduce the Behavior

Unsure

### Do you have any idea what may have caused this?

Seems like a failure to unwind the old process. Maybe related to hard stop logic specifically.

### What is your configuration?

```haproxy
#/etc/haproxy/ssl/crtlist
/etc/haproxy/ssl/tld1.pem [ocsp-update on] tld1 *.tld1
/etc/haproxy/ssl/tld2.pem [ocsp-update on] tld2 *.tld2
/etc/haproxy/ssl/tld3.pem [ocsp-update on] tld3 *.tld3
/etc/haproxy/ssl/tld4.pem [ocsp-update on] tld4 *.tld4

#haproxy.cfg
bind 45.129.229.1:443 ssl strict-sni crt-list /etc/haproxy/ssl/crtlist alpn h2,http1.1 tfo allow-0rtt
bind 45.129.229.2:443 ssl strict-sni crt-list /etc/haproxy/ssl/crtlist alpn h2,http1.1 tfo allow-0rtt
...
```

### Output of `haproxy -vv`

```plain
HAProxy version 3.0-dev4-dec0175+mangadex-1c8f244 2024-02-23T19:31+00:00 - https://haproxy.org/
Status: development branch - not safe for use in production.
Known bugs: https://github.com/haproxy/haproxy/issues?q=is:issue+is:open
Running on: Linux 5.15.131-1-pve #1 SMP PVE 5.15.131-2 (2023-11-14T11:32Z) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -ggdb3 -gdwarf-4 -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wnull-dereference -fwrapv -Wno-unknown-warning-option -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment -DMAX_SESS_STKCTR=5
  OPTIONS = USE_LIBCRYPT=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_TFO=1 USE_NS=1 USE_SYSTEMD=1 USE_QUIC=1 USE_PROMEX=1 USE_STATIC_PCRE2=1 USE_PCRE2=1 USE_PCRE2_JIT=1
  DEBUG   = -DDEBUG_MEMORY_POOLS -DDEBUG_STRICT

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_AWSLC -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION +QUIC -QUIC_OPENSSL_COMPAT +RT +SHM_OPEN +SLZ +SSL -STATIC_PCRE +STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=16).
Built with OpenSSL version : OpenSSL 1.1.1w+quic-mangadex-1c8f244 23 Feb 2024
Running on OpenSSL version : OpenSSL 1.1.1w+quic-mangadex-1c8f244 23 Feb 2024
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.4.6
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.42 2022-12-11
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with clang compiler version 17.0.6 (++20231208085813+6009708b4367-1~exp1~20231208085906.81)

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
       quic : mode=HTTP  side=FE     mux=QUIC  flags=HTX|NO_UPG|FRAMED
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=

Available services : prometheus-exporter
Available filters :
	[BWLIM] bwlim-in
	[BWLIM] bwlim-out
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
```

### Last Outputs and Backtraces

```plain
haproxy[775420]: [NOTICE]   (775420) : New worker (790783) forked
haproxy[775420]: [NOTICE]   (775420) : Loading success.
haproxy[790783]: -:- [25/Feb/2024:20:24:25.885] <OCSP-UPDATE> /etc/haproxy/ssl/tld1.pem 1 "Update successful" 0 1
haproxy[790783]: -:- [25/Feb/2024:20:24:25.889] <OCSP-UPDATE> /etc/haproxy/ssl/tld2.pem 1 "Update successful" 0 1
haproxy[790783]: -:- [25/Feb/2024:20:24:25.892] <OCSP-UPDATE> /etc/haproxy/ssl/tld3.pem 1 "Update successful" 0 1
haproxy[790783]: -:- [25/Feb/2024:20:24:25.895] <OCSP-UPDATE> /etc/haproxy/ssl/tld4.pem 1 "Update successful" 0 1
haproxy[775420]: [NOTICE]   (775420) : haproxy version is 3.0-dev4-dec0175+mangadex-1c8f244
haproxy[775420]: [NOTICE]   (775420) : path to executable is /usr/sbin/haproxy
haproxy[775420]: [WARNING]  (775420) : Former worker (790280) exited with code 0 (Exit)
haproxy[782466]: -:- [25/Feb/2024:20:25:06.179] <OCSP-UPDATE> /etc/haproxy/ssl/tld1.pem 1 "Update successful" 0 11
haproxy[782466]: -:- [25/Feb/2024:20:25:06.182] <OCSP-UPDATE> /etc/haproxy/ssl/tld2.pem 1 "Update successful" 0 11
haproxy[782466]: -:- [25/Feb/2024:20:25:06.185] <OCSP-UPDATE> /etc/haproxy/ssl/tld3.pem 1 "Update successful" 0 11
haproxy[782466]: -:- [25/Feb/2024:20:25:07.189] <OCSP-UPDATE> /etc/haproxy/ssl/tld4.pem 1 "Update successful" 0 11
haproxy[782466]: [WARNING]  (782466) : soft-stop running for too long, performing a hard-stop.
haproxy[782466]: soft-stop running for too long, performing a hard-stop.
haproxy[782466]: [WARNING]  (782466) : Some tasks resisted to hard-stop, exiting now.
haproxy[782466]: Some tasks resisted to hard-stop, exiting now.
haproxy[782466]: FATAL: bug condition "ocsp->refcount_instance > 0" matched at src/ssl_ocsp.c:397
haproxy[782466]:   call trace(1):
haproxy[782466]:   | 0xfffffffffffffffb [-- -- -- -- -- -- -- --]: main+0xffffaa664f46ab8b
haproxy[775420]: [WARNING]  (775420) : Former worker (782466) exited with code 132 (Illegal instruction)
haproxy[790783]: -:- [25/Feb/2024:21:24:25.897] <OCSP-UPDATE> /etc/haproxy/ssl/tld1.pem 1 "Update successful" 0 2
haproxy[790783]: -:- [25/Feb/2024:21:24:25.901] <OCSP-UPDATE> /etc/haproxy/ssl/tld2.pem 1 "Update successful" 0 2
haproxy[790783]: -:- [25/Feb/2024:21:24:25.903] <OCSP-UPDATE> /etc/haproxy/ssl/tld3.pem 1 "Update successful" 0 2
haproxy[790783]: -:- [25/Feb/2024:21:24:25.906] <OCSP-UPDATE> /etc/haproxy/ssl/tld4.pem 1 "Update successful" 0 2
haproxy[790783]: -:- [25/Feb/2024:22:24:25.912] <OCSP-UPDATE> /etc/haproxy/ssl/tld1.pem 1 "Update successful" 0 3
haproxy[790783]: -:- [25/Feb/2024:22:24:25.916] <OCSP-UPDATE> /etc/haproxy/ssl/tld2.pem 1 "Update successful" 0 3
haproxy[790783]: -:- [25/Feb/2024:22:24:25.918] <OCSP-UPDATE> /etc/haproxy/ssl/tld3.pem 1 "Update successful" 0 3
haproxy[790783]: -:- [25/Feb/2024:22:24:25.920] <OCSP-UPDATE> /etc/haproxy/ssl/tld4.pem 1 "Update successful" 0 3




Program terminated with signal SIGILL, Illegal instruction.
#0  0x00005599b0a0c174 in ssl_sock_free_ocsp (ocsp=0x7fc86f5d4480) at src/ssl_ocsp.c:397
397	src/ssl_ocsp.c: No such file or directory.
(gdb) t a a bt full

Thread 1 (Thread 0x7fc883aaf9c0 (LWP 782466)):
#0  0x00005599b0a0c174 in ssl_sock_free_ocsp (ocsp=0x7fc86f5d4480) at src/ssl_ocsp.c:397
        msg = <optimized out>
#1  0x00005599b09f9bea in ssl_sock_free_cert_key_and_chain_contents (data=0x7fc88362c640) at src/ssl_ckch.c:751
        certid = "0K0\t\006\005+\016\003\002\032\005\000\004\024H\332\311\240\373+\323-O\360\336h\322\365g\267\065\371\263\304\004\024\024.\263\027\267XV\313\256P\t@\346\037\257\235\213\024\302\306\002\022\003t<\251\261'\202\351\273\273\343\312\277\364f\266jr", '\000' <repeats 50 times>
        certid_length = 77
        ocsp = 0x5b
#2  0x00005599b09fb7b1 in ckch_store_free (store=0x7fc86f52b180) at src/ssl_ckch.c:909
        inst = <optimized out>
        inst_s = <optimized out>
        __x = <optimized out>
#3  ckch_deinit () at src/ssl_ckch.c:3955
        node = 0x7fc86f52b1a8
        next = 0x7fc86f52b3a8
        store = 0x7fc86f52b180
        canode = <optimized out>
#4  0x00005599b0b948f5 in deinit () at src/haproxy.c:2925
        p = <optimized out>
        ua = <optimized out>
        cur_fd = <optimized out>
        p0 = <optimized out>
        uap = <optimized out>
        pdf = 0x7fc883627040
        log = <optimized out>
        logb = <optimized out>
        wl = <optimized out>
        wlb = <optimized out>
        bol = <optimized out>
        pxdf = <optimized out>
        pxdfb = <optimized out>
        pdfb = <optimized out>
        srvdf = <optimized out>
        srvdfb = <optimized out>
        pcf = <optimized out>
        pcfb = <optimized out>
        pscf = <optimized out>
        pscfb = <optimized out>
        ppcf = <optimized out>
        ppcfb = <optimized out>
        prcf = <optimized out>
        prcfb = <optimized out>
        tif = <optimized out>
        tifb = <optimized out>
        tdf = <optimized out>
        tdfb = <optimized out>
        taf = <optimized out>
        tafb = <optimized out>
        tff = <optimized out>
        tffb = <optimized out>
        pprs = <optimized out>
        pprsb = <optimized out>
        bolb = <optimized out>
#5  0x00005599b0b94f4f in deinit_and_exit (status=status@entry=0) at src/haproxy.c:3027
No locals.
#6  0x00005599b0b981a8 in main (argc=<optimized out>, argv=0x7ffe144fc698) at src/haproxy.c:3954
        limit = {
          rlim_cur = 18446744073709551615,
          rlim_max = 18446744073709551615
        }
        pidfd = <optimized out>
        retry = <optimized out>
        err = <optimized out>
        intovf = <optimized out>
```

**Comment by wlallemand** [comment]
Thank you for the report, it was also reported in #2442, the patches that introduced this regression were reverted and new 2.8 and 2.9 release done.
