### ISSUE TITLE
memory leak in master branch

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#256]
```
***  h1   debug|==8871==ERROR: LeakSanitizer: detected memory leaks
***  h1   debug|
***  h1   debug|Direct leak of 8 byte(s) in 1 object(s) allocated from:
***  h1   debug|    #0 0x4dd653 in __interceptor_malloc /tmp/final/llvm.src/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:146:3
**** dT   0.064
***  h1   debug|    #1 0x76e222 in my_strndup /home/travis/build/haproxy/haproxy/src/standard.c:2237:8
***  h1   debug|    #2 0x85b436 in parse_acl /home/travis/build/haproxy/haproxy/src/acl.c:728:13
***  h1   debug|    #3 0x97cefe in _fini (/home/travis/build/haproxy/haproxy/haproxy+0x97cefe)
***  h1   debug|
***  h1   debug|Direct leak of 8 byte(s) in 1 object(s) allocated from:
***  h1   debug|    #0 0x4dd653 in __interceptor_malloc /tmp/final/llvm.src/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:146:3
***  h1   debug|    #1 0x76e222 in my_strndup /home/travis/build/haproxy/haproxy/src/standard.c:2237:8
***  h1   debug|    #2 0x85b436 in parse_acl /home/travis/build/haproxy/haproxy/src/acl.c:728:13
**** dT   0.066
***  h1   debug|    #3 0x7ffe470e4c1f  ([stack]+0x1dc1f)
***  h1   debug|
***  h1   debug|SUMMARY: AddressSanitizer: 16 byte(s) leaked in 2 allocation(s).
```

failed build: https://travis-ci.com/haproxy/haproxy/jobs/231360766

**Comment by capflam** [comment]
Now fixed and backported. Thanks !
