### ISSUE TITLE
QUIC Interop / AWS-LC / neqo: segfault on handshakecorruption test

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#2664]
### Detailed Description of the Problem

```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==28==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000008 (pc 0x563457d60b29 bp 0x7ffd7ac16780 sp 0x7ffd7ac16740 T0)
==28==The signal is caused by a READ memory access.
==28==Hint: address points to the zero page.
    #0 0x563457d60b28 in qc_enc_level_alloc (/usr/local/sbin/haproxy+0xd7b28)
    #1 0x563457d225f8 in qc_rx_pkt_handle (/usr/local/sbin/haproxy+0x995f8)
    #2 0x563457d29646 in quic_dgram_parse (/usr/local/sbin/haproxy+0xa0646)
    #3 0x563457d5be4b in qc_rcv_buf (/usr/local/sbin/haproxy+0xd2e4b)
    #4 0x563457d4cd78 in quic_conn_app_io_cb (/usr/local/sbin/haproxy+0xc3d78)
    #5 0x563457f53a81 in run_tasks_from_lists (/usr/local/sbin/haproxy+0x2caa81)
    #6 0x563457f545d2 in process_runnable_tasks (/usr/local/sbin/haproxy+0x2cb5d2)
    #7 0x563457ed5bb6 in run_poll_loop (/usr/local/sbin/haproxy+0x24cbb6)
    #8 0x563457ed6366 in run_thread_poll_loop (/usr/local/sbin/haproxy+0x24d366)
    #9 0x563457ed95df in main (/usr/local/sbin/haproxy+0x2505df)
    #10 0x7fe386259082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082)
    #11 0x563457cf09cd in _start (/usr/local/sbin/haproxy+0x679cd)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/usr/local/sbin/haproxy+0xd7b28) in qc_enc_level_alloc
==28==ABORTING
```

### Expected Behavior

according to The Terminator (1984) we should be living in Skynet driven world. no SEGV is allowed

### Steps to Reproduce the Behavior

run QUIC Interop with the following

- neqo client
-  aws-lc lib
- asan enabled

### What is your configuration?

```haproxy
default QUIC Interop one
```

### Output of `haproxy -vv`

```plain
no :(
```

**Comment by chipitsine** [comment]
I'll try to get better symbols with clang

**Comment by haproxyFred** [comment]
The log would be helpful too.

**Comment by chipitsine** [comment]
I've deleted logs (in hope that issue will be reproduced).
well, it was not easy to get repro. no luck so far

I suspect it was lack of resource, for example memory (I ran on low end laptop)

I checked on missing malloc/strdup ( https://github.com/haproxy/haproxy/issues/2615 ), no clue so far

**Comment by haproxyFred** [comment]
Not reproduced here.

**Comment by chipitsine** [comment]
no repro so far.
I'm closing it
