### ISSUE TITLE
Peers crash on reload when there's no local peer

### ISSUE THREAD

**Issue by wtarreau** [haproxy/haproxy#312]
I met this issue while trying to reproduce another one affecting peers, hence my limited analysis.

 ## Output of `haproxy -vv` and `uname -a`

```
Linux wtap.local 4.19.68 #1 SMP Tue Sep 3 07:00:08 CEST 2019 x86_64 GNU/Linux

HA-Proxy version 2.0.7-c0104f-1 2019/09/28 - https://haproxy.org/

HA-Proxy version 2.1-dev2-427c52-4 2019/10/02 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = /g/public/linux/master/x86_64-gcc47_glibc218-linux-gnu-gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits -DDEBUG_EXPR -DDEBUG_DEV
  OPTIONS = USE_PCRE=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB= USE_SLZ=1 USE_TFO=1 USE_NS=1 USE_WURFL=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER +PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES +WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=8).
Built with OpenSSL version : OpenSSL 1.1.1a  20 Nov 2018
Running on OpenSSL version : OpenSSL 1.1.1a  20 Nov 2018
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.5
Built with WURFL support (dummy library version 1.11.2.100)
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE version : 8.42 2018-03-20
Running on PCRE version : 8.43 2019-02-23
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=HTTP       side=FE|BE     mux=H1
       <default> : mode=TCP        side=FE|BE     mux=PASS
            fcgi : mode=HTTP       side=BE        mux=FCGI

Available services : none

Available filters :
        [SPOE] spoe
        [COMP] compression
        [CACHE] cache
        [TRACE] trace
        [FCGI] fcgi-app

```

## What's the configuration?

```
global
        stats socket /tmp/sock1 mode 666 level admin
        stats timeout 10s

peers peers
        peer localhost 127.0.0.1:1024
```

## Steps to reproduce the behavior

1. start haproxy in one window: haproxy -db -f file.cfg
2. reload haproxy in another window: haproxy -db -f file.cfg -sf $(pidof haproxy)

## Actual behavior

The old process segfaults

## Do you have any idea what may have caused this?

It looks like it's related to the lack of a local peer in the peers section.

```
Core was generated by `../haproxy-2.0/haproxy -db -f fewtables.cfg -sf 27046'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  process_peer_sync (task=0x205a370, context=0x205d5e0, state=<optimized out>) at src/peers.c:2743
2743                                    for (st = ps->tables; st ; st = st->next)
[Current thread is 1 (Thread 0x7f1179b7b080 (LWP 27055))]
(gdb) p ps
$1 = (struct peer *) 0x0
(gdb) list
2738                            if (!(peers->flags & PEERS_F_DONOTSTOP)) {
2739                                    /* add DO NOT STOP flag if not present */
2740                                    _HA_ATOMIC_ADD(&jobs, 1);
2741                                    peers->flags |= PEERS_F_DONOTSTOP;
2742                                    ps = peers->local;
2743                                    for (st = ps->tables; st ; st = st->next)
2744                                            st->table->syncing++;
2745                            }
2746
2747                            /* disconnect all connected peers */
(gdb) bt
#0  process_peer_sync (task=0x205a370, context=0x205d5e0, state=<optimized out>) at src/peers.c:2743
#1  0x000000000055e330 in process_runnable_tasks () at src/task.c:414
#2  0x00000000004cd6cb in run_poll_loop () at src/haproxy.c:2517
#3  run_thread_poll_loop (data=data@entry=0x0) at src/haproxy.c:2638
#4  0x0000000000426a4e in main (argc=<optimized out>, argv=0x7ffd3bb478f8) at src/haproxy.c:3315
```

## Do you have an idea how to solve the issue?

Actually uncertain, probably that peers->local has to be added as a condition to enter the "if" block but I'm not sure at all. I'd appreciate it if Fred or Emeric had a look at it.

**Comment by TimWolla** [comment]
5a4fe5a35d544579586672c46f8afe4114589d91
