### ISSUE TITLE
HAProxy 1.9.6 stuck in infinite loop

### ISSUE THREAD

**Issue by zeronone** [haproxy/haproxy#347]
We found a few of our HAProxies suddenly hit 100% user CPU. `strace` didn't show anything, so probably no system calls were being made. Attaching a GDB session showed the following.

## Output of `haproxy -vv` and `uname -a`
```
[root@host /]# uname -r
3.10.0-957.21.3.el7.x86_64
[root@host /]# /usr/local/bin/haproxy -vv
HA-Proxy version 1.9.6 2019/03/29 - https://haproxy.org/
Build options :
  TARGET  = linux2628
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -DTCP_USER_TIMEOUT=18
  OPTIONS = USE_LINUX_TPROXY=1 USE_ZLIB=1 USE_REGPARM=1 USE_OPENSSL=1 USE_PCRE=1 USE_PCRE_JIT=1

Default settings :
  maxconn = 2000, bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
Running on OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.7
Running on zlib version : 1.2.7
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE version : 8.32 2012-11-30
Running on PCRE version : 8.32 2012-11-30
PCRE library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with multi-threading support.

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE
              h2 : mode=HTTP       side=FE
       <default> : mode=HTX        side=FE|BE
       <default> : mode=TCP|HTTP   side=FE|BE

Available filters :
        [SPOE] spoe
        [COMP] compression
        [CACHE] cache
        [TRACE] trace
```

## GDB Output
```
(gdb) info args
cs = 0x1e90130
buf = 0x2299308
count = 2
flags = <optimized out>
(gdb) info args
cs = 0x1e90130
buf = 0x2299308
count = 2
flags = <optimized out>
(gdb) info args
cs = 0x1e90130
buf = 0x2299308
count = 2
flags = <optimized out>
(gdb) info locals
h2s = 0x20cf0e0
orig_count = <optimized out>
total = 0
ret = <optimized out>
htx = 0x0
blk = 0x2
(gdb) frame
#0  0x0000000000458e15 in h2_snd_buf (cs=0x1e90130, buf=0x2299308, count=2, flags=<optimized out>) at src/mux_h2.c:5392
5392    in src/mux_h2.c
(gdb) info locals
h2s = 0x20cf0e0
orig_count = <optimized out>
total = 0
ret = <optimized out>
htx = 0x0
blk = 0x2
(gdb) info args
cs = 0x1e90130
buf = 0x2299308
count = 2
flags = <optimized out>
(gdb) backtrace
#0  0x0000000000458e15 in h2_snd_buf (cs=0x1e90130, buf=0x2299308, count=2, flags=<optimized out>) at src/mux_h2.c:5392
#1  0x00000000004de1c4 in si_cs_send (cs=0x1e90130) at src/stream_interface.c:691
#2  0x00000000004ded08 in si_update_both (si_f=si_f@entry=0x2299528, si_b=si_b@entry=0x2299568) at src/stream_interface.c:850
#3  0x000000000044e60b in process_stream (t=t@entry=0x21c5400, context=0x2299290, state=<optimized out>) at src/stream.c:2502
#4  0x000000000050c555 in process_runnable_tasks () at src/task.c:434
#5  0x000000000048d155 in run_poll_loop () at src/haproxy.c:2642
#6  run_thread_poll_loop (data=data@entry=0x1647c50) at src/haproxy.c:2707
#7  0x000000000040bd2a in main (argc=<optimized out>, argv=0x7fffe85ed578) at src/haproxy.c:3343
(gdb) print ret
$1 = <optimized out>
(gdb) whatis ret
type = size_t
(gdb) print printf("%d", ret)
value has been optimized out
(gdb) info locals
h2s = 0x20cf0e0
orig_count = <optimized out>
total = 0
ret = <optimized out>
htx = 0x0
blk = 0x2
(gdb) ptype h2s
type = struct h2s {
    struct conn_stream *cs;
    struct session *sess;
    struct h2c *h2c;
    struct h1m h1m;
    struct eb32_node by_id;
    int32_t id;
    uint32_t flags;
    int mws;
    enum h2_err errcode;
    enum h2_ss st;
    uint16_t status;
    unsigned long long body_len;
    struct buffer rxbuf;
    struct wait_event wait_event;
    struct wait_event *recv_wait;
    struct wait_event *send_wait;
    struct list list;
    struct list sending_list;
} *
(gdb) print h2s
$2 = (struct h2s *) 0x20cf0e0
(gdb) print *h2s
$3 = {cs = 0x1e90130, sess = 0x7a9dc0 <pool_cache+96>, h2c = 0x2004c20, h1m = {state = H1_MSG_CHUNK_SIZE, flags = 542, curr_len = 0, body_len = 212414, next = 404, err_pos = -1, err_state = 0}, by_id = {node = {branches = {b = {0x1ea68e1, 0x20cf120}}, node_p = 0x0, leaf_p = 0x2004cd8, bit = 2, pfx = 29285}, key = 5}, id = 5,
  flags = 28673, mws = 884849, errcode = H2_ERR_NO_ERROR, st = H2_SS_HREM, status = 200, body_len = 0, rxbuf = {size = 0, area = 0x0, data = 0, head = 0}, wait_event = {task = 0x2264730, handle = 0x0, events = 0}, recv_wait = 0x2299550, send_wait = 0x0, list = {n = 0x20cf1a8, p = 0x20cf1a8}, sending_list = {n = 0x20cf1b8, p = 0x20cf1b8}}
(gdb) print *h2s->h2c
$4 = {conn = 0x1dab9e0, st0 = H2_CS_FRAME_H, errcode = H2_ERR_NO_ERROR, flags = 0, streams_limit = 100, max_id = 19, rcvd_c = 0, rcvd_s = 0, ddht = 0x214a4a0, dbuf = {size = 0, area = 0x0, data = 0, head = 0}, dsi = 9, dfl = 4, dft = 8 '\b', dff = 0 '\000', dpl = 0 '\000', last_sid = -1, mbuf = {size = 16384, area = 0x1d29560 "",
    data = 0, head = 0}, msi = -1, mfl = 0, mft = 0 '\000', mff = 0 '\000', miw = 65535, mws = 9854909, mfs = 16384, timeout = 60000, shut_timeout = 60000, nb_streams = 1, nb_cs = 1, nb_reserved = 0, stream_cnt = 10, proxy = 0x18b1da0, task = 0x2098f70, streams_by_id = {b = {0x20cf120, 0x0}}, send_list = {n = 0x2004ce8, p = 0x2004ce8},
  fctl_list = {n = 0x2004cf8, p = 0x2004cf8}, sending_list = {n = 0x2004d08, p = 0x2004d08}, buf_wait = {target = 0x0, wakeup_cb = 0x0, list = {n = 0x2004d28, p = 0x2004d28}}, wait_event = {task = 0x21fe750, handle = 0x0, events = 1}}
(gdb) print h2s->rxbuf
$5 = {size = 0, area = 0x0, data = 0, head = 0}
(gdb) print buf
$6 = (struct buffer *) 0x2299308
(gdb) print *buf
$7 = {size = 16384,
  area = 0x1edc9d0 "\226\016\374\v\350'p\025\275\242\352\033\346\304q\376B\256i^֊5Ak+\255\371\220c\215\027\267D\354\261\035R.\002\343^C\207\302_\361\034\346\212+\217\251\305\065\006\265\236NHlw\254\365}\337\317,.\200\034`\310\016O\271\343\067\320O\267\\\273\vX0\260\002r\215V\220\375\310\035@\034a\315\371\212\232\324\254M\016\234|\f\273\240!\365\071\205\263\004\231\331a]@\353'\234J\315CkG\277W\316F\265\257>\354B\373\001\065|\244v\003\375\023\324\375]˜Ƹ\020\031:$\316`Ɠ\254Ol9̡r֢ڹ\t\256\242\330&#\346\211\003\017(\202\277\250<d\254#kkV\261~\300\002x"..., data = 2, head = 857}
(gdb) ptype buf
type = struct buffer {
    size_t size;
    char *area;
    size_t data;
    size_t head;
} *
```

##  Configuration
```
global
    # send logs to local syslog
    log   localhost:18  format rfc3164  local0
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    maxconn 40000
    user haproxy
    group haproxy
    tune.ssl.default-dh-param 2048
    ssl-server-verify none # do not verify self signed certs
    ssl-default-bind-options no-tls-tickets
    server-state-file /tmp/server_state
    hard-stop-after 1m
    daemon

defaults
    load-server-state-from-file global
    mode                    http
    maxconn                 8000
    log                     global
    option                  httplog
    option log-health-checks
    # enables session redistribution in case of connection failures. So session stickiness is overriden if a appserver goes down.
    # option                  redispatch 
    timeout http-request    10s
    timeout queue           1m
    timeout connect         4s
    timeout client          1m
    timeout server          1m
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 425 /etc/haproxy/errors/425.http
    errorfile 429 /etc/haproxy/errors/429.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend fr_https_443_1542
    bind 2.0.0.1:443 ssl crt /var/lib/haproxy/ssl/wildcard.pem alpn h2,http/1.1 ciphers ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:AES256-GCM-SHA384:AES256-SHA256:AES256-SHA:AES128-GCM-SHA256:AES128-SHA256:AES128-SHA:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4
    mode http

    # Disable HTTP/1.1 CONNECT method
    http-request deny if METH_CONNECT
    default_backend ba_https_443_1542
    timeout client 60s
    
backend ba_https_443_1542
    balance roundrobin
    mode http
    http-request set-header X-Forwarded-Port 443
    http-request add-header X-Forwarded-Proto https if { ssl_fc }
    http-request add-header X-Forwarded-HTTPS ON if { ssl_fc }
    http-request add-header X-Forwarded-Proto http  if !{ ssl_fc }
    acl h_xff_exists req.hdr(X-Forwarded-For) -m found
    http-request replace-header X-Forwarded-For (.*) \1,\ %[src] if h_xff_exists
    http-request add-header X-Forwarded-For %[src] if ! h_xff_exists
    
    timeout server 60s
    option tcp-check # for now we will use SYN-ACK health check only
    
    timeout check 3s
    default-server fall 2 rise 2 ssl verify none  inter 5s
    
    server svr_service-frontend001.:443_7051 10.0.0.1:443 check port 443 weight 1 agent-check agent-port 12 agent-addr localhost agent-inter 5s agent-send 7051
    server svr_service-frontend003.:443_7052 10.0.0.2:443 check port 443 weight 1 agent-check agent-port 12 agent-addr localhost agent-inter 5s agent-send 7052
    server svr_service-frontend002.:443_7053 10.0.0.3:443 check port 443 weight 1 agent-check agent-port 12 agent-addr localhost agent-inter 5s agent-send 7053
    server svr_service-frontend005.:443_7055 10.0.0.4:443 check port 443 weight 1 agent-check agent-port 12 agent-addr localhost agent-inter 5s agent-send 7055
    server svr_service-frontend004.:443_7056 10.0.0.5:443 check port 443 weight 1 agent-check agent-port 12 agent-addr localhost agent-inter 5s agent-send 7056
```

## Steps to reproduce the behavior
- We don't know what request/situation caused HAProxy to go into loop?

**Comment by TimWolla** [comment]
Can you please upgrade to HAProxy 1.9.12 or 2.0.8? Quite a few MAJOR bugs have been fixed in the mean time: http://www.haproxy.org/bugs/bugs-1.9.6.html

Some of them, for example "BUG/MAJOR: mux-h2: do not add a stream twice to the send list", fix issues with infinite looping in the HTTP/2 subsystem.

**Comment by TimWolla** [comment]
Closing due to lack of feedback.
