### ISSUE TITLE
reg-tests/seamless-reload/abns_socket.vtc fails on s390x

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#504]
if I enable s390x in travis-ci, the following reg-test fails all the time

https://travis-ci.com/chipitsine/haproxy/jobs/287617972

```
***  h1   debug|[ALERT] 045/142714 (6373) : Current worker #1 (6382) exited with code 143 (Terminated)
```

**Comment by chipitsine** [comment]
I enabled gcc asan, here some debug info

https://travis-ci.com/chipitsine/haproxy/jobs/287620998

```
***  h1   debug|ASAN:DEADLYSIGNAL
***  h1   debug|=================================================================
***  h1   debug|==6265==ERROR: AddressSanitizer: stack-overflow on address 0x03ffcfe00000 (pc 0x03ffad2096be bp 0x03ffcfdfbda8 sp 0x03ffcfdfbba8 T0)
***  h1   debug|    <empty stack>
***  h1   debug|
***  h1   debug|SUMMARY: AddressSanitizer: stack-overflow
***  h1   debug|==6265==ABORTING
**** dT   0.017
**** h1   STDOUT EOF
**** dT   5.008
---- c1   HTTP rx timeout (fd:8 5000 ms)
```


```
***  h1   debug|=================================================================
***  h1   debug|==5957==ERROR: AddressSanitizer: stack-use-after-scope on address 0x03ffe617c460 at pc 0x02aa2b02586e bp 0x03ffe617c3a0 sp 0x03ffe617c390
***  h1   debug|WRITE of size 8 at 0x03ffe617c460 thread T0
**** dT   0.157
***  h1   debug|    #0 0x2aa2b02586d in ha_ssl_read src/ssl_sock.c:280
***  h1   debug|    #1 0x3ffbc3aa871 in bread_conv (/home/travis/opt/lib/libcrypto.so.1.1+0xaa871)
***  h1   debug|    #2 0x3ffbc3a91f9 in BIO_read (/home/travis/opt/lib/libcrypto.so.1.1+0xa91f9)
***  h1   debug|    #3 0x3ffbc624ebf in ssl3_read_n (/home/travis/opt/lib/libssl.so.1.1+0x24ebf)
***  h1   debug|    #4 0x3ffbc62a513 in ssl3_get_record (/home/travis/opt/lib/libssl.so.1.1+0x2a513)
***  h1   debug|    #5 0x3ffbc626df5 in ssl3_read_bytes (/home/travis/opt/lib/libssl.so.1.1+0x26df5)
***  h1   debug|    #6 0x3ffbc65ff0f in tls_get_message_header (/home/travis/opt/lib/libssl.so.1.1+0x5ff0f)
***  h1   debug|    #7 0x3ffbc655c4b in state_machine (/home/travis/opt/lib/libssl.so.1.1+0x55c4b)
***  h1   debug|    #8 0x3ffbc63fbb9 in SSL_do_handshake (/home/travis/opt/lib/libssl.so.1.1+0x3fbb9)
***  h1   debug|    #9 0x3ffbc6411bd in SSL_read_early_data (/home/travis/opt/lib/libssl.so.1.1+0x411bd)
***  h1   debug|    #10 0x2aa2b03e461 in ssl_sock_handshake src/ssl_sock.c:6113
***  h1   debug|    #11 0x2aa2b03e461 in ssl_sock_io_cb src/ssl_sock.c:6465
**** dT   0.159
***  h1   debug|    #12 0x2aa2b41263b in run_tasks_from_list src/task.c:345
***  h1   debug|    #13 0x2aa2b413e77 in process_runnable_tasks src/task.c:446
**** dT   0.161
***  h1   debug|    #14 0x2aa2b2fcf6d in run_poll_loop src/haproxy.c:2628
***  h1   debug|    #15 0x2aa2b2fcf6d in run_thread_poll_loop src/haproxy.c:2781
***  h1   debug|    #16 0x2aa2b0068cb in main src/haproxy.c:3481
***  h1   debug|    #17 0x3ffbbf23ac9 in __libc_start_main (/lib/s390x-linux-gnu/libc.so.6+0x23ac9)
***  h1   debug|    #18 0x2aa2b00ce13  (/home/travis/build/chipitsine/haproxy/haproxy+0x10ce13)
***  h1   debug|
**** dT   0.162
***  h1   debug|Address 0x03ffe617c460 is located in stack of thread T0
***  h1   debug| at offset 32 in frame
***  h1   debug|    #0 0x2aa2b025567 in ha_ssl_read src/ssl_sock.c:274
***  h1   debug|
***  h1   debug|  This frame has 1 object(s):
***  h1   debug|    [32, 64) 'tmpbuf' <== Memory access at offset 32 is inside this variable
***  h1   debug|HINT: this may be a false positive if your program uses some custom stack unwind mechanism or swapcontext
***  h1   debug|      (longjmp and C++ exceptions *are* supported)
***  h1   debug|SUMMARY: AddressSanitizer: stack-use-after-scope src/ssl_sock.c:280 in ha_ssl_read
***  h1   debug|Shadow bytes around the buggy address:
***  h1   debug|  0x10007ffcc2f830: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
***  h1   debug|  0x10007ffcc2f840: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
***  h1   debug|  0x10007ffcc2f850: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
***  h1   debug|  0x10007ffcc2f860: 00 00 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8
***  h1   debug|  0x10007ffcc2f870: f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8
***  h1   debug|=>0x10007ffcc2f880: f8 f8 f8 f8 f8 f8 f8 f8 f1 f1 f1 f1[f8]f8 f8 f8
***  h1   debug|  0x10007ffcc2f890: f3 f3 f3 f3 f8 00 00 00 00 00 00 00 00 00 00 00
***  h1   debug|  0x10007ffcc2f8a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
***  h1   debug|  0x10007ffcc2f8b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
***  h1   debug|  0x10007ffcc2f8c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
***  h1   debug|  0x10007ffcc2f8d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
***  h1   debug|Shadow byte legend (one shadow byte represents 8 application bytes):
***  h1   debug|  Addressable:           00
***  h1   debug|  Partially addressable: 01 02 03 04 05 06 07 
***  h1   debug|  Heap left redzone:       fa
***  h1   debug|  Freed heap region:       fd
***  h1   debug|  Stack left redzone:      f1
***  h1   debug|  Stack mid redzone:       f2
***  h1   debug|  Stack right redzone:     f3
***  h1   debug|  Stack after return:      f5
***  h1   debug|  Stack use after scope:   f8
***  h1   debug|  Global redzone:          f9
***  h1   debug|  Global init order:       f6
***  h1   debug|  Poisoned by user:        f7
***  h1   debug|  Container overflow:      fc
***  h1   debug|  Array cookie:            ac
***  h1   debug|  Intra object redzone:    bb
***  h1   debug|  ASan internal:           fe
***  h1   debug|  Left alloca redzone:     ca
***  h1   debug|  Right alloca redzone:    cb
***  h1   debug|==5957==ABORTING
```

**Comment by wtarreau** [comment]
The code in question does this:
```
        struct buffer tmpbuf;
        struct ssl_sock_ctx *ctx;
        int ret;

        ctx = BIO_get_data(h);
        tmpbuf.size = size;  <<<---- complains about this
        tmpbuf.area = buf;
        tmpbuf.data = 0;
        tmpbuf.head = 0;
```
This is a very standard and basic structure initialization, thus it seems that ASAN doesn't work well on s390x, which is not much surprizing considering it might not be its primary target. I'd suggest to disable it there.

**Comment by chipitsine** [comment]
first it was running without asan enabled

https://travis-ci.com/chipitsine/haproxy/jobs/287617972

**Comment by chipitsine** [comment]
it fails with and without asan

**Comment by wtarreau** [comment]
That's very weird. It got a SIGTERM! And why does only this test fail?
That's a mystery. Note that the abns test is not reliable, it fails for
me ~5% of the time as well. I'm used to issuing another "make regtests"
again two or three times a day on my laptop because of this. Would you
want to run it again (without ASAN) just to be certain it's not a false
positive ?

**Comment by chipitsine** [comment]
I ran it three times. I'll run more tomorrow

**Comment by wtarreau** [comment]
OK. Generally, running it twice is enough. I do it from time to time on
Travis as well because it happens to fail there once in a while as well.
So there's really something in relation with this platform here I'm afraid.

**Comment by chipitsine** [comment]
I do not see a lot of usage of s390x. Maybe we should label this issue as "backlog" and keep it open until someone (motivated in s390x CI) will find a way how to get it running

**Comment by wtarreau** [comment]
On Mon, Feb 17, 2020 at 11:05:43AM -0800, Ilya Shipitsin wrote:
> I do not see a lot of usage of s390x. Maybe we should label this issue as
> "backlog" and keep it open until someone (motivated in s390x CI) will find a
> way how to get it running

Good idea, I'm fine with this approach.

**Comment by TimWolla** [comment]
@chipitsine Can you check whether the fixes for #543 fixed this issue as well?

**Comment by wtarreau** [comment]
@TimWolla excellent idea. I'm just going to revert the patch that disabled it and we'll see. It's cheap enough to test it live, and it's just a regtest, we're not going to break anyone's code with this.

**Comment by chipitsine** [comment]
seems it fixed now
