### ISSUE TITLE
memory leak detected in current master branch

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#506]
https://travis-ci.com/haproxy/haproxy/jobs/287624735#L674

```
***  h1   debug|=================================================================
***  h1   debug|==11701==ERROR: LeakSanitizer: detected memory leaks
***  h1   debug|
***  h1   debug|Direct leak of 48 byte(s) in 1 object(s) allocated from:
**** dT   0.053
***  h1   debug|    #0 0x4de7da in calloc /tmp/final/llvm.src/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:155:3
***  h1   debug|    #1 0x7f8b43 in sample_parse_expr /home/travis/build/haproxy/haproxy/src/sample.c:873:9
***  h1   debug|    #2 0x8d6076 in parse_acl_expr /home/travis/build/haproxy/haproxy/src/acl.c:324:9
***  h1   debug|    #3 0x8d9286 in parse_acl /home/travis/build/haproxy/haproxy/src/acl.c:700:13
***  h1   debug|    #4 0x7269f7 in str2listener /home/travis/build/haproxy/haproxy/src/cfgparse.c:232:2
***  h1   debug|
***  h1   debug|Direct leak of 40 byte(s) in 1 object(s) allocated from:
***  h1   debug|    #0 0x4de7da in calloc /tmp/final/llvm.src/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:155:3
***  h1   debug|    #1 0x77a83d in add_to_logformat_list /home/travis/build/haproxy/haproxy/src/log.c:450:33
***  h1   debug|
***  h1   debug|Direct leak of 7 byte(s) in 1 object(s) allocated from:
***  h1   debug|    #0 0x4c925d in strdup /tmp/final/llvm.src/projects/compiler-rt/lib/asan/asan_interceptors.cc:447:3
***  h1   debug|    #1 0x906c3f in parse_http_set_header /home/travis/build/haproxy/haproxy/src/http_act.c:1245:27
***  h1   debug|
***  h1   debug|Indirect leak of 61 byte(s) in 1 object(s) allocated from:
**** dT   0.054
***  h1   debug|    #0 0x4de7da in calloc /tmp/final/llvm.src/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:155:3
***  h1   debug|    #1 0x77a85a in add_to_logformat_list /home/travis/build/haproxy/haproxy/src/log.c:455:9
***  h1   debug|
***  h1   debug|SUMMARY: AddressSanitizer: 156 byte(s) leaked in 4 allocation(s).
```

**Comment by wtarreau** [comment]
I broke the parser when addressing issue #502 :-(  It's now fixed, and Travis seems to be building OK again. Thanks!
