### ISSUE TITLE
Haproxy crashes with fastcgi

### ISSUE THREAD

**Issue by thorro** [haproxy/haproxy#637]
## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 2.1.4 2020/04/02 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2021.
Known bugs: http://www.haproxy.org/bugs/bugs-2.1.4.html
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O0 -g -fno-strict-aliasing
  OPTIONS = USE_STATIC_PCRE=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_ZLIB=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -REGPARM +STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL -LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.0.1f 6 Jan 2014
Running on OpenSSL version : OpenSSL 1.0.1f 6 Jan 2014
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.31 2012-07-06
Running on PCRE version : 8.31 2012-07-06
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes
Built with zlib version : 1.2.8
Running on zlib version : 1.2.8
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : none

Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[TRACE] trace
	[COMP] compression
```
```
Linux xxxxxx.dev 3.13.0-170-generic #220-Ubuntu SMP Thu May 9 12:40:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

## What's the configuration?

```
global
        log /dev/log    local2
        chroot /var/lib/haproxy
        stats socket /run/haproxy/admin.sock mode 660 level admin
        stats timeout 30s
        user haproxy
        group haproxy
        daemon

        # Default SSL material locations
        ca-base /etc/ssl/certs
        crt-base /etc/ssl/private

        ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS
        ssl-default-bind-options no-sslv3
        tune.ssl.default-dh-param 2048
        maxconn 8192

defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000

backend backend_cdr_integrations_stage
        use-fcgi-app fpm-integrations
        balance roundrobin

        option redispatch
        retries 5
        timeout connect 16s
        timeout queue 120s
        timeout tunnel 78s
        timeout tarpit 63s
        timeout server-fin 75s
        retry-on empty-response conn-failure response-timeout

        timeout server 335s
        server stage  host.stage:30420  proto fcgi check agent-check agent-port 5555 inter 2000 fall 3 maxconn 200 weight 100

backend backend_cdr_integrations2_stage
        use-fcgi-app fpm-integrations
        balance roundrobin

        option redispatch
        retries 5
        timeout connect 16s
        timeout queue 120s
        timeout tunnel 78s
        timeout tarpit 63s
        timeout server-fin 75s

        retry-on empty-response conn-failure response-timeout

        timeout server 335s
        server stage  host.stage:30421  proto fcgi check agent-check agent-port 5555 inter 2000 fall 3 maxconn 200 weight 100


backend backend_cdr_credentialsmanager_stage
        use-fcgi-app fpm-integrations
        balance roundrobin

        option redispatch
        retries 5
        timeout connect 16s
        timeout queue 120s
        timeout tunnel 78s
        timeout tarpit 63s
        timeout server-fin 75s
        retry-on empty-response conn-failure response-timeout

        timeout server 335s
        server stage host.stage:30422 proto fcgi check inter 2000 fall 3 maxconn 200


fcgi-app fpm-integrations
        option keep-conn
        log-stderr global

        docroot /usr/src/integrations-core/delivery
        index index.php
        set-param SCRIPT_NAME /index.php
        path-info ^(/.+\.php)(/.*)?$


```

## Steps to reproduce the behavior

1. start haproxy
2. put some load on it
3. eventually it will crash, mostly in a few minutes time, with "Thread 1 is about to kill the process."
4. same thing happens when using haproxy 2.1.4 or 2.2-rc docker image

## Do you have any idea what may have caused this?

Backtrace follows:

```gdb /usr/sbin/haproxy2.1.4-debug CoreDump
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.3) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/sbin/haproxy2.1.4-debug...done.

warning: core file may not match specified executable file.
[New LWP 751]
[New LWP 752]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/sbin/haproxy2.1 -f /etc/haproxy/haproxy2.1.cfg -d'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f9c0e450c37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) t a a bt full

Thread 2 (Thread 0x7f9c0cffb700 (LWP 752)):
#0  0x00007f9c0e5186d3 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
No locals.
#1  0x000000000040b641 in _do_poll (p=0x9e3560 <cur_poller>, exp=397888072, wake=0) at src/ev_epoll.c:181
        timeout = 16
        status = -1
        fd = -1
        count = 0
        updt_idx = 0
        wait_time = 16
        old_fd = -1
#2  0x000000000052c9d8 in run_poll_loop () at src/haproxy.c:2787
        next = 397888072
        wake = 0
#3  0x000000000052cbb4 in run_thread_poll_loop (data=0x1) at src/haproxy.c:2869
        ptaf = 0x8cdfb0 <per_thread_alloc_list>
        ptif = 0x8cdfc0 <per_thread_init_list>
        ptdf = 0x7f9c0cfd8bb0
        ptff = 0x7f9c0cffb700
        init_left = 0
        init_mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0,
            __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}
        init_cond = {__data = {__lock = 0, __futex = 2, __total_seq = 1, __wakeup_seq = 1, __woken_seq = 1,
            __mutex = 0x8dbe60 <init_mutex>, __nwaiters = 0, __broadcast_seq = 1},
          __size = "\000\000\000\000\002\000\000\000\001\000\000\000\000\000\000\000\001\000\000\000\000\000\000\000\001\000\000\000\000\000\000\000`\276\215\000\000\000\000\000\000\000\000\000\001\000\000", __align = 8589934592}
#4  0x00007f9c0f02f184 in start_thread (arg=0x7f9c0cffb700) at pthread_create.c:312
        __res = <optimized out>
        pd = 0x7f9c0cffb700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140308209710848, -8564605345967066209, 0, 0, 140308209711552,
                140308209710848, 8510801828533285791, 8510808054275683231}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0,
              0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#5  0x00007f9c0e51803d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
No locals.

Thread 1 (Thread 0x7f9c0f8acac0 (LWP 751)):
#0  0x00007f9c0e450c37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
        resultvar = 0
        pid = 751
        selftid = 751
#1  0x00007f9c0e454028 in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x13, sa_sigaction = 0x13}, sa_mask = {__val = {0, 140721075147168,
              140308250256887, 5, 0, 23, 140308230835504, 19, 140721075147168, 8, 140308250285477, 425, 140308243505997, 425,
              27206240, 425}}, sa_flags = 1701015410, sa_restorer = 0x62b7e0 <__FUNCTION__.33468>}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00000000005bcd15 in ha_panic () at src/debug.c:210
No locals.
#3  0x00000000005e870e in wdt_handler (sig=14, si=0x7ffc2db25330, arg=0x7ffc2db25200) at src/wdt.c:119
        n = 3035072349
        p = 677703439
        thr = 0
#4  <signal handler called>
No locals.
#5  trace (level=TRACE_LEVEL_STATE, mask=134234120, src=0x8cb260 <trace_fcgi>, where=..., func=0x0, a1=0x2ad4e40,
    a2=0x2abfbd0, a3=0x2bb1820, a4=0x7ffc2db26120, cb=0x0, msg=...) at include/proto/trace.h:150
No locals.
#6  0x0000000000469629 in fcgi_strm_send_stdin (fconn=0x2b75240, fstrm=0x2abfbd0, htx=0x2bb1820, count=9048, buf=0x2b15968)
    at src/mux_fcgi.c:2249
        outbuf = {size = 4571850, area = 0x4000 <error: Cannot access memory at address 0x4000>, data = 6468219, head = 19}
        mbuf = 0x0
        blk = 0x2bb5818
        type = HTX_BLK_DATA
---Type <return> to continue, or q <return> to quit---
        size = 9048
        total = 0
        __FUNCTION__ = "fcgi_strm_send_stdin"
#7  0x000000000047747a in fcgi_snd_buf (cs=0x2afd7f0, buf=0x2b15968, count=9048, flags=2) at src/mux_fcgi.c:3952
        fstrm = 0x2abfbd0
        fconn = 0x2b75240
        total = 0
        ret = 0
        htx = 0x2bb1820
        sl = 0x63d8cb <__FUNCTION__.34566>
        blk = 0x2bb5818
        bsize = 9048
        __FUNCTION__ = "fcgi_snd_buf"
#8  0x0000000000557a7c in si_cs_send (cs=0x2afd7f0) at src/stream_interface.c:752
        send_flag = 2
        conn = 0x2ad4e40
        si = 0x2b15c50
        oc = 0x2b15960
        ret = 0
        did_send = 0
#9  0x00000000005584aa in stream_int_chk_snd_conn (si=0x2b15c50) at src/stream_interface.c:1136
        oc = 0x2b15960
        cs = 0x2afd7f0
#10 0x0000000000556736 in si_chk_snd (si=0x2b15c50) at include/proto/stream_interface.h:496
No locals.
#11 0x000000000055724a in stream_int_notify (si=0x2b15bf8) at src/stream_interface.c:505
        new_len = 766666288
        last_len = 9048
        ic = 0x2b15960
        oc = 0x2b159c0
        sio = 0x2b15c50
        task = 0x2b4f230
#12 0x00000000005576f6 in si_cs_process (cs=0x2afe1e0) at src/stream_interface.c:639
        conn = 0x2b32ac0
        si = 0x2b15bf8
        ic = 0x2b15960
        oc = 0x2b159c0
#13 0x0000000000557c45 in si_cs_io_cb (t=0x0, ctx=0x2b15bf8, state=1) at src/stream_interface.c:807
        si = 0x2b15bf8
        cs = 0x2afe1e0
        ret = 1
#14 0x000000000059fc6b in process_runnable_tasks () at src/task.c:413
        t = 0x2b15730
        state = 1
        ctx = 0x2b15bf8
        process = 0x557b9a <si_cs_io_cb>
        tt = 0x9e1240 <task_per_thread>
        lrq = 0x0
        grq = 0x0
        t = 0x7ffc2db266e0
        max_processed = 197
        tmp_list = 0x0
#15 0x000000000052c82b in run_poll_loop () at src/haproxy.c:2746
        next = 397885704
        wake = 0
#16 0x000000000052cbb4 in run_thread_poll_loop (data=0x0) at src/haproxy.c:2869
        ptaf = 0x8cdfb0 <per_thread_alloc_list>
        ptif = 0x8cdfc0 <per_thread_init_list>
        ptdf = 0x0
        ptff = 0x0
        init_left = 0
        init_mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0,
            __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}
        init_cond = {__data = {__lock = 0, __futex = 2, __total_seq = 1, __wakeup_seq = 1, __woken_seq = 1,
            __mutex = 0x8dbe60 <init_mutex>, __nwaiters = 0, __broadcast_seq = 1},
          __size = "\000\000\000\000\002\000\000\000\001\000\000\000\000\000\000\000\001\000\000\000\000\000\000\000\001\000\000\000\000\000\000\000`\276\215\000\000\000\000\000\000\000\000\000\001\000\000", __align = 8589934592}
#17 0x000000000052e789 in main (argc=4, argv=0x7ffc2db26bb8) at src/haproxy.c:3603
        blocked_sig = {__val = {18446744067199990583, 18446744073709551615 <repeats 15 times>}}
        old_sig = {__val = {0, 5482510, 9, 140721075153280, 9207128, 140721075153888, 140721075153848, 5511302,
---Type <return> to continue, or q <return> to quit---
            140721075153848, 32, 18446603352634398273, 140720308486147, 0, 270582939696, 140721075153344, 0}}
        i = 2
        err = 0
        retry = 200
        limit = {rlim_cur = 16535, rlim_max = 16535}
        errmsg = "\000|\001\000\000\000\000\000 \000\000\000\000\000\000\000\060\023\237\001\000\000\000\000\270k\262-\374\177\000\000\004\000\000\000\000\000\000\000\374\325I\016\234\177\000\000\000\000\000\000\000\000\000\000\t\000\000\000\000\000\000\000pj\262-\374\177\000\000X}\214\000\000\000\000\000\340k\262-\374\177\000\000\003dR\000\000\000\000\000\000\000\000"
        pidfd = -1
(gdb)
```

**Comment by capflam** [comment]
I pushed a patch that should fix this bug. If possible, it could be good to confirm it fixes your issue. The patch should apply on the 2.1 without any conflict. Thanks !

**Comment by thorro** [comment]
@capflam we've done some testing, no crashes. Thanks for the fast resolution.

**Comment by capflam** [comment]
Cool. Thanks for the confirmation !
