### ISSUE TITLE
reg-tests/checks/spop-check.vtc: global-buffer-overflow found by gcc10 asan

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#687]
```
***  h1   debug|==434227==ERROR: AddressSanitizer: global-buffer-overflow on address 0x0000008f77e8 at pc 0x7fa2673633f0 bp 0x7fa25eae7a40 sp 0x7fa25eae71e8
***  h1   debug|READ of size 14 at 0x0000008f77e8 thread T3
**** dT   0.189
***  h1   debug|    #0 0x7fa2673633ef  (/lib64/libasan.so.6+0x903ef)
***  h1   debug|    #1 0x7fa267363b26 in memcmp (/lib64/libasan.so.6+0x90b26)
**** dT   0.192
***  h1   debug|    #2 0x6c391f in spoe_handle_agenthello_frame src/flt_spoe.c:685
***  h1   debug|    #3 0x6d672f in spoe_handle_healthcheck_response src/flt_spoe.c:1107
**** dT   0.195
***  h1   debug|    #4 0x66f9a5 in tcpcheck_spop_expect_agenthello src/tcpcheck.c:728
***  h1   debug|    #5 0x6793ff in tcpcheck_eval_expect src/tcpcheck.c:1856
***  h1   debug|    #6 0x67aa71 in tcpcheck_main src/tcpcheck.c:2063
**** dT   0.198
***  h1   debug|    #7 0x60a557 in wake_srv_chk src/check.c:780
***  h1   debug|    #8 0x60afd3 in event_srv_chk_io src/check.c:831
**** dT   0.199
***  h1   debug|    #9 0x7e9994 in run_tasks_from_list src/task.c:345
***  h1   debug|    #10 0x7ea583 in process_runnable_tasks src/task.c:446
**** dT   0.200
***  h1   debug|    #11 0x726086 in run_poll_loop src/haproxy.c:2879
***  h1   debug|    #12 0x726891 in run_thread_poll_loop src/haproxy.c:3051
**** dT   0.201
***  h1   debug|    #13 0x7fa267253431 in start_thread /usr/src/debug/glibc-2.31-17-gab029a2801/nptl/pthread_create.c:477
**** dT   0.278
***  h1   debug|    #14 0x7fa2666499d2 in __clone (/lib64/libc.so.6+0x1019d2)
***  h1   debug|
***  h1   debug|0x0000008f77e8 is located 0 bytes to the right of global variable '*.LC132' defined in 'src/flt_spoe.c' (0x8f77e0) of size 8
***  h1   debug|  '*.LC132' is ascii string 'version'
***  h1   debug|0x0000008f77e8 is located 56 bytes to the left of global variable '*.LC133' defined in 'src/flt_spoe.c' (0x8f7820) of size 13
***  h1   debug|  '*.LC133' is ascii string 'capabilities'
***  h1   debug|SUMMARY: AddressSanitizer: global-buffer-overflow (/lib64/libasan.so.6+0x903ef) 
**** dT   0.279
***  h1   debug|Shadow bytes around the buggy address:
***  h1   debug|  0x000080116ea0: 00 00 03 f9 f9 f9 f9 f9 00 00 00 00 00 00 00 04
***  h1   debug|  0x000080116eb0: f9 f9 f9 f9 04 f9 f9 f9 f9 f9 f9 f9 00 00 00 03
***  h1   debug|  0x000080116ec0: f9 f9 f9 f9 00 00 00 00 00 00 00 07 f9 f9 f9 f9
***  h1   debug|  0x000080116ed0: 00 00 00 00 00 02 f9 f9 f9 f9 f9 f9 00 04 f9 f9
***  h1   debug|  0x000080116ee0: f9 f9 f9 f9 00 f9 f9 f9 f9 f9 f9 f9 04 f9 f9 f9
***  h1   debug|=>0x000080116ef0: f9 f9 f9 f9 04 f9 f9 f9 f9 f9 f9 f9 00[f9]f9 f9
***  h1   debug|  0x000080116f00: f9 f9 f9 f9 00 05 f9 f9 f9 f9 f9 f9 00 06 f9 f9
***  h1   debug|  0x000080116f10: f9 f9 f9 f9 04 f9 f9 f9 f9 f9 f9 f9 05 f9 f9 f9
***  h1   debug|  0x000080116f20: f9 f9 f9 f9 00 f9 f9 f9 f9 f9 f9 f9 06 f9 f9 f9
***  h1   debug|  0x000080116f30: f9 f9 f9 f9 07 f9 f9 f9 f9 f9 f9 f9 04 f9 f9 f9
***  h1   debug|  0x000080116f40: f9 f9 f9 f9 05 f9 f9 f9 f9 f9 f9 f9 00 f9 f9 f9
***  h1   debug|Shadow byte legend (one shadow byte represents 8 application bytes):
***  h1   debug|  Addressable:           00
***  h1   debug|  Partially addressable: 01 02 03 04 05 06 07 
***  h1   debug|  Heap left redzone:       fa
***  h1   debug|  Freed heap region:       fd
***  h1   debug|  Stack left redzone:      f1
***  h1   debug|  Stack mid redzone:       f2
***  h1   debug|  Stack right redzone:     f3
***  h1   debug|  Stack after return:      f5
***  h1   debug|  Stack use after scope:   f8
***  h1   debug|  Global redzone:          f9
***  h1   debug|  Global init order:       f6
***  h1   debug|  Poisoned by user:        f7
***  h1   debug|  Container overflow:      fc
***  h1   debug|  Array cookie:            ac
***  h1   debug|  Intra object redzone:    bb
***  h1   debug|  ASan internal:           fe
***  h1   debug|  Left alloca redzone:     ca
***  h1   debug|  Right alloca redzone:    cb
***  h1   debug|  Shadow gap:              cc
***  h1   debug|Thread T3 created by T0 here:
**** dT   0.280
***  h1   debug|    #0 0x7fa26732abe5 in __interceptor_pthread_create (/lib64/libasan.so.6+0x57be5)
***  h1   debug|    #1 0x72c133 in main src/haproxy.c:3704
***  h1   debug|
***  s2   accepted fd 7 127.0.0.1 59984
**   s2   === recv 82
**** s2   recv|\x00\x00\x00N\x01\x00\x00\x00\x01\x00\x00\x12supported-versions\x08\x03
**** s2   recv|2.0\x0emax-frame-size\x03\xfc\xf0\x06\x0ccapabilit
**** s2   recv|ies\x08\x00\vhealthcheck\x11
**   s2   === sendhex "00000000"
**** s2   sendhex|  00 00 00 00
***  s2   shutting fd 7
**   s2   Ending
***  h1   debug|==434227==ABORTING

```

**Comment by TimWolla** [comment]
While VTest is not terribly happy with a valgrind wrapped HAProxy (it appears to die to signal 9 instead of cleanly exiting) I am not seeing anything with valgrind for your gcc10 asan issues. And I honestly trust valgrind more than ASAN by now:

```
$ ./valgrind-proxy -vv
==14983== Memcheck, a memory error detector
==14983== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==14983== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==14983== Command: *snip*/haproxy -vv
==14983== 
HA-Proxy version 2.2-dev9-8469be-10 2020/06/13 - https://haproxy.org/
Status: development branch - not safe for use in production.
Known bugs: https://github.com/haproxy/haproxy/issues?q=is:issue+is:open
Running on: Linux 4.4.0-184-generic #214-Ubuntu SMP Thu Jun 4 10:14:11 UTC 2020 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
  OPTIONS = 

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO -OPENSSL -LUA +FUTEX +ACCEPT4 -ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=4).
Built with network namespace support.
Built with gcc compiler version 5.4.0 20160609
Built without compression support (neither USE_ZLIB nor USE_SLZ are set).
Compression algorithms supported : identity("identity")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built without PCRE or PCRE2 support (using libc's regex instead)
Encrypted password support via crypt(3): yes

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : none

Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace
	[CACHE] cache
	[FCGI] fcgi-app

==14983== 
==14983== HEAP SUMMARY:
==14983==     in use at exit: 1,100,562 bytes in 90 blocks
==14983==   total heap usage: 108 allocs, 18 frees, 1,107,849 bytes allocated
==14983== 
==14983== LEAK SUMMARY:
==14983==    definitely lost: 0 bytes in 0 blocks
==14983==    indirectly lost: 0 bytes in 0 blocks
==14983==      possibly lost: 0 bytes in 0 blocks
==14983==    still reachable: 1,100,562 bytes in 90 blocks
==14983==         suppressed: 0 bytes in 0 blocks
==14983== Rerun with --leak-check=full to see details of leaked memory
==14983== 
==14983== For counts of detected and suppressed errors, rerun with: -v
==14983== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

```
$ *snip*VTest/vtest -b 2097152 -k -t 50 -Dno-htx= -l -v reg-tests/checks/spop-check.vtc |grep debug
***  h1   debug|==15058== Memcheck, a memory error detector
***  h1   debug|==15058== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
***  h1   debug|==15058== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
***  h1   debug|==15058== Command: *snip*/haproxy -d -f /tmp/vtc.15044.14bd981e/h1/cfg
***  h1   debug|==15058== 
***  h1   debug|Note: setting global.maxconn to 492.
***  h1   debug|Available polling systems :
***  h1   debug|      epoll : 
***  h1   debug|pref=300, 
***  h1   debug| test result OK
***  h1   debug|
1 tests failed, 0 tests skipped, 0 tests passed
***  h1   debug|       poll : 
***  h1   debug|pref=200, 
***  h1   debug| test result OK
***  h1   debug|
***  h1   debug|     select : 
***  h1   debug|pref=150, 
***  h1   debug| test result OK
***  h1   debug|
***  h1   debug|Total: 3 (3 usable), will use epoll.
***  h1   debug|
***  h1   debug|Available filters :
***  h1   debug|\t[SPOE] spoe
***  h1   debug|\t[COMP] compression
***  h1   debug|\t[TRACE] trace
***  h1   debug|\t[CACHE] cache
***  h1   debug|\t[FCGI] fcgi-app
***  h1   debug|Using epoll() as the polling mechanism.
***  h1   debug|00000000:spop1.accept(0011)=001e from [127.0.0.1:36528] ALPN=<none>
***  h1   debug|[WARNING] 164/233429 (15058) : Health check for server be2/srv failed, reason: Layer7 invalid response, info: "invalid frame received", check duration: 17ms, status: 0/1 DOWN.
***  h1   debug|[WARNING] 164/233429 (15058) : Server be2/srv is DOWN. 0 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
***  h1   debug|[NOTICE] 164/233429 (15058) : haproxy version is 2.2-dev9-8469be-10
***  h1   debug|[NOTICE] 164/233429 (15058) : path to executable is *snip*/haproxy
***  h1   debug|[ALERT] 164/233429 (15058) : backend 'be2' has no server available!
***  h1   debug|[WARNING] 164/233429 (15058) : Health check for server be1/srv succeeded, reason: Layer7 check passed, code: 0, info: "SPOA server is ok", check duration: 243ms, status: 1/1 UP.
***  h1   debug|00000000:spop1.srvcls[adfd:adfd]
***  h1   debug|00000000:spop1.clicls[adfd:adfd]
***  h1   debug|00000000:spop1.closed[adfd:adfd]
***  h1   debug|[WARNING] 164/233429 (15058) : Health check for server be3/srv failed, reason: Layer7 invalid response, info: "fragmentation not supported", check duration: 0ms, status: 0/1 DOWN.
***  h1   debug|[WARNING] 164/233429 (15058) : Server be3/srv is DOWN. 0 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
***  h1   debug|[ALERT] 164/233429 (15058) : backend 'be3' has no server available!
***  h1   debug|[WARNING] 164/233429 (15058) : Health check for server be4/srv failed, reason: Layer7 invalid response, info: "unsupported version", check duration: 9ms, status: 0/1 DOWN.
***  h1   debug|[WARNING] 164/233429 (15058) : Server be4/srv is DOWN. 0 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
***  h1   debug|[ALERT] 164/233429 (15058) : backend 'be4' has no server available!
***  h1   debug|==15058== 
***  h1   debug|==15058== Process terminating with default action of signal 2 (SIGINT)
***  h1   debug|==15058==    at 0x57A2A13: ??? (syscall-template.S:84)
***  h1   debug|==15058==    by 0x41B3F8: _do_poll (ev_epoll.c:180)
***  h1   debug|==15058==    by 0x507EFE: run_poll_loop (haproxy.c:2933)
***  h1   debug|==15058==    by 0x50833E: run_thread_poll_loop (haproxy.c:3051)
***  h1   debug|==15058==    by 0x41900C: main (haproxy.c:3753)
***  h1   debug|==15058== 
***  h1   debug|==15058== HEAP SUMMARY:
***  h1   debug|==15058==     in use at exit: 2,179,808 bytes in 363 blocks
***  h1   debug|==15058==   total heap usage: 449 allocs, 86 frees, 2,300,540 bytes allocated
***  h1   debug|==15058== 
***  h1   debug|==15058== LEAK SUMMARY:
***  h1   debug|==15058==    definitely lost: 0 bytes in 0 blocks
***  h1   debug|==15058==    indirectly lost: 0 bytes in 0 blocks
***  h1   debug|==15058==      possibly lost: 1,352 bytes in 10 blocks
***  h1   debug|==15058==    still reachable: 2,178,456 bytes in 353 blocks
***  h1   debug|==15058==         suppressed: 0 bytes in 0 blocks
***  h1   debug|==15058== Rerun with --leak-check=full to see details of leaked memory
***  h1   debug|==15058== 
***  h1   debug|==15058== For counts of detected and suppressed errors, rerun with: -v
***  h1   debug|==15058== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

**Comment by wtarreau** [comment]
duplicate of #689
