### ISSUE TITLE
reg-tests/checks/mysql-check.vtc: heap-buffer-overflow found by gcc10 asan

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#688]
```
***  h1   debug|==433251==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6020000001dd at pc 0x7efd867dc59e bp 0x7ffeae1f31d0 sp 0x7ffeae1f2978
***  h1   debug|READ of size 14 at 0x6020000001dd thread T0
**** dT   1.508
***  h1   debug|    #0 0x7efd867dc59d  (/lib64/libasan.so.6+0x9059d)
***  h1   debug|    #1 0x7efd867dcb26 in memcmp (/lib64/libasan.so.6+0x90b26)
**** dT   1.509
***  h1   debug|    #2 0x865bdf in __ebim_lookup include/import/ebimtree.h:65
***  h1   debug|    #3 0x865bdf in ebim_lookup src/ebimtree.c:32
**** dT   1.520
***  h1   debug|    #4 0x66e279 in ebis_lookup_len include/import/ebistree.h:51
***  h1   debug|    #5 0x66e279 in find_tcpcheck_ruleset src/tcpcheck.c:295
**** dT   1.528
***  h1   debug|    #6 0x615658 in proxy_parse_mysql_check_opt src/check.c:2207
**** dT   1.533
***  h1   debug|    #7 0x594065 in cfg_parse_listen src/cfgparse-listen.c:2284
**** dT   1.538
***  h1   debug|    #8 0x55eb23 in readcfgfile src/cfgparse.c:2167
**** dT   1.540
***  h1   debug|    #9 0x729086 in init src/haproxy.c:2021
***  h1   debug|    #10 0x729086 in main src/haproxy.c:3121
**** dT   1.542
***  h1   debug|    #11 0x7efd859e8041 in __libc_start_main ../csu/libc-start.c:308
***  h1   debug|    #12 0x4244ed in _start (/home/ilia/haproxy/haproxy+0x4244ed)
***  h1   debug|
***  h1   debug|0x6020000001dd is located 0 bytes to the right of 13-byte region [0x6020000001d0,0x6020000001dd)
***  h1   debug|allocated by thread T0 here:
***  h1   debug|    #0 0x7efd867a63a7 in strdup (/lib64/libasan.so.6+0x5a3a7)
***  h1   debug|    #1 0x66e2fd in create_tcpcheck_ruleset src/tcpcheck.c:314
***  h1   debug|
***  h1   debug|SUMMARY: AddressSanitizer: heap-buffer-overflow (/lib64/libasan.so.6+0x9059d) 
***  h1   debug|Shadow bytes around the buggy address:
***  h1   debug|  0x0c047fff7fe0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
***  h1   debug|  0x0c047fff7ff0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
***  h1   debug|  0x0c047fff8000: fa fa 00 fa fa fa 00 04 fa fa 00 03 fa fa 07 fa
***  h1   debug|  0x0c047fff8010: fa fa 07 fa fa fa 05 fa fa fa 00 07 fa fa 00 fa
***  h1   debug|  0x0c047fff8020: fa fa 07 fa fa fa 06 fa fa fa fd fa fa fa fd fa
***  h1   debug|=>0x0c047fff8030: fa fa 04 fa fa fa fd fd fa fa 00[05]fa fa 04 fa
***  h1   debug|  0x0c047fff8040: fa fa fd fd fa fa 04 fa fa fa fd fd fa fa 04 fa
***  h1   debug|  0x0c047fff8050: fa fa 05 fa fa fa 00 04 fa fa 00 06 fa fa fa fa
***  h1   debug|  0x0c047fff8060: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
***  h1   debug|  0x0c047fff8070: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
***  h1   debug|  0x0c047fff8080: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
***  h1   debug|Shadow byte legend (one shadow byte represents 8 application bytes):
***  h1   debug|  Addressable:           00
***  h1   debug|  Partially addressable: 01 02 03 04 05 06 07 
***  h1   debug|  Heap left redzone:       fa
***  h1   debug|  Freed heap region:       fd
***  h1   debug|  Stack left redzone:      f1
***  h1   debug|  Stack mid redzone:       f2
***  h1   debug|  Stack right redzone:     f3
***  h1   debug|  Stack after return:      f5
***  h1   debug|  Stack use after scope:   f8
***  h1   debug|  Global redzone:          f9
***  h1   debug|  Global init order:       f6
***  h1   debug|  Poisoned by user:        f7
***  h1   debug|  Container overflow:      fc
***  h1   debug|  Array cookie:            ac
***  h1   debug|  Intra object redzone:    bb
***  h1   debug|  ASan internal:           fe
***  h1   debug|  Left alloca redzone:     ca
***  h1   debug|  Right alloca redzone:    cb
***  h1   debug|  Shadow gap:              cc
***  h1   debug|==433251==ABORTING

```

**Comment by wtarreau** [comment]
duplicate of #689
