### ISSUE TITLE
HAproxy dead: thread stuck process_chk

### ISSUE THREAD

**Issue by matuszabojnik** [haproxy/haproxy#871]
## Detailed description of the problem
HAProxy dies randomly: thread stuck killing HAProxy (we are using multiple machines with the same setup and some machines are more prone to getting stuck than others). This happens after some time of being UP (not immediately after start). This happens also under no load.

## Expected behavior
HAProxy process should not die.

## Do you have any idea what may have caused this?
Network latency might be involved.

## What is your configuration?

```
global
  maxconn 2000
  log 127.0.0.1:514  local0  info
  tune.ssl.default-dh-param 2048
  spread-checks 20

defaults
  log global
  mode tcp
  retries 5
  timeout client 30m
  timeout connect 60s
  timeout server 30m
  timeout check 30s

listen stats
  mode http
  bind *:7000 ssl crt /usr/local/etc/haproxy/haproxy.pem force-tlsv12
  stats enable
  stats uri /
  stats auth admin:<PW>

listen postgres
  bind *:5000
  option httpchk
  http-check send meth GET
  http-check expect status 200
  default-server inter 30s fall 2 rise 1 on-marked-down shutdown-sessions
  server <SERVER1> <IP1>:5432 maxconn 2000 check port 8008 check-ssl ca-file /usr/local/etc/haproxy/truststore.crt verify required
    server <SERVER2> <IP2>:5432 maxconn 2000 check port 8008 check-ssl ca-file /usr/local/etc/haproxy/truststore.crt verify required
    server <SERVER3> <IP3>:5432 maxconn 2000 check port 8008 check-ssl ca-file /usr/local/etc/haproxy/truststore.crt verify required
    server <SERVER4> <IP4>:5432 maxconn 2000 check port 8008 check-ssl ca-file /usr/local/etc/haproxy/truststore.crt verify required
    server <SERVER5> <IP5>:5432 maxconn 2000 check port 8008 check-ssl ca-file /usr/local/etc/haproxy/truststore.crt verify required
    server <SERVER6> <IP6>:5432 maxconn 2000 check port 8008 check-ssl ca-file /usr/local/etc/haproxy/truststore.crt verify required

```

## Output of `haproxy -vv` and `uname -a`

```
Linux swa-cr-postgres2 3.10.0-957.5.1.el7.x86_64 #1 SMP Wed Dec 19 10:46:58 EST 2018 x86_64 GNU/Linux
```

```
HA-Proxy version 2.2.3-0e58a34 2020/09/08 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.3.html
Running on: Linux 3.10.0-957.5.1.el7.x86_64 #1 SMP Wed Dec 19 10:46:58 EST 2018 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=16).
Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.3.0
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services :
	prometheus-exporter

Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace
	[CACHE] cache
	[FCGI] fcgi-app

```

## If HAProxy crashed: Last outputs and backtraces

```
Thread 6 is about to kill the process.
  Thread 1 : id=0x7fe37918a200 act=0 glob=0 wq=0 rq=0 tl=0 tlsz=0 rqsz=0
             stuck=0 prof=0 harmless=1 wantrdv=0
             cpu_ns: poll=386397653 now=446659561 diff=60261908
             curr_task=0
  Thread 2 : id=0x7fe378b6a700 act=1 glob=1 wq=0 rq=0 tl=0 tlsz=0 rqsz=0
             stuck=0 prof=0 harmless=1 wantrdv=0
             cpu_ns: poll=470965204 now=899266638 diff=428301434
             curr_task=0
  Thread 3 : id=0x7fe378369700 act=1 glob=1 wq=0 rq=0 tl=0 tlsz=0 rqsz=0
             stuck=0 prof=0 harmless=1 wantrdv=0
             cpu_ns: poll=230767487 now=536337260 diff=305569773
             curr_task=0
  Thread 4 : id=0x7fe377b68700 act=1 glob=1 wq=0 rq=0 tl=0 tlsz=0 rqsz=0
             stuck=0 prof=0 harmless=1 wantrdv=0
             cpu_ns: poll=166457040 now=992112825 diff=825655785
             curr_task=0
  Thread 5 : id=0x7fe377367700 act=1 glob=1 wq=1 rq=0 tl=0 tlsz=0 rqsz=0
             stuck=0 prof=0 harmless=1 wantrdv=0
             cpu_ns: poll=217459480 now=1629304560 diff=1411845080
             curr_task=0
*>Thread 6 : id=0x7fe376b66700 act=1 glob=0 wq=0 rq=0 tl=0 tlsz=0 rqsz=0
             stuck=1 prof=0 harmless=0 wantrdv=0
             cpu_ns: poll=189090504 now=4588522138 diff=4399431634
             curr_task=0x562bfb677000 (task) calls=21 last=0
               fct=0x562bf9c63320(process_chk) ctx=0x562bfb5e9a50

             call trace(39):
             | 0x562bf9d330f7 [48 83 c4 10 5b 5d 41 5c]: wdt_handler+0x107/0x114
             | 0x7fe379966730 [48 c7 c0 0f 00 00 00 0f]: libpthread:+0x12730
             | 0x7fe379764eca [2b 41 14 75 11 85 d2 74]: libcrypto:+0x198eca
             | 0x7fe379765582 [85 c0 79 ca 45 89 fd 45]: libcrypto:OBJ_bsearch_ex_+0x72/0x11f
             | 0x7fe3797656e2 [48 85 c0 75 11 66 0f 1f]: libcrypto:OBJ_obj2nid+0xa2/0xd0
             | 0x7fe37966e724 [85 c0 74 78 89 c7 e8 b1]: libcrypto:+0xa2724
             | 0x7fe37967c3f1 [48 85 c0 74 3a 66 2e 0f]: libcrypto:+0xb03f1
             | 0x7fe37967d13c [41 5a 41 5b e9 cd f7 ff]: libcrypto:+0xb113c
             | 0x7fe37967d5b1 [48 83 c4 20 85 c0 74 47]: libcrypto:+0xb15b1
             | 0x7fe37967d849 [5a 59 eb c3 0f 1f 00 41]: libcrypto:+0xb1849
             | 0x7fe37967cef2 [5a 59 85 c0 0f 84 8f 03]: libcrypto:+0xb0ef2
             | 0x7fe37967d5b1 [48 83 c4 20 85 c0 74 47]: libcrypto:+0xb15b1
             | 0x7fe37967d849 [5a 59 eb c3 0f 1f 00 41]: libcrypto:+0xb1849
             | 0x7fe37967cef2 [5a 59 85 c0 0f 84 8f 03]: libcrypto:+0xb0ef2
             | 0x7fe37967d5b1 [48 83 c4 20 85 c0 74 47]: libcrypto:+0xb15b1
             | 0x7fe37967d849 [5a 59 eb c3 0f 1f 00 41]: libcrypto:+0xb1849
             | 0x7fe37967cef2 [5a 59 85 c0 0f 84 8f 03]: libcrypto:+0xb0ef2
             | 0x7fe37967d5b1 [48 83 c4 20 85 c0 74 47]: libcrypto:+0xb15b1
             | 0x7fe37967d7b5 [5e 5f 85 c0 0f 84 51 01]: libcrypto:+0xb17b5
             | 0x7fe37967cef2 [5a 59 85 c0 0f 84 8f 03]: libcrypto:+0xb0ef2
             | 0x7fe37967d94d [48 83 c4 20 85 c0 7e 0b]: libcrypto:ASN1_item_ex_d2i+0x1d/0x4a
             | 0x7fe37967d9cb [5a 31 d2 59 85 c0 7e 03]: libcrypto:ASN1_item_d2i+0x4b/0x74
             | 0x7fe3798eb62b [48 89 c5 48 85 c0 0f 84]: libssl:d2i_SSL_SESSION+0x3b/0x505
             | 0x562bf9bb521c [49 89 c6 48 85 c0 74 1c]: main+0xdbac
             | 0x562bf9d0ee3b [85 c0 0f 88 fd 05 00 00]: tcp_connect_server+0x50b/0xdd2
             | 0x562bf9c8a67a [41 89 c7 85 c0 0f 85 cb]: tcpcheck_eval_connect+0x87a/0x2240
             | 0x562bf9c8ef8b [48 8b 6b 38 48 85 ed 0f]: tcpcheck_main+0x3cb/0xa91
             | 0x562bf9c638c1 [48 8b 8b 68 01 00 00 e9]: process_chk+0x5a1/0x16fe
  Thread 7 : id=0x7fe376365700 act=1 glob=1 wq=0 rq=0 tl=0 tlsz=0 rqsz=0
             stuck=0 prof=0 harmless=1 wantrdv=0
             cpu_ns: poll=287691819 now=1377941132 diff=1090249313
             curr_task=0
  Thread 8 : id=0x7fe375b64700 act=1 glob=1 wq=0 rq=0 tl=0 tlsz=0 rqsz=0
             stuck=0 prof=0 harmless=0 wantrdv=0
             cpu_ns: poll=489566604 now=1716420643 diff=1226854039
             curr_task=0
  Thread 9 : id=0x7fe375363700 act=1 glob=1 wq=0 rq=0 tl=0 tlsz=0 rqsz=0
             stuck=0 prof=0 harmless=1 wantrdv=0
             cpu_ns: poll=164603395 now=1712514751 diff=1547911356
             curr_task=0
  Thread 10: id=0x7fe374b62700 act=0 glob=0 wq=0 rq=0 tl=0 tlsz=0 rqsz=0
             stuck=0 prof=0 harmless=1 wantrdv=0
             cpu_ns: poll=809016203 now=3372009146 diff=2562992943
             curr_task=0
  Thread 11: id=0x7fe36ffff700 act=1 glob=1 wq=0 rq=0 tl=0 tlsz=0 rqsz=0
             stuck=0 prof=0 harmless=1 wantrdv=0
             cpu_ns: poll=198059740 now=2640338221 diff=2442278481
             curr_task=0
  Thread 12: id=0x7fe36f7fe700 act=0 glob=0 wq=0 rq=0 tl=0 tlsz=0 rqsz=0
             stuck=0 prof=0 harmless=1 wantrdv=0
             cpu_ns: poll=959683915 now=3178067908 diff=2218383993
             curr_task=0
  Thread 13: id=0x7fe36effd700 act=1 glob=1 wq=0 rq=0 tl=0 tlsz=0 rqsz=0
             stuck=0 prof=0 harmless=1 wantrdv=0
             cpu_ns: poll=149322616 now=1630785610 diff=1481462994
             curr_task=0
  Thread 14: id=0x7fe36e7fc700 act=1 glob=1 wq=0 rq=0 tl=0 tlsz=0 rqsz=0
             stuck=0 prof=0 harmless=1 wantrdv=0
             cpu_ns: poll=254002999 now=1514116857 diff=1260113858
             curr_task=0
  Thread 15: id=0x7fe36dffb700 act=0 glob=0 wq=0 rq=0 tl=0 tlsz=0 rqsz=0
             stuck=0 prof=1 harmless=1 wantrdv=0
             cpu_ns: poll=305542671 now=1850442040 diff=1544899369
             curr_task=0
  Thread 16: id=0x7fe36d7fa700 act=0 glob=0 wq=0 rq=0 tl=0 tlsz=0 rqsz=0
             stuck=0 prof=0 harmless=1 wantrdv=0
             cpu_ns: poll=482355205 now=2074328365 diff=1591973160
             curr_task=0
[NOTICE] 265/142116 (1) : haproxy version is 2.2.3-0e58a34
[NOTICE] 265/142116 (1) : path to executable is /usr/local/sbin/haproxy
[ALERT] 265/142116 (1) : Current worker #1 (9) exited with code 134 (Aborted)
[ALERT] 265/142116 (1) : exit-on-failure: killing every processes with SIGTERM
[WARNING] 265/142116 (1) : All workers exited. Exiting... (134)

```

**Comment by wtarreau** [comment]
I'm very curious to know what libcrypto could be doing, eating that much time! If you have a core file, it would be nice to pass it under gdb and issue "t a a bt full" to get a more precise backtrace (hoping gdb will better decode libcrypto's symbols).

**Comment by capflam** [comment]
I'm closing this issue. Feel free to reopen it if necessary. Thanks !

**Comment by ObieBent** [comment]
Hello, I'm reopening this thread because I'm facing the same issue. 
I have no idea why _EVP_CIPHER_CTX_reset_ is clearing all information from  its cipher context. 
Seems like there is no local variables for the frames related to **libcrypto**. 

```
HA-Proxy version 2.1.11-9da7aab 2021/01/08 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2021.
Known bugs: http://www.haproxy.org/bugs/bugs-2.1.11.html
Running on: Linux 5.6.6-300.fc32.x86_64 #1 SMP Tue Apr 21 13:44:19 UTC 2020 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_REGPARM=1 USE_LINUX_TPROXY=1 USE_CRYPT_H=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT +PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +BACKTRACE +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.1i FIPS  8 Dec 2020
Running on OpenSSL version : OpenSSL 1.1.1k  FIPS 25 Mar 2021
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.5
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.36 2020-12-04
PCRE2 library supports JIT : no (USE_PCRE2_JIT not set)
Encrypted password support via crypt(3): yes
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services :
	prometheus-exporter

Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[TRACE] trace
	[COMP] compression
```

```
(gdb) t a a bt full

Thread 1 (Thread 0x7fc47ac91140 (LWP 4036250)):
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {18446744067195533847, 0 <repeats 15 times>}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007fc47ae67895 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x1, sa_sigaction = 0x1}, sa_mask = {__val = {0, 18446744067267100671, 18446744073709551615 <repeats 12 times>, 140481860757796, 18446744073709551615}}, sa_flags = 1208, sa_restorer = 0x55a10214c100}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x000055a100da2ed2 in ha_panic () at src/debug.c:267
No locals.
#3  <signal handler called>
No locals.
#4  EVP_CIPHER_CTX_reset (c=0x55a102229430) at crypto/evp/evp_enc.c:35
No locals.
#5  EVP_CIPHER_CTX_reset (c=0x55a102229430) at crypto/evp/evp_enc.c:25
No locals.
#6  0x00007fc47b45bcbd in EVP_CIPHER_CTX_free (ctx=0x55a102229430) at crypto/evp/evp_enc.c:63
No locals.
#7  0x00007fc47b49d53c in drbg_ctr_uninstantiate (drbg=0x55a102224b30) at crypto/rand/drbg_ctr.c:396
No locals.
#8  0x00007fc47b49e60c in RAND_DRBG_free (drbg=0x55a102224b30) at crypto/rand/drbg_lib.c:274
No locals.
#9  0x00007fc47b49f870 in drbg_delete_thread_state () at crypto/rand/drbg_lib.c:960
        drbg = <optimized out>
#10 0x00007fc47b46f0b5 in ossl_init_thread_stop (locals=0x55a10212c8b0) at crypto/init.c:446
--Type <RET> for more, q to quit, c to continue without paging--
No locals.
#11 0x00007fc47b46f36f in OPENSSL_cleanup () at crypto/init.c:72
        currhandler = <optimized out>
        lasthandler = <optimized out>
        key = 32708
#12 OPENSSL_cleanup () at crypto/init.c:497
        currhandler = <optimized out>
        lasthandler = <optimized out>
        key = <optimized out>
#13 0x00007fc47ae81197 in __run_exit_handlers (status=134, listp=0x7fc47b005578 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:108
        atfct = <optimized out>
        onfct = <optimized out>
        cxafct = <optimized out>
        f = <optimized out>
        new_exitfn_called = 3
        cur = 0x7fc47b007960 <initial>
#14 0x00007fc47ae81340 in __GI_exit (status=<optimized out>) at exit.c:139
No locals.
#15 0x000055a100d90f6b in mworker_catch_sigchld (sh=<optimized out>) at src/mworker.c:327
        exitpid = -1
        status = 134
        childfound = 0
#16 0x000055a100db4c5b in __signal_process_queue () at src/signal.c:90
        sh = <optimized out>
        shb = 0x55a100f919e0 <signal_state+416>
        sig = 17
        cur_pos = 0
        desc = 0x55a100f919d8 <signal_state+408>
        old_sig = {__val = {0, 0, 4294967295, 18446744073709508336, 1, 140481852908709, 94150013956688, 14--Type <RET> for more, q to quit, c to continue without paging--
0724985559952, 18446744073709508344, 94149991071323, 94149994269536, 94149994427520, 18446744073709508344, 140724985559952, 10968608, 907847117}}
#17 0x000055a100d40f3f in signal_process_queue () at include/proto/signal.h:39
No locals.
#18 run_poll_loop () at src/haproxy.c:2847
        next = <optimized out>
        wake = <optimized out>
#19 0x000055a100d41141 in run_thread_poll_loop (data=<optimized out>) at src/haproxy.c:2977
        ptaf = <optimized out>
        ptif = <optimized out>
        ptdf = <optimized out>
        ptff = <optimized out>
        init_left = 0
        init_mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}
        init_cond = {__data = {{__wseq = 0, __wseq32 = {__low = 0, __high = 0}}, {__g1_start = 0, __g1_start32 = {__low = 0, __high = 0}}, __g_refs = {0, 0}, __g_size = {0, 0}, __g1_orig_size = 0, __wrefs = 0, __g_signals = {0, 0}}, __size = '\000' <repeats 47 times>, __align = 0}
#20 0x000055a100c5e073 in main (argc=<optimized out>, argv=<optimized out>) at src/haproxy.c:3465
        px = <optimized out>
        ret = <optimized out>
        proc = <optimized out>
        curpeers = <optimized out>
        devnullfd = -1
        err = <optimized out>
        retry = <optimized out>
        limit = {rlim_cur = 40039, rlim_max = 524288}
        errmsg = "\000\000\000\000\060\000\000\000n\000\000\000|", '\000' <repeats 11 times>, "[\000\000\000w", '\000' <repeats 27 times>, " #\000\000\000\000\000\000\340Y\000{\304\177\000\000 \000\000\000\000\00--Type <RET> for more, q to quit, c to continue without paging--
0\000\000\340\254\024\002\241U\000\000p\201\306\026\375\177\000\000p\277", <incomplete sequence \344>
        pidfd = 15
```

**Comment by TimWolla** [comment]
@ObieBent HAProxy 2.1 is EOL and 2.1.11 is not even the latest version of 2.1.x. Please upgrade to a supported version (I recommend 2.4 or 2.6). If you are still seeing issues, then please create *a new* bug report.
