### ISSUE TITLE
Segmentation fault when tcp-check is used with version 2.2

### ISSUE THREAD

**Issue by Julien75013** [haproxy/haproxy#945]
## Detailed description of the problem

Version 2.2 segfault as soon as started when tcp-check is used (see at the bottom of https://www.haproxy.com/fr/documentation/aloha/latest/traffic-management/lb-layer7/health-checks/ )

## Expected behavior

All was working fine with version 2.1

## What is your configuration?

```
global
        log /dev/log    local0
        log /dev/log    local1 notice

        chroot /var/lib/haproxy
        user haproxy
        group haproxy

        stats socket /run/haproxy/admin.sock mode 660 level admin
        stats timeout 30s
        stats maxconn 1

        daemon

defaults
        log     global
        mode    http
        maxconn 512

frontend ft_http
        bind *:80 tfo alpn h2,http/1.1
        default_backend bk_hello

fcgi-app php7.4-fpm
    docroot /var/www/default/fakejail

backend bk_hello
        use-fcgi-app php7.4-fpm
        option tcp-check
        tcp-check send-binary 0101000100080000000100000000000001040001004503000e03524551554553545f4d4554484f444745540b055343524950545f4e414d452f70696e670f055343524950545f46494c454e414d452f70696e67040455534552524F4F540000000104000100000000
        tcp-check expect binary 706f6e67
        server web-php-fpm 10.2.2.4:9004 proto fcgi check port 9000 observe layer7

```

## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 2.2.5-1~bpo10+1 2020/11/09 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.5.html
Running on: Linux 5.8.0-3-amd64 #1 SMP Debian 5.8.14-1 (2020-10-10) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-2.2.5=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=1).
Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1h  22 Sep 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.3.0
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services :
        prometheus-exporter

Available filters :
        [SPOE] spoe
        [COMP] compression
        [TRACE] trace
        [CACHE] cache
        [FCGI] fcgi-app

```

## If HAProxy crashed: Last outputs and backtraces

```
Nov 10 16:23:57 host haproxy[320933]: Proxy ft_http started.
Nov 10 16:23:57 host haproxy[320933]: Proxy ft_http started.
Nov 10 16:23:57 host haproxy[320933]: Proxy bk_hello started.
Nov 10 16:23:57 host haproxy[320933]: Proxy bk_hello started.
Nov 10 16:23:57 host haproxy[320933]: [NOTICE] 314/162357 (320933) : New worker #1 (320935) forked
Nov 10 16:23:57 host haproxy[320933]: [NOTICE] 314/162357 (320933) : haproxy version is 2.2.5-1~bpo10+1
Nov 10 16:23:57 host haproxy[320933]: [NOTICE] 314/162357 (320933) : path to executable is /usr/sbin/haproxy
Nov 10 16:23:57 host haproxy[320933]: [ALERT] 314/162357 (320933) : Current worker #1 (320935) exited with code 139 (Segmentation fault)
Nov 10 16:23:57 host haproxy[320933]: [ALERT] 314/162357 (320933) : exit-on-failure: killing every processes with SIGTERM
Nov 10 16:23:57 host haproxy[320933]: [WARNING] 314/162357 (320933) : All workers exited. Exiting... (139)

```

**Comment by lukastribus** [comment]
CC @capflam 
first bad commit: [12882cfaf85c6fdab78dd3372b25f7e728c6a180] BUG/MEDIUM: checks: Use the mux protocol specified on the server line

stacktrace from master:

```
lukas@dev:~/haproxy$ ./haproxy -vv
HA-Proxy version 2.4-dev0-288c07-41 2020/11/10 - https://haproxy.org/
Status: development branch - not safe for use in production.
Known bugs: https://github.com/haproxy/haproxy/issues?q=is:issue+is:open
Running on: Linux 4.4.0-146-generic #172-Ubuntu SMP Wed Apr 3 09:00:08 UTC 2019 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O0 -march=native -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
  OPTIONS = USE_THREAD= USE_OPENSSL=1

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE -THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL -LUA +FUTEX +ACCEPT4 -CLOSEFROM -ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with OpenSSL version : OpenSSL 1.0.2g  1 Mar 2016
Running on OpenSSL version : OpenSSL 1.0.2g  1 Mar 2016
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2
Built with network namespace support.
Built without compression support (neither USE_ZLIB nor USE_SLZ are set).
Compression algorithms supported : identity("identity")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built without multi-threading support (USE_THREAD not set).
Built without PCRE or PCRE2 support (using libc's regex instead)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 5.4.0 20160609

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : none

Available filters :
        [SPOE] spoe
        [CACHE] cache
        [FCGI] fcgi-app
        [COMP] compression
        [TRACE] trace

lukas@dev:~/haproxy$ sudo gdb haproxy core
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from haproxy...done.
[New LWP 20976]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./haproxy -f /home/lukas/haproxy-2.2/crashme.cfg -d'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000000057768b in htx_get_blk_ptr (htx=0x2863340, blk=0xfb861461) at include/haproxy/htx.h:370
370             return ((void *)htx->blocks + blk->addr);
(gdb) set pagination off
(gdb) t a a bt full

Thread 1 (Thread 0x7ff51b81a700 (LWP 20976)):
#0  0x000000000057768b in htx_get_blk_ptr (htx=0x2863340, blk=0xfb861461) at include/haproxy/htx.h:370
No locals.
#1  0x0000000000577b63 in http_get_stline (htx=0x2863340) at src/http_htx.c:72
        blk = 0xfb861461
#2  0x000000000047f52b in fcgi_snd_buf (cs=0x287aaf0, buf=0x280a968, count=2048, flags=0) at src/mux_fcgi.c:3948
        id = 1
        fstrm = 0x287b1c0
        fconn = 0x287aca0
        total = 0
        ret = 104
        htx = 0x2863340
        sl = 0x6
        blk = 0x4e5ab7 <b_peek+51>
        bsize = 0
        __FUNCTION__ = "fcgi_snd_buf"
#3  0x00000000004ea1b1 in tcpcheck_eval_send (check=0x280a910, rule=0x280a1e0) at src/tcpcheck.c:1356
        ret = TCPCHK_EVAL_CONTINUE
        send = 0x280a200
        cs = 0x287aaf0
        conn = 0x287ab40
        tmp = 0x0
        htx = 0x0
#4  0x00000000004ec8d3 in tcpcheck_main (check=0x280a910) at src/tcpcheck.c:2046
        rule = 0x280a1e0
        cs = 0x287aaf0
        conn = 0x287ab40
        must_read = 1
        last_read = 0
        ret = 16
        retcode = 0
        eval_ret = (unknown: 9316448)
#5  0x00000000005453fc in wake_srv_chk (cs=0x287aaf0) at src/check.c:780
        conn = 0x287ab40
        check = 0x280a910
        q = 0x280a900
        ret = 0
#6  0x0000000000545521 in event_srv_chk_io (t=0x2867350, ctx=0x280a910, state=0) at src/check.c:831
        check = 0x280a910
        cs = 0x287aaf0
#7  0x00000000005b98a0 in run_tasks_from_lists (budgets=0x7ffcc5d2cdb0) at src/task.c:465
        process = 0x5454eb <event_srv_chk_io>
        tl_queues = 0x91a0f0 <task_per_thread+48>
        t = 0x2867350
        budget_mask = 7 '\a'
        done = 0
        queue = 0
        state = 0
        ctx = 0x280a910
#8  0x00000000005b9fab in process_runnable_tasks () at src/task.c:689
        tt = 0x91a0c0 <task_per_thread>
        lrq = 0x0
        grq = 0x0
        t = 0xc5d2cdd0
        default_weights = {64, 48, 16}
        max = {198, 0, 0}
        max_total = 64
        tmp_list = 0x2867368
        queue = 3
        max_processed = 199
#9  0x0000000000586bc6 in run_poll_loop () at src/haproxy.c:2849
        next = -1277524066
        wake = 0
#10 0x0000000000586f4d in run_thread_poll_loop (data=0x0) at src/haproxy.c:3014
        ptaf = 0x8ea1d0 <per_thread_alloc_list>
        ptif = 0x8ea1e0 <per_thread_init_list>
        ptdf = 0x0
        ptff = 0x0
        init_left = 0
#11 0x000000000058878c in main (argc=4, argv=0x7ffcc5d2d0a8) at src/haproxy.c:3720
        err = 0
        retry = 200
        limit = {rlim_cur = 1048575, rlim_max = 1048576}
        pidfd = -1
(gdb) quit
lukas@dev:~/haproxy$
```

**Comment by capflam** [comment]
Thanks @lukastribus , I'll take a look.

**Comment by capflam** [comment]
We identified the bug, @a-denoyelle is on a fix.

**Comment by naphta** [comment]
> We identified the bug, @a-denoyelle is on a fix.

@capflam We're seeing something similar in 2.2 with proxied HTTP2 (with health checks), it's only under slight load that we can get the segfault to happen but it is consistent. Is the bug possibly related to the problem we're having?

**Comment by a-denoyelle** [comment]
Jake Hill <notifications@github.com> wrote:

> > We identified the bug, @a-denoyelle is on a fix.
> @capflam We're seeing something similar in 2.2 with proxied HTTP2 (with health checks), it's only under slight load that we can get the segfault to happen but it is consistent. Is the bug possibly related to the problem we're having?

The bug I discovered is systematic due to a certain config and does not
depend on load condition so it seems to me that it is not the same
problem.

-- 
Amaury Denoyelle

**Comment by naphta** [comment]
That's interesting. I'll open up a new ticket with my problem configuration, but for now we've solved the problem by removing H2 from the equation.

**Comment by capflam** [comment]
Now fixed. Backports are on the way. Thanks !
